### ISSUE TITLE
Queries for posts that are private are not showing?

### ISSUE THREAD

**Issue by kuworking** [wp-graphql/wp-graphql-acf#104]
Trying to use graphql to retrieve information from private content and using ACF, but I am seeing that if posts are private they are not shown in graphiQL

Is this because it cannot be done?

**Comment by jasonbahl** [comment]
@kuworking private posts require authentication and permission to view them. Much like a public user cannot see private posts in a WordPress theme, private posts also cannot be viewed by GraphQL API requests without proper authentication. 

You can read more about Authentication and Authorization in WPGraphQL here: https://docs.wpgraphql.com/guides/authentication-and-authorization/

Let me know if you still have questions. Thanks!

**Comment by kuworking** [comment]
But @jasonbahl neither through GraphiQL when logged as admin?
