### ISSUE TITLE
ACF User field value treated as function

### ISSUE THREAD

**Issue by iamlili** [wp-graphql/wp-graphql-acf#105]
Hi,

I think i've come across a bug.

I have a Custom Post Type with ACF group called "stallDetails"

One of the fields in the group is a **User** field called "stallholder"

I assign the word "**count**" as a user's lastName (or firstName)

I assign that user to myposttype (stallholder field)

If that user is only assigned to one myposttype the query returned is correct

HOWEVER if i have multiple myposttypes with that same user assigned to 'stallholder' the query returned is incorrect

![image](https://user-images.githubusercontent.com/13793240/73701344-59007200-473d-11ea-833c-eb60f7211c6b.png)

The name "Count" (because it's also a php function name) is being treated as a function (for the 2nd, 3rd occurance, not the 1st)

You can see the function being called in the error log

`PHP Warning:  count() expects at least 1 parameter, 0 given in ...../web/app/plugins/wp-graphql/src/Model/Model.php on line 149`

_Note: if different users have the same name, its fine. It only happens when the same user is chosen on multiple posts_

wp-graphql version 0.6.1
wp-graphql-acf version 0.3.1

**Comment by henrikwirth** [comment]
Same happens with the `author` fields lastName. So I think it's related to the core plugin.

![image](https://user-images.githubusercontent.com/10786260/73834457-08a41580-480c-11ea-8218-46efa9ac9415.png)

**Comment by henrikwirth** [comment]
This goes for all the fields pretty much.
![image](https://user-images.githubusercontent.com/10786260/73835231-59683e00-480d-11ea-9d72-c4506fd8b425.png)

**Comment by henrikwirth** [comment]
I close this one here in favor of the issue in WP-GraphQL: https://github.com/wp-graphql/wp-graphql/issues/1144
