### ISSUE TITLE
Flexible content empty layout, causes a 503, DB connection error

### ISSUE THREAD

**Issue by sirichards** [wp-graphql/wp-graphql-acf#106]
Creating an empty layout within a flexible content field type using ACF causes the plugin to break.
The empty layout must be beneath other layouts containing fields to trigger this bug.

![1](https://user-images.githubusercontent.com/21104091/74679803-bd4c1880-51b6-11ea-9009-fda75bcddea1.jpg)

When visiting /graphql
the server responded with a status of 503 (Service Unavailable), and no nodes are accessible 

PHP errors

Warning: Error while sending QUERY packet. PID=4274 in /opt/bitnami/apps/wordpress/htdocs/wp-includes/wp-db.php on line 2030

Error reconnecting to the database

Looks like there is some sort of continuous loop happening.

**Comment by jasonbahl** [comment]
This issue has been resolved in the re-architecture of the plugin over here: https://github.com/wp-graphq/wpgraphql-acf. 

I tested with the following field grou: 

[acf-export-2023-11-07.json.zip](https://github.com/wp-graphql/wp-graphql-acf/files/13289039/acf-export-2023-11-07.json.zip)

The Schema loads without error even with a flexible content field that has a layout with no fields. 

----

NOTE: This repo will be getting archived in the not-too-distant future in favor of the re-architected plugin which will be released on WordPress.org in the near future.
