### ISSUE TITLE
Field showing up in wordpress but not in React

### ISSUE THREAD

**Issue by nerdess** [wp-graphql/wp-graphql-acf#107]
First of all: Thanks for this great Wordpress plugin :) It works really well, however, just now I stumbled over something that I can't get my head round. 

I did nothing unusual, just added a new field

`Vision_Visiondetail_Problem_Piechart`

using ACF and ticked "Show in GraphQL". 

In GraphiQL within Wordpress it shows up fine:

![Bildschirmfoto 2020-02-18 um 12 46 42](https://user-images.githubusercontent.com/711925/74734095-26cb3600-524e-11ea-955c-ffa0333780c4.png)

In GraphiQL on my React/Gatsby environment it is missing though:

![Bildschirmfoto 2020-02-18 um 12 46 03](https://user-images.githubusercontent.com/711925/74734106-2c288080-524e-11ea-8e4b-466de3b9157b.png)

What could be the probem? Any hints on how to debug this would be great (I am fairly new to GraphQL so I am sorry if I am missing something obvious here)

**Comment by nerdess** [comment]
btw: in the console when i run "gatsby devlop" i get this error:

`Abstract type WPGraphQL_Vision_Visiondetail_Problem must resolve to an Object type at runtime for field WPGraphQL_Vision_Visiondetail.problem with value { __typename: "WPGraphQL_Vision_Visiondetail_Problem_Piechart" }, received "undefined". Either the WPGraphQL_Vision_Visiondetail_Problem type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function.`

**Comment by sirichards** [comment]
Hi,

Have you tried running `gatsby clean`? I noticed my fields were not showing up but after running that then `gatsby develop` they appeared.

**Comment by jasonbahl** [comment]
@nerdess can you try `gatsby clean` as @sirichards suggested and report back?

Any time you add/change fields in WordPress, Gatsby needs to refetch the Schema and merge it into the Gatsby Schema.

**Comment by IshaVohra** [comment]
Thanks @sirichards @jasonbahl, I was facing the same error and the above solution worked for me.

**Comment by jasonbahl** [comment]
Closed as I believe this was a Gatsby Source issue and cleaning the Gatsby cache resolves. Gatsby Source WordPress v4+ I believe automatically updates when ACF field groups are changed, too
