### ISSUE TITLE
Deprecate notice on Composer v 1.10.0

### ISSUE THREAD

**Issue by dsturm** [wp-graphql/wp-graphql-acf#113]
Hey,

this package throws three deprecation notices on installing / updating with Composer v 1.10.0

```sh
Deprecation Notice: Class WPGraphQL\ACF\ACF located in ./web/app/plugins/wp-graphql-acf/src/class-acf.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.0/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class WPGraphQL\ACF\ACF_Settings located in ./web/app/plugins/wp-graphql-acf/src/class-acfsettings.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.0/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class WPGraphQL\ACF\Config located in ./web/app/plugins/wp-graphql-acf/src/class-config.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.0/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
```

Cheers,
Daniel

**Comment by jasonbahl** [comment]
@dsturm hey!

Can you provide some instructions on replicating this?

I'm on Composer v1.10.1

I setup a [Bedrock](https://roots.io/docs/bedrock/master/installation/) project and used it to install WPGraphQL and WPGraphQL. 

I ran `composer require wp-graphql/wp-graphql` and `composer require wp-graphql/wp-graphql-acf` and did not get any deprecation notices. 

Is there another way I should go about this to replicate?

**Comment by dsturm** [comment]
Hey @jasonbahl,

on Composer v1.10.1 I can no longer replicate the problem either. [The changelog](https://github.com/composer/composer/releases/tag/1.10.1) lists a fix for this. So I think this issue could be closed.

Best,
Daniel
