### ISSUE TITLE
Undefined index: ID acf-field-functions.php on line 361

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-acf#120]
I get multiple notices on one of my sites and it completely breaks the whole site. 

`Notice: Undefined index: ID in /home/example.com/web/app/plugins/advanced-custom-fields-pro/includes/acf-field-functions.php on line 361
`

Until it ultimately runs out of memory:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 28672 bytes) in /home/example.com/web/app/plugins/wp-graphql/src/Registry/TypeRegistry.php on line 154

When _deactivating_ wp-graphql-acf the notice goes away.

Not sure if this is related but this plugin had the same notice: https://github.com/jameelmoses/acf-flexible-content-preview/commit/946bc90b7c3249f1be44b16aa043ebe1f5ebac8e

**Update**: When I delete a field group containing a flexible field the error goes away so it might be related not same issue as the plugin above. 

**Update 2**: Found the issue. Had an empty "Layout" in my flexible field. For a divider component in my page builder (needs no options) and that broke everything. Maybe an edge case... You can close this issue. Up to you.

**Comment by jasonbahl** [comment]
@zamson this is a good issue that we need to address. Thanks for all the details!

**Comment by henrikwirth** [comment]
This seems to be related to: https://github.com/wp-graphql/wp-graphql-acf/issues/131

This PR solved it for our usecase: https://github.com/wp-graphql/wp-graphql-acf/pull/168

**Comment by jasonbahl** [comment]
Closed by #168
