### ISSUE TITLE
Inconsistent filter naming

### ISSUE THREAD

**Issue by esamattis** [wp-graphql/wp-graphql-acf#123]
The source uses both `wpgraphql_acf_` and `graphql_acf_` prefixes in `apply_filters()`. I think we should have only one naming convention.

I'd prefer `graphql_acf_` as it is what the core uses.

**Comment by jasonbahl** [comment]
Good call. That's fair for sure.

**Comment by jasonbahl** [comment]
This has been resolved in the new version of WPGraphQL for ACF over here: ttps://github.com/wp-graphql/wpgraphql-acf

see: https://github.com/wp-graphql/wpgraphql-acf/pull/67

This version of WPGraphQL for ACF will be archived in the not-too-distant future in favor of the new one.
