### ISSUE TITLE
Field  settings on admin area defaulting to "Show in GraphQL"

### ISSUE THREAD

**Issue by foltra** [wp-graphql/wp-graphql-acf#127]
Hi,

First, thank you much for this amazing work. 

I am using graphql to expose certain post types with some associate data to some javascript calendar component. 
If I am modifying an unrelated fieldset, a layout field for example, "show in graphql " defaults to active and subsequently **requires** to fill "graphql field name", this has become an annoyance.

This default behavior would rather be opt-in, that you could select on general settings.

**Comment by jasonbahl** [comment]
👋🏻  Sorry for the delay on this, but with v0.5.0 (#250) this is resolved!

The GraphQL Settings have been re-worked and moved into their own "GraphQL Settings" panel on the field group settings page. 

The "graphql_field_name" field is now conditional based on the state of the `show_in_graphql` setting. If the field group is NOT set to show_in_graphql, the `graphql_field_name` will not be visible, and will not be required. 

If the field group IS set to show_in_graphql, the `graphql_field_name` is visible, and required, but is filled with a name based on the Field Group Title (but can be changed). 

You can see this in action here: https://www.youtube.com/watch?v=VvrZGrcwv0Y
