### ISSUE TITLE
Add Explicit options for adding ACF Field Groups to the Schema

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#135]
Currently, the way WPGraphQL for ACF implicitly maps field groups from ACF Location Rules to the WPGraphQL Schema causes a lot of confusion. 

ACF has a lot of location rules that require specific run-time context that's not available for Schema generation. 

For example, rules such as `Page is not equal to Home` or `Post is equal to Hello World` don't exactly map well to a Schema. 

The Schema is representative of all Types available, and context such as whether a Page is the Home Page, or a Post is the "Hello World" post is runtime context. 

So, in an effort to reduce this confusion, I'm working on a more explicit setting where you can define the GraphQL Types to show the ACF Field Group on, and _not_ rely on the location rules at all. 

The location rules can be used for determining the editing experience, and the new setting can be used for determining explicitly which Types the field group should be available on in the Schema. 

Something like the following: 

![Screen Shot 2020-04-20 at 1 56 00 PM](https://user-images.githubusercontent.com/1260765/81082131-1a02c980-8eb0-11ea-9f0e-1a0d004545ab.png)

This checkbox field will show all Types that _can_ have field groups associated with them. Post Types and Taxonomies that are exposed to GraphQL, Users, Comments, Menus, Menu Items, Media, Page Templates, etc.

**Comment by AbeCole** [comment]
Looks good, definitely separating the 'display' logic of locations rules from the 'filtering' logic of what is/isn't added to the schema feels more correct

**Comment by rburgst** [comment]
when can we expect this to be implemented?

**Comment by willem-aart** [comment]
Would _love_ to see this happen 😃👍🏻

**Comment by supriome** [comment]
How's the development of this feature coming along?

**Comment by AbeCole** [comment]
> How's the development of this feature coming along?

Not sure myself, but if you want a quick workaround take a look at https://github.com/wp-graphql/wp-graphql-acf/pull/134

**Comment by magicspon** [comment]
Any updates on this?

**Comment by ledniy** [comment]
@jasonbahl sorry for tagging you, but do you plan to complete it? It's a deal breaker for me to use new gatsby wordpress source and wp-graphql, because my WP admin dashboard build on top of location rules and users see only what they can add for specific pages/types/categories. So the separation from location rules is very important in my case. Thanks in advance.

**Comment by supriome** [comment]
The location rule is key to WordPress as a headless CMS, and only pages and posts that can use Graphql are specifically limited to WordPress customization. Whether it's Gatsbyjs or nextjs combined with WordPress, the inability to query custom ACF information with Graphql is the biggest problem limiting further development. I've been stuck on this problem for a particularly long time. The solution upstairs doesn't solve my problem. I need the location rule to customize the ACF fields of the page with different category posts.

**Comment by AbeCole** [comment]
@supriome Just to say the 'workaround' solution I provided will still 'work'. It does have 2 caveats: (1) The acf field groups will appear on more objects than they should (2) You can't have 2 field groups with the same 'GraphQL name'

**Comment by supriome** [comment]
@AbeCole Thanks again, I'll try this method on my next project. But for now, my solution is to get the data through REST API instead of using GraphQL

**Comment by rsm0128** [comment]
I created a [PR](https://github.com/wp-graphql/wp-graphql-acf/pull/207) to handle this issue.

**Comment by abdulrauf11** [comment]
Any updates on this? This issue seems to be a deal-breaker when it comes to building client projects.

**Comment by AbeCole** [comment]
> Any updates on this? This issue seems to be a deal-breaker when it comes to building client projects.

Look at the [PR](https://github.com/wp-graphql/wp-graphql-acf/pull/207) @rsm0128 mentioned, seems to be progress happening there, but nothing completely merged to main branch yet
