### ISSUE TITLE
Add Gravityforms Add-on support

### ISSUE THREAD

**Issue by Twansparant** [wp-graphql/wp-graphql-acf#140]
I would love to see the [Advanced Custom Fields: Gravityforms Add-on](https://wordpress.org/plugins/acf-gravityforms-add-on/) supported by WPGraphQL ACF.
Would this be possible? And how could I add support for it myself?

Thanks a lot!

**Comment by Twansparant** [comment]
I made a [PR](https://github.com/wp-graphql/wp-graphql-acf/pull/143) for this.

**Comment by Ebeldev** [comment]
Unfortunaly this issue and the pull request is still not fully working. 

Any news on that?

**Comment by jasonbahl** [comment]
👋🏻 We're working on a new version of WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. 

The new version has an API for adding support for third party ACF Field Types. 

In fact, the plugin comes with support for [ACF Extended](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/AcfExtended.php) Field Types and you can use them as a model for adding support for additional ACF Field Types. 

For example: 

- [ACFE Advanced Link](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeAdvancedLink.php)
- [ACFE Countries](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeCountries.php)

Here's also a GIST showing how @CesarBenavides777 mapped the ACF Table field type to the GraphQL Schema: https://gist.github.com/CesarBenavides777/79b158db8355ddbc349fbf9b3272ae47

While we won't be supporting all ACF Field Type extensions out of the box, we will be supporting the APIs for developers to add their own custom ACF Field Types more easily. 

We'd recommend checking out the new version of WPGraphQL for ACF as it's what we'll be supporting going forward. It will have a stable release on WordPress.org in the near future and this repo will be archived.
