### ISSUE TITLE
Feature-Request: Add filter for root-field-config on RootQuery-field

### ISSUE THREAD

**Issue by davidfaber** [wp-graphql/wp-graphql-acf#142]
I am using https://github.com/BeAPI/acf-options-for-polylang to allow different values for different languages in acf-options-pages. To make this plugin work with wp-graphql-acf I need to filter the field-config on the root field, so I can add a language-argument and set the language on the resolve.

I use the filter this way:
```php
<?php
/**
 * Adding language-option for acf-options-pages
 */
add_filter('wpgraphql_acf_register_root_field_options_page', function ($config) {
    $config['args'] = [
        'language' => [
            'type' => [
                'non_null' => 'LanguageCodeFilterEnum',
            ],
        ],
    ];

    $config['resolve'] = function ($root, $args) use ($config) {
        $language = isset($args['language']) ? $args['language'] : pll_default_language('slug');
        PLL()->curlang = PLL()->model->get_language($language);

        return $config['resolve']();
    };

    return $config;
});
```

I already created a Pull-Request for this.

It would be awesome if you could merge this!

**Comment by davidfaber** [comment]
MR is #141

**Comment by esamattis** [comment]
I just used the `graphql_RootQuery_fields` filter in wp-graphql-polylang to implement the build in BeAPI/acf-options-for-polylang support

https://github.com/valu-digital/wp-graphql-polylang/blob/a3e6bcf360b194731a199af9090c1f4f573feda8/src/OptionsPages.php#L81-L100

**Comment by davidfaber** [comment]
Thanks @esamattis, I am using your plugin but I completely missed the part where you said I MUST set `'graphql_field_name' => 'siteSettings'`. So this issue is closed then. Awesome!

I guess, when I have some time inbetween I'll help out the guys from wp-graphql writing some documentation. It's simply wonderful, what they (and also people like you) are doing, they deserve some support!!

Thanks!
