### ISSUE TITLE
one-to-many relationship, querying child based on parent support

### ISSUE THREAD

**Issue by mmb12345** [wp-graphql/wp-graphql-acf#148]
i can grab all the children when querying for parent, however i can't seem to figure out how to grab a single child given the parents id.  

in prisma, you can query for a comment by using operation arguments that provide either who the author of the comment is (an author can have multiple comments) or what post it was a reply to (each post can have multiple comments)

**Comment by jasonbahl** [comment]
@warmSnowyMorning if you know the database ID of the parent, you can query like so: 

```graphql
{
  replies: comments(where: {parent: 2}) {
    nodes {
      id
      content
    }
  }
}
```

![Screen Shot 2020-06-22 at 7 55 13 AM](https://user-images.githubusercontent.com/1260765/85295848-ba5f7e00-b45d-11ea-9302-ce1b06e406fb.png)


Here it is in action:
