### ISSUE TITLE
Slow Queries

### ISSUE THREAD

**Issue by ashhitch** [wp-graphql/wp-graphql-acf#154]
Since updating the main WpGraphQL plugin to `0.10.3` I am getting a really slow query, I seem to have narrowed it down to an ACF gallery field/media items, that tips it over the edge to timeout wise.

For refrence using:
WpGatsby is at `0.4.9`
gatsby-source-wordpress-experimental is at `1.0.4`

If I set gatsby-source-wordpress-experimental to only fetch 10 posts its works, but this was not an issue with `0.9.x`

**Comment by jasonbahl** [comment]
I believe one thing that will help greatly here is to implement DataLoader throughout this plugin. 

There are a lot of fields that suffer from n+1 loading that could benefit from DataLoader. 

It would be good to get more information about the underlying SQL queries that are being generated for your specific situation so we can identify if this indeed is the culprit of the slow performance.

**Comment by ashhitch** [comment]
@jasonbahl ill try dig out where this was happening and report back.

**Comment by jasonbahl** [comment]
@ashhitch we're working on a new version of WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf.

We'll be archiving this repo in the not-too-distant future and supporting the new version going forward. 

If you're experiencing slow-downs like this on the new version of the plugin, please open a new issue with steps to reproduce on that repo. 

Thanks! 🙏🏻
