### ISSUE TITLE
/graphql crashes with a 500 error when plugin is active

### ISSUE THREAD

**Issue by madeodev** [wp-graphql/wp-graphql-acf#158]
Hi,

The plugin when activated breaks the GraphQL endpoint `/graphql`, I enabled debug from wp-config, seeing the following PHP error:

`Notice: Undefined index: ID in /../../../wp-content/plugins/advanced-custom-fields-pro/includes/acf-field-functions.php on line 361` repeated several times, then..

`Fatal error: Allowed memory size of XXXXXXXXX bytes exhausted (tried to allocate XXXX bytes) in /../../../wp-content/plugins/wp-graphql-master/src/Registry/TypeRegistry.php on line 729
`

No matter how I increases the memory limit, it always exceeds it just by a tiny bit then throws a 500 error, also if helpful to note, the more I increase memory limit, the more lines I see of the (Notice: undefined index..) then the fatal error.

Could you please assist, thank you so much!

**Comment by lqze** [comment]
@madeodev Why did you close this?

**Comment by madeodev** [comment]
@lqze were running version 0.3.4, then I noticed they released a new version two days ago (back then), I upgraded and was no longer having this issue.

**Comment by lqze** [comment]
Cool, interesting.
