### ISSUE TITLE
Update Readme for Options Page Documentation

### ISSUE THREAD

**Issue by chrisherold** [wp-graphql/wp-graphql-acf#162]
Looks like the documentation for the ACF Options page got lost as the WPGraphQL docs got updated to reference the GitHub repo for each extension directly.

In https://github.com/wp-graphql/wp-graphql-acf/pull/66 the options page support was added and there's a comment about adding documentation directly to the `wp-graphql` repo here:
https://github.com/wp-graphql/wp-graphql/pull/1010

But now that `wp-graphql/docs/source/extensions/wpgraphql-advanced-custom-fields.mdx` has been removed in favor of the Readme here, should the Options page documentation get added back to this Readme?

**Comment by jasonbahl** [comment]
Docs for options pages in the README here: https://github.com/wp-graphql/wp-graphql-acf#options-pages
