### ISSUE TITLE
Feature request: mutations

### ISSUE THREAD

**Issue by FreddieFruitSticks** [wp-graphql/wp-graphql-acf#166]
Hi

Mutations would be a great addition. Are there any plans for this in the near future? I have read on the ACF for GraphQL website that there is currently no support for this.

Is there a recommended work-around that someone might suggest in the mean time?

**Comment by pickleat** [comment]
Uhoh, I'm about to have the same problem if they aren't supported.

**Comment by pickleat** [comment]
@FreddieFruitSticks Not sure of your use case, but I'm attempting to figure out a workaround in the meantime. I need to update data based on the client side visiting the page, but I haven't had much success yet.

**Comment by FreddieFruitSticks** [comment]
@pickleat great! Keen to see what you come up with. I had to move over to the REST api unfortunately, due to this missing feature.

**Comment by pickleat** [comment]
@FreddieFruitSticks that's my plan as well, but not going super well. Any chance you could share how you worked around it with the REST API? 
UPDATE: I've got it, I'll share once the code is cleaned up!

**Comment by cesarkohl** [comment]
@pickleat Can you share it?

**Comment by saleebm** [comment]
Here is a child theme example with how I implemented mutations for wp graphql fields, not necessarily ACF but can be constructed to do the same with any ACF fields. 

[link](https://github.com/saleebm/wp-acf-mutations)

**Comment by jack-pallot** [comment]
Completely agree that this is an important feature to have. At the moment I'm also planning to use REST to solve this. 

In the meantime even a few examples of custom mutations for more difficult fields like repeaters, images, flexible content would go far in making this easier to achieve.

**Comment by lance-anderson** [comment]
Perhaps it's worth noting that wp-graphql exposes the [register_graphql_mutation](https://www.wpgraphql.com/functions/register_graphql_mutation/) function which be used to leverage ACF's [update_field](https://www.advancedcustomfields.com/resources/update_field/) function and other APIs for updating WP data.

**Comment by vstrelianyi** [comment]
would be great to have mutations build in the plugin. or at least there should be some kind of step-by-step instruction how to implement that...
I have tried what you have advised.. but without any success.

**Comment by colmobildev** [comment]
Very important feature!

**Comment by jasonbahl** [comment]
👋🏻 We are re-building WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. 

I've created a new issue to track mutation support (and explain some current blockers). see: https://github.com/wp-graphql/wpgraphql-acf/issues/109

I'm going to close this in favor of tracking it in the new repo.
