### ISSUE TITLE
error in gatsby-node js on active plugin in the wordpress

### ISSUE THREAD

**Issue by tinelli22** [wp-graphql/wp-graphql-acf#169]
When I active the plugin wp-graphql-acf-master, my gatsby project in gatsby-node.js launch this error:

 const { data } = await graphql(`

 Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
  
  - graphql-runner.ts:98 GraphQLRunner.validate
    [...]/[gatsby]/src/query/graphql-runner.ts:98:22
  
  - graphql-runner.ts:162 GraphQLRunner.query
    [....]/[gatsby]/src/query/graphql-runner.ts:162:25
  
  - create-graphql-runner.ts:59 
    [...]/[gatsby]/src/bootstrap/create-graphql-runner.ts:59:8
  
  - gatsby-node.js:58 Object.exports.createPages
------//-----
A part of the code:

exports.createPages = async ({ actions, graphql }) => {
  const { createPage } = actions
 ......
  const PostTemplate = path.resolve(`./src/templates/blog/Post/index.js`)

  const { data } = await graphql(`
  .............
..................
}

**Comment by jasonbahl** [comment]
@tinelli22 this looks like perhaps you've added an ACF Field Group with an empty `graphQLFieldName` setting. 

Can you make sure any field groups you have in ACF have a GraphQL Field Name set?

![Screen Shot 2020-09-11 at 8 59 06 AM](https://user-images.githubusercontent.com/1260765/92941034-16a6be00-f40d-11ea-9fb5-e4601b9a67a7.png)

**Comment by tinelli22** [comment]
I create only one, following your example on "WPGraphQL for ACF" youtube

**Comment by hashinteractive** [comment]
I'm getting this same error on `gatsby develop` command and it's erring out:

`Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.`

The GraphQL Field Name is populated and it's showing up in the WPGraphiQL explorer but when I go to build/develop with Gatsby it's throwing this error. 

ACF Settings:

![image](https://user-images.githubusercontent.com/12477388/93956338-93903c80-fd17-11ea-9cbd-85e054539fd7.png)


WPGraphiQL Explorer:

![image](https://user-images.githubusercontent.com/12477388/93956446-d94d0500-fd17-11ea-9779-7c16dc3ba80c.png)


Gatsby Develop/Build Error:

![image](https://user-images.githubusercontent.com/12477388/93956510-01d4ff00-fd18-11ea-9683-b2a2d7c410af.png)

Any ideas what this might be causing this?

**Comment by jasonbahl** [comment]
Can you provide exports of your ACF field groups? Perhaps there's something in the Field Group registration that can help replicate this.

**Comment by jasonbahl** [comment]
@hashinteractive are you also using Custom Post Type UI and WPGraphQL for Custom Post Type UI by chance?

**Comment by hashinteractive** [comment]
@jasonbahl thanks for taking a look. I'm not using Custom Post Type UI

I believe it had something to do with when the fieldGroup was saved the fieldGroup name (for graphql schema) was somehow saved as empty (even though I had filled out the GraphQL Field Name) and even if I changed/updated the GraphQL Field Name it still was throwing this error (despite clearing data cache using gatsby clean).

Tyler addressed this issue and might be resolved on Gatsby side: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/169

I had to resolve this by creating a new instance of WordPress, installed required plugins (WP GraphQL, WP Gatsby) and porting data over. It was early on in the project so I wasn't too far in so it wasn't a big deal for me but anyone further along in a project getting this error might have other concerns.

**Comment by jasonbahl** [comment]
Ok. Interesting. 

Ya, my only thought is that somehow some ACF Field Groups were saved with `show_in_graphql => true` but no `graphql_field_name`. 

I'll see if I can reproduce this and guard against it.

**Comment by hashinteractive** [comment]
That might have been the case, I have not done any programmatic definition for the the **ACF Field Group** such as `show_in_graphql => true` and always have used the GUI on the ACF Field Group editor to name the field but maybe for some reason it wasn't saving (or saving as an empty string) in the admin editor and that was creating the error. I haven't been able to reproduce since. 

![image](https://user-images.githubusercontent.com/12477388/113042036-50000a80-9160-11eb-9a4d-e1f5e8fdab67.png)

**Comment by jasonbahl** [comment]
WPGraphQL v0.5.0 has a lot of improvements to the settings fields. 

I've not been able to reproduce this issue, even pre-v0.5.0, but I believe the changes to v0.5.0 guard against this even more. 

I'm going to close this, but if the issue persists after v0.5.0, please open a new issue with clear steps to reproduce and we'll look into it further.
