### ISSUE TITLE
Question: how to use it with "Repeater" fields?

### ISSUE THREAD

**Issue by TimurGumarov** [wp-graphql/wp-graphql-acf#17]
Hi all!
Trying this plugin. It's workin', but i can't anderstand how to use with repeater fields.
I found "(repeater_name)Field" and i think that all inside fields must be in "group => fields". But i found nothing there. 
Can you explain me how to use it with Repeater fields in a proper way?

**Comment by jasonbahl** [comment]
Hey, this plugin is a ways away from being ready for use. Repeater and flex fields aren't supported yet, and most of the other fields are only partially implemented.

**Comment by TimurGumarov** [comment]
Aw! Thats OK then. I will wait for this plugin getting strength to use it in my projects! 
Thank you for your work!)
