### ISSUE TITLE
New GraphQL fields not showing in the Schema

### ISSUE THREAD

**Issue by bftrepo** [wp-graphql/wp-graphql-acf#17]
See attached file. I can find the acfEventFields in the Schema, but searching for the acfSubHead does not display. I see in another closed issue that I have to trash my Field Group first?
![acfField](https://user-images.githubusercontent.com/4974677/61461478-c209cf00-a93e-11e9-8d1f-75a039eabbd5.jpg)

**Comment by bftrepo** [comment]
I also see in another closed issue that if I have an "acf-json" folder in my theme, this can prevent fields from showing... is that still an issue? Can I solve this by renaming the folder as [mentioned here](https://www.advancedcustomfields.com/resources/local-json/)?

I took a look at those json files and it looks like they're showing graphql settings correctly:
`"active": 1,
    "description": "",
    "show_in_graphql": 1,
    "graphql_field_name": "acfSubHead",
    "modified": 1563391188`

**Comment by jasonbahl** [comment]
@bftrepo as far as I know, the acf-json issue has been resolved. You can _try_ the trash/restore trick, but I don't _think_ that's an issue anymore. 

Can you provide a .json export of your field group that's not displaying so I can check it out?

**Comment by bftrepo** [comment]
@jasonbahl - thanks for looking into this. Looks like I can't attach a json file, but below is the code:
`[
    {
        "key": "group_5b64bf6e824ba",
        "title": "Truck Fields",
        "fields": [
            {
                "key": "field_5b6847f390ac6",
                "label": "At a Glance",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "left",
                "endpoint": 0
            },
            {
                "key": "field_5b64bf9c41b94",
                "label": "At a Glance",
                "name": "truck_at_a_glance",
                "type": "repeater",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "collapsed": "",
                "min": 0,
                "max": 0,
                "layout": "row",
                "button_label": "Add Bullet",
                "sub_fields": [
                    {
                        "key": "field_5b64bfec41b95",
                        "label": "At a Glance",
                        "name": "at_a_glance_item",
                        "type": "text",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "maxlength": ""
                    }
                ]
            },
            {
                "key": "field_5b6848a06dcfa",
                "label": "Truck Specs",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "left",
                "endpoint": 0
            },
            {
                "key": "field_5b6848ae6dcfb",
                "label": "Specs",
                "name": "truck_specs",
                "type": "repeater",
                "instructions": "",
                "required": 0,
                "conditional_logic": [
                    [
                        {
                            "field": "field_5b6848f66dcfe",
                            "operator": "==",
                            "value": "1"
                        }
                    ]
                ],
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "collapsed": "",
                "min": 0,
                "max": 0,
                "layout": "row",
                "button_label": "Add Spec",
                "sub_fields": [
                    {
                        "key": "field_5b6848bc6dcfc",
                        "label": "Spec Label",
                        "name": "spec_label",
                        "type": "text",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "maxlength": ""
                    },
                    {
                        "key": "field_5b6848df6dcfd",
                        "label": "The Spec",
                        "name": "the_spec",
                        "type": "wysiwyg",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "tabs": "all",
                        "toolbar": "full",
                        "media_upload": 0,
                        "delay": 0
                    }
                ]
            },
            {
                "key": "field_5bb4dd016c748",
                "label": "Truck Specs Table",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "left",
                "endpoint": 0
            },
            {
                "key": "field_5bb4dd306c74c",
                "label": "Truck Specs Table",
                "name": "truck_specs_table",
                "type": "wysiwyg",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "tabs": "text",
                "media_upload": 0,
                "toolbar": "full",
                "delay": 0
            },
            {
                "key": "field_5b6b3904a2f97",
                "label": "Truck Features",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "top",
                "endpoint": 0
            },
            {
                "key": "field_5b6b3919a2f98",
                "label": "Add Truck Features",
                "name": "add_truck_features",
                "type": "repeater",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "collapsed": "",
                "min": 0,
                "max": 0,
                "layout": "row",
                "button_label": "Add Feature",
                "sub_fields": [
                    {
                        "key": "field_5bd9f2330c713",
                        "label": "Title",
                        "name": "feature_title",
                        "type": "text",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "placeholder": "",
                        "prepend": "",
                        "append": "",
                        "maxlength": ""
                    },
                    {
                        "key": "field_5bd9f2520c714",
                        "label": "Content",
                        "name": "feature_content",
                        "type": "wysiwyg",
                        "instructions": "",
                        "required": 0,
                        "conditional_logic": 0,
                        "wrapper": {
                            "width": "",
                            "class": "",
                            "id": ""
                        },
                        "default_value": "",
                        "tabs": "all",
                        "toolbar": "full",
                        "media_upload": 0,
                        "delay": 0
                    }
                ]
            },
            {
                "key": "field_5bce1f4138fb8",
                "label": "Truck Chassis",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "top",
                "endpoint": 0
            },
            {
                "key": "field_5bce1f8038fb9",
                "label": "Add Truck Chassis",
                "name": "add_truck_chassis",
                "type": "image",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "return_format": "url",
                "preview_size": "thumbnail",
                "library": "all",
                "min_width": "",
                "min_height": "",
                "min_size": "",
                "max_width": "",
                "max_height": "",
                "max_size": "",
                "mime_types": ""
            },
            {
                "key": "field_5b6b1423912e7",
                "label": "Truck Innovations",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "left",
                "endpoint": 0
            },
            {
                "key": "field_5b6b144a912e8",
                "label": "Add Truck Innovations",
                "name": "add_truck_innovations",
                "type": "relationship",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "post_type": [
                    "truck_innovations"
                ],
                "taxonomy": [],
                "filters": "",
                "elements": "",
                "min": "",
                "max": "",
                "return_format": "object"
            },
            {
                "key": "field_5b6d97ae53e18",
                "label": "Truck Resources",
                "name": "",
                "type": "tab",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "placement": "left",
                "endpoint": 0
            },
            {
                "key": "field_5b6d978853e17",
                "label": "Assign Resources",
                "name": "assign_resources",
                "type": "relationship",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "post_type": [
                    "spartan_resources"
                ],
                "taxonomy": [],
                "filters": [
                    "taxonomy"
                ],
                "elements": "",
                "min": "",
                "max": "",
                "return_format": "object"
            }
        ],
        "location": [
            [
                {
                    "param": "page_template",
                    "operator": "==",
                    "value": "templates\/truck.php"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": "",
        "active": 1,
        "description": "",
        "show_in_graphql": 1,
        "graphql_field_name": "acfTruckFields"
    }
]`

**Comment by jasonbahl** [comment]
@bftrepo ah! At the moment, the location rule of setting a field group to a specific page template isn't supported. 

I have a few ideas on how to add support for this, but I've not yet settled on which way to go. 

The "context" of ACF locations doesn't match with GraphQL 1:1, because ACF location rules are often based on the context of an individual page/post, but the GraphQL Schema is independant of any one piece of content.

So, adding a Field Group to a page template is a bit tricky, because a page template is only relevant to a specific page, where the GraphQL Schema is representative of everything that's possible in the API, not just with one page in mind. 

My thought on this was to add a new field for template to the Types (Page, etc) for Post Types that support `page-attributes` (templates). 

That would allow you to query something like: 

```
{
  pages {
    nodes {
       id
       title
       template {
           name
           ...on TruckTemplate {
               acfTruckFields {
                   addTruckChassis {
                     sourceUrl
                   }
               }
           }
       }
    } 
  }
}
```

(or something to that tune)

This part here: 

```
template {
           name
           ...on TruckTemplate {
               acfTruckFields {
                   addTruckChassis {
                     sourceUrl
                   }
               }
           }
       }
```

Is telling GraphQL: `if the page being queried happens to be assigned the `Truck.php` template, please give me these fields in response, otherwise, ignore me`

**Comment by jasonbahl** [comment]
I'll see what I can come up with in regards to template support.

**Comment by bftrepo** [comment]
Thanks @jasonbahl - that does make sense. Could you expand on your comment re

> My thought on this was to add a new field for template to the Types (Page, etc) for Post Types that support page-attributes (templates).

I'm adding a new acf field? Or it's just not possible to query this acf group?

**Comment by bftrepo** [comment]
What if I changed the location rule to "Page Parent" - would that be supported? That would still allow me to limit the acf fields to certain pages.

**Comment by jasonbahl** [comment]
Ah, ya. Let me clarify my words.

My thought is that the WPGraphQL for ACF plugin should detect field groups assigned to a specific page template, and those groups should be added to the GraphQL Schema as a new field that can be queried within the `template` field (which doesn't yet exist in the Schema). 

Does that make a bit more sense? 

It'll take a bit of work (on my end) still to be able to have ACF Fields assigned to a template as the location rule be available in the Schema.

**Comment by bftrepo** [comment]
Thanks for the clarification @jasonbahl. Would an easy fix, on my end, be to change the Location Rule for that acf field group to "Page Parent" instead of "Page Template"? Or is that still not something available in the Schema?

**Comment by bftrepo** [comment]
I created my own api feed to grab the custom fields I needed.
