### ISSUE TITLE
Feature Request: Relative Permalink URLs for Post Objects

### ISSUE THREAD

**Issue by lance-anderson** [wp-graphql/wp-graphql-acf#171]
Support for accessing the permalink of a [Post Object](https://github.com/wp-graphql/wp-graphql-acf#post-object-field) would be helpful.

Similar to what is exposed here but making it available for Post Objects.
https://github.com/wp-graphql/wp-graphql/issues/912

**Comment by jasonbahl** [comment]
@lance-anderson The Post Object field returns Post Objects, so any field you can query on a Post Object can be queried from this field. 

For example, taken from the docs: 

```
{
  post(id: "acf-example-test", idType: URI) {
    acfDocs {
      postObject {
        __typename
        ... on Post {
          id
          title
          date
          link
        }
        ... on Page {
          id
          title
          link
        }
      }
    }
  }
}
```
