### ISSUE TITLE
Relationship with posts object as draft return null value which causes internal server error

### ISSUE THREAD

**Issue by siddhantdante** [wp-graphql/wp-graphql-acf#173]
![Captuasdre](https://user-images.githubusercontent.com/44642083/94336501-540c6d80-0001-11eb-9572-652dba4f6469.PNG)
![Capasdasdture](https://user-images.githubusercontent.com/44642083/94336505-5bcc1200-0001-11eb-911c-5d371fa31dbf.PNG)

**Comment by jasonbahl** [comment]
I can confirm. Updating the field resolver to use DataLoader should resolve this. 

Marking this actionable.

**Comment by dChiamp** [comment]
ran in to this today too on Version 0.4.0

**Comment by wf-ssahakyan** [comment]
Hi @jasonbahl, is it clear when this issue will be resolved? Thanks in advance

**Comment by jasonbahl** [comment]
I'm working on v0.6.0 right now and this is resolved in that. 

It should be released this week or next week. 

I'm going to close this issue as it's part of the v0.6 milestone and is addressed by the upcoming release.

**Comment by jasonbahl** [comment]
This is resolved by #262. 

We can use the relationship field to set a relationship to a published post and a draft post, then query it as a public user and get no errors. 

Here, we can see the relationship being set on the post edit screen: 

![Screen Shot 2021-05-13 at 10 19 15 AM](https://user-images.githubusercontent.com/1260765/118154751-ace41700-b3d4-11eb-91c0-953714635111.png)

## Before

Querying for this field would return an error: 

![Screen Shot 2021-05-13 at 10 22 26 AM](https://user-images.githubusercontent.com/1260765/118155132-1f54f700-b3d5-11eb-88f5-cb80abf0d040.png)

## After:

Querying the relationship returns the public related nodes, but prevents the private (drafts, in this case) from being returned, and no errors are returned.

![Screen Shot 2021-05-13 at 10 26 42 AM](https://user-images.githubusercontent.com/1260765/118155678-b6ba4a00-b3d5-11eb-9a53-8c58b32d5fbb.png)

**NOTE:** The shape of the query has changed for relationship fields in this release. Relationship fields are now "[connections](https://www.wpgraphql.com/docs/connections/)" and the connected "nodes" are nested under the nodes field, as seen in the "after" screenshot.

**Comment by rodrigo-arias** [comment]
I'm glad this has been resolved. Do we have an ETA for release 0.6.0? I know it involves other updates

**Comment by arthay** [comment]
@jasonbahl hi. Do you have any news about Release v0.6.0? Thanks

**Comment by rodrigo-arias** [comment]
In case it is useful to someone, I was getting this error and tried to use [v0.6.0](https://github.com/wp-graphql/wp-graphql-acf/pull/262) but was getting other issues with repeated fragments. Finally I modified [this line](https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-config.php#L690) to return only published posts and that worked for me.
`if ( $post_object instanceof \WP_Post && 'publish' === $post_object->post_status ) {`
Of course, it is only a workaround and it works in my case that I don't need drafts in the frontend.
