### ISSUE TITLE
Error: EPERM: operation not permitted, lstat after WPGraphQL for Advanced Custom Fields activated

### ISSUE THREAD

**Issue by surreum** [wp-graphql/wp-graphql-acf#179]
In developing mode WPGraphQL for Advanced Custom Fields doesn't allow to load build. After disabling the plugin everything goes but without acf fields in a GraphQL explorer. Clearing cache doesn't help. Please advice.

**Full error:**

D:\xxx\xxx\xxx\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: EPERM: operation not permitted, lstat 'D:\xxx\xxx\xxx\.cache\caches\gatsby-source-wordpress-experimental\tmp-8fc5841f607fde1fb23f474462bfdac8.jpg'
    at Object.lstatSync (fs.js:1000:3)
    at Object.lstatSync (D:\xxx\xxx\xxx\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.rimrafSync D:\xxx\xxx\xxx\node_modules\gatsby-source-wordpress-experimental\node_modules\fs-extra\lib\remove\rimraf.js:228:18)
    at Request.<anonymous> (D:\xxx\xxx\xxx\node_modules\gatsby-source-wordpress-experimental\steps\source-nodes\create-nodes\create-remote-file-node\index.js:211:8)
    at Request.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: 'D:\xxx\xxx\xxx\\.cache\\caches\\gatsby-source-wordpress-experimental\\tmp-8fc5841f607fde1fb23f474462bfdac8.jpg'
}

**Comment by jasonbahl** [comment]
@surreum we'll need more information to debug this. 

Can you provide the following: 
- an export of your ACF fields as JSON
- gatsby repo or at least the gatsby-node.js, gatsby-config.js and package.json so we can try and replicate to some level

I think @TylerBarnes might have more context on this as well. 

This error: `Error: EPERM: operation not permitted, lstat 'D:\xxx\xxx\xxx.cache\caches\gatsby-source-wordpress-experimental\tmp-8fc5841f607fde1fb23f474462bfdac8.jpg'` makes me think there's some operation happening with image processing, so it's hard to say for sure if this is a WPGraphQL for ACF bug, a `gatsby-source-wordpress-experimental` bug, or a bit of each.

**Comment by surreum** [comment]
[files.zip](https://github.com/wp-graphql/wp-graphql-acf/files/5424329/files.zip)


> @surreum we'll need more information to debug this.
> 
> Can you provide the following:
> 
> * an export of your ACF fields as JSON
> * gatsby repo or at least the gatsby-node.js, gatsby-config.js and package.json so we can try and replicate to some level
> 
> I think @TylerBarnes might have more context on this as well.
> 
> This error: `Error: EPERM: operation not permitted, lstat 'D:\xxx\xxx\xxx.cache\caches\gatsby-source-wordpress-experimental\tmp-8fc5841f607fde1fb23f474462bfdac8.jpg'` makes me think there's some operation happening with image processing, so it's hard to say for sure if this is a WPGraphQL for ACF bug, a `gatsby-source-wordpress-experimental` bug, or a bit of each.

Thank you for your help!
Sorry, this repo is private, so I uploaded files in a zip archive.
Hope this help to solve my problem I like ACF much.

**Comment by TylerBarnes** [comment]
Hi @surreum , it looks like this is a node permissions issue. This might be helpful here https://stackoverflow.com/a/34614939

**Comment by surreum** [comment]
> Hi @surreum , it looks like this is a node permissions issue. This might be helpful here https://stackoverflow.com/a/34614939

Thanks a lot **@TylerBarnes** it solved the issue!

**Comment by TylerBarnes** [comment]
Great to hear! Have fun building things and let us know if you run into more problems :)
