### ISSUE TITLE
ACF Repeater fields date or date time are null

### ISSUE THREAD

**Issue by lexcode** [wp-graphql/wp-graphql-acf#18]
Any date format inside of repeater field are null

WP Graphql
![image](https://user-images.githubusercontent.com/349424/61707350-2dd6a800-ad42-11e9-9e19-a2ea95645faa.png)

WP REST API
![image](https://user-images.githubusercontent.com/349424/61707444-69717200-ad42-11e9-806c-2c85c900e35d.png)

**Comment by jasonbahl** [comment]
@lexcode thanks for reporting! I'll see what I can find out.

**Comment by jasonbahl** [comment]
@lexcode I just confirmed that #29 resolves this. I'm writing a few tests for this now to prevent regressions then will get a release out here shortly. 

Thanks for the PR @speedpro!

**Comment by lexcode** [comment]
Nice one, thank you @jasonbahl  and @speedpro

**Comment by jasonbahl** [comment]
This was closed by #29
