### ISSUE TITLE
Add unique id to repeater row

### ISSUE THREAD

**Issue by LudovicFauchet** [wp-graphql/wp-graphql-acf#183]
Hello,

Does it's possible to add an unique id to repeater row ?

Cheers

**Comment by LudovicFauchet** [comment]
I tried an other solution with creating a new field type who generate an unique id, but how to add this new field type to the schema ?
Cheers

**Comment by jasonbahl** [comment]
@LudovicFauchet can you provide more context on what you're trying to accomplish? Is there a way to do this outside of WPGraphQL with "normal" ACF and you're looking for parity with that?
