### ISSUE TITLE
Any way to add top-level databases/fields? Or how to filter

### ISSUE THREAD

**Issue by iamhazel** [wp-graphql/wp-graphql-acf#184]
Hello, thanks to everyone involved with creating and maintaining this plugin! I'm using WP as a headless CMS with a Gatsby front-end, and ACF is really helping me customize to my needs. I was wondering though:

1. I'd like to have several post types, e.g. production, activity, etc. but I have to query allWpPost to access them -- is there any way to create something like allWpProduction and put the production post types in there, so I can query them directly?
2. If not, can someone help me with filtering? I know how to query the ACFs, but the only way I can think to filter is to set the post category to "production" and filter based on category. Is there a better way?

**Comment by jasonbahl** [comment]
@iamhazel if you create a Custom Post Type called `Production` and add ACF Fields to that post type, then the content of the `Production` Post Type would show in Gatsby as `allWpProduction` and you could query the ACF fields from there. 

Perhaps this documentation might help: https://www.wpgraphql.com/docs/custom-post-types/
