### ISSUE TITLE
ACF_Link is being registered multiple times

### ISSUE THREAD

**Issue by SmartyP** [wp-graphql/wp-graphql-acf#189]
In trying to track down why my Gatsby previews are failing, and in the process I noticed a warning stating:

```
"type": "DUPLICATE_TYPE",
"message": "You cannot register duplicate Types to the Schema. The Type 'ACF_Link' already exists in the Schema. Make sure to give new Types a unique name.",
"type_name": "ACF_Link",
```

I found where this message is printed out in `wp-graphql-1.0/src/Registry/TypeRegistry.php` and put an `error_log` statement in place. My error log got flooded out with this same error about `ACF_Link` being registered multiple times. 

In looking at `wp-graphql-acf-release-v0.3.5/src/class-config.php` in the method `register_graphql_field`, for the case `link`, it appears to always register the `$field_type_name` of `ACF_Link`, whereas other cases in here seem to append other variances to the end of the field name before registering them. When putting `error_log()` statements in this case I find dozens/hundreds of times `ACF_Link` gets used for the $field_type_name (even though they each have differing `$type_name` values).

I'm not sure if this is related to my preview not working, but I wanted to file a ticket as it seems this warning is firing hundreds of times under the covers either way and potentially should be revisited..?

**Comment by ohuu** [comment]
I have exactly the same problem. Thought I'd just put a +1 on this issue

**Comment by nhankla-kl** [comment]
Same issue: 
Plugins Used: Wpgraphql 1.0.1
WPGraphql ACF 0.3.4

` "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'ACF_Link' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "ACF_Link",`

**Comment by lqze** [comment]
This is a known bug apparently.

**Comment by PieterT2000** [comment]
In my case it occurs because a ACF Group is being displayed on multiple pages using conditions. 
![image](https://user-images.githubusercontent.com/47913749/103224802-50e68d80-4920-11eb-9d45-ed985c6d00e3.png)

If I display the group only on one page, the error will disappear.

**Comment by elijameslennox** [comment]
Is there any movement on this? My site does re-use ACF field groups across multiple templates and custom post types and this bug makes this plugin useless. I otherwise love WPGraphQL and really would like to use it on this and other projects.

**Comment by danielnedelcu90** [comment]
First off, many thanks to the creator of this amazing plugin! 
I too am stuck with this issue and would really appreciate a fix 👍

**Comment by ChristopherNowlan** [comment]
Are we close to resolving this issue?

**Comment by ssoney200** [comment]
Same issue here

**Comment by AlexAlmeidaNS** [comment]
Same here

**Comment by merapi** [comment]
We also have the same problem, we cannot update the plugin because the site stops working.

@kidunot89  Does it look like a small or big fix for you?

**Comment by K-JAX** [comment]
Same issue here.

**Comment by nyvek28** [comment]
Same issue here :(

**Comment by guayom** [comment]
Same issue!

**Comment by jasonbahl** [comment]
Hello, 

Apologies for the delay in responding. 

The debug message should not be affecting execution. This bug has actually existed for a long time, but a change to WPGraphQL core leading up to the v1.0 release surfaced it in a debug message, where before it would silently happen, just without letting us know. 

I explain a bit more about this here: https://github.com/wp-graphql/wp-graphql-acf/issues/198#issuecomment-791733673

I'm going to close this issue as a duplicate of #198
