### ISSUE TITLE
Queries fail depending on client

### ISSUE THREAD

**Issue by derekchin** [wp-graphql/wp-graphql-acf#193]
I made the mistake(?) of updating WP(5.6) and plugins.

When I use graphiQL IDE in WP, everything works as expected. It also works when I use the chromeiQL plugin.

If I perform the same query using the electron graphiQL client, or curl, I get an error:

```
{
  "errors": [
    {
      "message": "Cannot query field \"property\" on type \"Property\". Did you mean \"propertyId\"?",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    },
```
If I query NON ACF fields, everything works, on every client.

Apologies if this is the wrong place to post.  Any guidance you can provide would be greatly appreciated.

**Comment by jasonbahl** [comment]
@derekchin can you share the version numbers of the plugins you're using and an export of your acf field group(s) that you're having trouble querying?

Also, can you share a screenshot of the query working in GraphiQL on an older version of WordPress and a screenshot of the failing query after going to WordPress 5.6?

**Comment by derekchin** [comment]
Thanks for the quick reply. After leaving this issue last night, I tried to downgrade my WP. I did this with a plugin, but I couldn't get it to work like before, so I went back to 5.6.  I'm attaching screenshots of how it is now. same query different client.    Also the acf field groups in json format and my list of plugins.
[Archive.zip](https://github.com/wp-graphql/wp-graphql-acf/files/5718798/Archive.zip)

**Comment by jasonbahl** [comment]
@derekchin I imported the JSON export your provided and added it to the `Post` post type. 

I then filled out some fields: 

![Screen Shot 2021-03-26 at 4 23 21 PM](https://user-images.githubusercontent.com/1260765/112698630-afec6d80-8e4f-11eb-9610-f50f8de4af6d.png)


And was able to query just fine: 

## GraphiQL in the WP Admin

![Screen Shot 2021-03-26 at 4 24 17 PM](https://user-images.githubusercontent.com/1260765/112698650-ba0e6c00-8e4f-11eb-9e25-8fbf7bd07500.png)

## ChromiQL Chrome Extension
![Screen Shot 2021-03-26 at 4 26 06 PM](https://user-images.githubusercontent.com/1260765/112698749-fb068080-8e4f-11eb-8f02-8bc10d47bb1b.png)

As far as I can tell, everything is behaving as expected. 

Perhaps double check that Chromiql is pointing at the proper endpoint?

----

I'm going to close this issue as I believe things are working as expected here. If you have additional information that can help reproduce and points toward being an issue with this plugin, please open a new issue.
