### ISSUE TITLE
Smart Button ACF exposed

### ISSUE THREAD

**Issue by carl0s** [wp-graphql/wp-graphql-acf#195]
We're playing with your plugin, which is totally fantastic, and we're also using [smart button](https://github.com/gillesgoetsch/acf-smart-button/) to render links that could be both internal or external, pretty handy.
Unfortunately these links are not exposed in GraphQL. Any plan to support them, or guidelines to extend the support?

Thanks!

**Comment by jasonbahl** [comment]
@carl0s a few people have asked for ACF extension support. I created a central issue to track this. We can't support the entire ecosystem of ACF extensions, but we can document how to integrate them with WPGraphQL. 

See this issue (#225) and keep an eye out for the resolution (documentation on how to do this)

**Comment by jasonbahl** [comment]
Closing in favor of the central #225
