### ISSUE TITLE
Got the Acf results in wordpress but not on front end

### ISSUE THREAD

**Issue by monaebeauty** [wp-graphql/wp-graphql-acf#196]
Hi there! I am wondering is there any user role restrictions to retrieve acf fields to the front end via graphql query? It appears that i am able to get the data from wordpress graphiQL as an admin but not for outsiders.

As i tried on wordpress graphiQL, it works.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/74286289/103335514-1c094080-4ab0-11eb-8f0f-9afe00efae3d.png">

And i tried it on altair graphql or my front end without admin role, it gets null.
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/74286289/103335571-422ee080-4ab0-11eb-8b9d-169691a5f263.png">

I am wondering if there's anything i could do to get it working?

**Comment by samhastings** [comment]
Hi @monaebeauty did you ever find a solution for this? Have run into the same problem this morning and not sure what to do!

**Comment by monaebeauty** [comment]
> Hi @monaebeauty did you ever find a solution for this? Have run into the same problem this morning and not sure what to do!

Hi @samhastings, unfortunately, I could not find a way to get it accessed publicly yet. I hope there's any help somewhere outside. Tried a lot of googling but got nothing from there.

**Comment by allyssonharry** [comment]
I also have the same problem. Using next js and apollo. When I add any custom field to the query in the frontend it returns: ```TypeError: Cannot read property 'user' of undefined``` or just ```undefined```.

**Comment by jasonbahl** [comment]
@monaebeauty can you provide more information about your ACF Field Group config, what field types you're using and the underlying data that's stored? 

A field group config from ACF would help, and screenshots of the data stored in the Post in the admin would help as well. 

The more info to allow me to replicate the same situation, the better.

**Comment by cromosom** [comment]
We ran into the same issue with a full page. For me it seems like it doesn't even relate to ACF. The page was created by an "editor". I can query it inside of WP as an admin but get null if I try to get it from outside.
![grafik](https://user-images.githubusercontent.com/3678823/113406107-38689200-93ab-11eb-86e9-e4edc0b51a55.png)
<img width="766" alt="grafik" src="https://user-images.githubusercontent.com/3678823/113406164-4dddbc00-93ab-11eb-9f28-2fd8c1b2a439.png">

**Comment by ltroya-as** [comment]
I have the same problem.

I created a `Subscription` ACF via code and I am not be able to query the field on Graphql Playground (it works on the internal Graphql IDE)

This is my config:

```
<?php

function create_custom_field_configuration_field($name, $label, $type)
{
    return array('key' => "field_{$name}", 'name' => $name, 'label' => $label, 'type' => $type);
}

# Check if advanced custom fields PRO is installed to execute 
# this function
if (function_exists('acf_add_local_field_group')) {
    # Subscription group field configuration
    acf_add_local_field_group(array(
        'key' => 'subscriptions',
        'title' => 'Subscriptions',
        'graphql_field_name' => 'subscriptions',
        'show_in_graphql' => 1,
        'fields' => array(
            create_custom_field_configuration_field('field_1', 'Field 1', 'date_picker'),
        ),
        'location' => array(
            # Show on users form to administrator's user role
            array(
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'edit',
                ),
                array(
                    'param' => 'current_user_role',
                    'operator' => '==',
                    'value' => 'administrator',
                ),
            ),
            # Show on users form to user manager's user role
            array(
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'edit',
                ),
                array(
                    'param' => 'current_user_role',
                    'operator' => '==',
                    'value' => 'user_manager',
                ),
            ),
        ),
    ));
}


```

Wordpress 5.7
wp-graphql-acf: 0.4.1

**Comment by vassbence** [comment]
Same here. A simple multi select user field returns the values as expected if accessed from the internal IDE but is null in a http response

**Comment by Ebeldev** [comment]
I do have the same problem. 
WordPress 5.8.2
WPGraphQL 1.6.10
WPGraphQL ACF 0.5.3
WPGraphQL Gutenberg 0.3.11
ACF PRO  5.11.4

In a option page, I do have 1 text field (textingtextfield) and 1 User field (testinguserfield). 

**Only the User field returns null outside of WordPress.** 
 
Here is the view of my ACF fields : 
<img width="1349" alt="Capture d’écran, le 2021-12-14 à 22 50 22" src="https://user-images.githubusercontent.com/8010184/146120130-0371f366-f74c-42be-b366-a3cc26c4702d.png">
<img width="1336" alt="Capture d’écran, le 2021-12-14 à 22 50 07" src="https://user-images.githubusercontent.com/8010184/146120132-14a727e4-6c51-474a-a542-dced8c10d48c.png">


Here is the GraphiQL in WordPress:
<img width="1001" alt="Capture d’écran, le 2021-12-14 à 22 50 53" src="https://user-images.githubusercontent.com/8010184/146120164-25f06946-4923-4aea-a944-97564250a072.png">


Here is the GraphiQL outside of WordPress:
<img width="975" alt="Capture d’écran, le 2021-12-14 à 22 51 02" src="https://user-images.githubusercontent.com/8010184/146120182-6b958c68-ec1f-4639-849f-535d941f76ac.png">

Anyone has a idea why ?

**Comment by jasonbahl** [comment]
This plugin is being re-architected over here: https://github.com/wp-graphql/wpgraphql-acf

In regards to the original issue, I attempted to reproduce using the new version (WPGraphQL for ACF v2.0.0-beta.5.1.0)

Using the following exported ACF Field Group I was able to assign an ACF Field Group with an Image Field to the "Comment" type. 

Then I was able to query the comments and the uploaded image and see the expected results.

[acf-export-2023-11-07 (1).json.zip](https://github.com/wp-graphql/wp-graphql-acf/files/13289516/acf-export-2023-11-07.1.json.zip)

----

I'm considering this issue resolved in the new version, which is what we'll be supporting going forward, and we encourage you to update when you can. 

----

@Ebeldev I believe you're experiencing something related to Model Layer rules about users. Users are not considered "public" in WordPress unless they've published content of a public post type. 

So if you're using a "User" field, the "User" node might not be publicly visible if the user isn't a publicly visible user. 

Here's some more info on this topic: 
- https://www.wpgraphql.com/2020/12/11/allowing-wpgraphql-to-show-unpublished-authors-in-user-queries
- https://www.wpgraphql.com/recipes/make-all-users-public
