### ISSUE TITLE
Example download gives a 404

### ISSUE THREAD

**Issue by ghost** [wp-graphql/wp-graphql-acf#199]
Hi,

Could you fix the example? field-group-export.zip 
Currently it gives me a 404 :( 

Thanks in advance.

**Comment by jasonbahl** [comment]
**Note to self:** This is referring to the link to the zip file in the README.md

**Comment by markkelnar** [comment]
The Pr added a [json file](https://github.com/wp-graphql/wp-graphql-acf/blob/develop/docs/field-group-examples-export.json) that can be imported to acf, instead of using the zip file. It's merged into the develop branch.

**Comment by jasonbahl** [comment]
closed by #227
