### ISSUE TITLE
Flexible Content query's not working

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-acf#2]
Create a field group with the Wp-GQL key of `acfSocialLinks` (also would be great if this could be `acf-social-links`). Then create a `Flexible Content` layout. See my screenshot. You'll see that you can't actually get the query to work.

![Screen Shot 2019-04-25 at 4 08 14 PM](https://user-images.githubusercontent.com/475015/56774025-b2328280-6775-11e9-97e8-f70957afe323.png)
![Screen Shot 2019-04-25 at 4 17 38 PM](https://user-images.githubusercontent.com/475015/56774026-b2cb1900-6775-11e9-9c1a-043ac260318c.png)

**Comment by jasonbahl** [comment]
Got this fixed. Release coming this evening 😀

**Comment by jasonbahl** [comment]
There was a bug with nested fields. I’ll provide docs on usage as well

**Comment by jasonbahl** [comment]
@drewbaker release v0.1.2 fixed this. 

Here's some info on usage. 

For demo sake, I've created a Field Group, and have included the export as a .zip that you can import to your ACF to test, if needed.

[acf-export-2019-04-27.json.zip](https://github.com/wp-graphql/wp-graphql-acf/files/3123917/acf-export-2019-04-27.json.zip)

The Field Group is configured to "Show in GraphQL" and has a "GraphQL Field Name" set to `flexTest`.

The Field Group contains one field named "Flex Field" (creative, I know 😆). The Flex field contains 2 Layouts:

- **Layout 1:** contains 1 repeater named "Repeater" (again, I'm really good at naming things). That repeater field has 1 text field, named "title".
- **Layout 2:**  contains just a text field named "text field"

You can see this Flex Field in action on a post:

![Screen Shot 2019-04-27 at 7 48 31 AM](https://user-images.githubusercontent.com/1260765/56850503-f8482d00-68c0-11e9-89f8-eaae4e6b4f53.png)

And below you can see an example of querying the post with the flex field data:

![Screen Shot 2019-04-27 at 7 50 00 AM](https://user-images.githubusercontent.com/1260765/56850522-157cfb80-68c1-11e9-9b0e-99c1e48b68b5.png)

Here's the raw query I used: 

```
{
  postBy(postId: 1800) {
    title
    content
    flexTest {
      flexField {
        __typename
        ... on Post_Flextest_FlexField_LayoutOne {
          repeater {
            title
          }
        }
        ... on Post_Flextest_FlexField_LayoutTwo {
          textField
        }
      }
    }
  }
}
```

**Comment by drewbaker** [comment]
OK great, I've never seen the `... on` syntax before. What does that do?

**Comment by jasonbahl** [comment]
@drewbaker the `...on` syntax is used for querying Unions. 

A union is a Type of field that can return one of many Types, but it's not known which Type it will be until execution. 

In our case, a Flex Field can return one of many Flex Field layouts. It's not known which layout was used in the Flex Field until execution time, so you can write a query asking for the specific field you plan to support for each layout you plan to support. 

Then when the query is executed, you get just the fields you specified for just the Layouts you asked for. 

You can read more about unions from the official GraphQL site here: https://graphql.org/learn/schema/#union-types

**Comment by jasonbahl** [comment]
@drewbaker I'm going to close this as I believe it's resolved. If you're still having issues, let me know.
