### ISSUE TITLE
Install free version asks for license key

### ISSUE THREAD

**Issue by mtthsnc** [wp-graphql/wp-graphql-acf#20]
Is the conversion of the plugin from being premium to free an ongoing development, or is there any nescessary things we have to do in order to avoid the license key input on installation?

**Comment by jasonbahl** [comment]
@omattman ya, I should have removed the license check **before** the announcement went out. I have a PR coming any second that removes it. 

Keep an eye out. 😄

**Comment by jasonbahl** [comment]
See #19

**Comment by mtthsnc** [comment]
@jasonbahl Oh my bad, didn't notice #19

I'll close this for now :-)
