### ISSUE TITLE
Repeater sub-fields not included in previews

### ISSUE THREAD

**Issue by benknight** [wp-graphql/wp-graphql-acf#200]
It looks like when preview support was added in https://github.com/wp-graphql/wp-graphql-acf/pull/153 repeater field subfields weren't included.

The root cause of the issue is here: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-config.php#L57

When the filter is run for a repeater field's subfield, the value of `$meta_key` will look something like `items_0_title` however only `items` (the repeater field itself) is inside of `$this->registered_field_names`. Therefore the filter returns true `graphql_resolve_revision_meta_from_parent` for repeater sub-fields which are then read from the parent rather than the preview revision.

**Comment by jasonbahl** [comment]
Closed by #201
