### ISSUE TITLE
Preview doesn't work for Advanded Custom Fields

### ISSUE THREAD

**Issue by tobiasandersen** [wp-graphql/wp-graphql-acf#202]
I'm not sure if this is a bug report or a feature request — but I'm trying to get preview data for a page with ACF content, but I'm only able to retrieve non-ACF data. Given this query:

```js
page(id: $id, idType: $idType) {
  preview {
    node {
      pageTemplate {
        template {
          ... on Page_Pagetemplate_Template_Hero {
            headline
          }
        }
      }
      title
      isPreview
      modified
    }
  }
}
```

The three bottom fields (`title`, `isPreview` and `modified`) all give me the expected preview data — but any data inside `pageTemplate` (set up in ACF) is stale. So in this case the `headline` property will never show the preview data. 

For reference, I'm using Wordpress 5.6 and the following plugins:
- WPGraphQL for Advanced Custom Fields (0.4.0)
- WP GraphQL (1.1.1)
- Advanced Custom Fields PRO (5.9.3)

**Comment by jasonbahl** [comment]
@tobiasandersen are you using Gutenberg or Classic Editor?

**Comment by tobiasandersen** [comment]
> @tobiasandersen are you using Gutenberg or Classic Editor?

Classic!

**Comment by tobiasandersen** [comment]
I'm not familiar with `asPreview`, but sounds like this could be the same issue as described in https://github.com/wp-graphql/wp-graphql-acf/issues/190?

**Comment by tobiasandersen** [comment]
The fix posted in https://github.com/wp-graphql/wp-graphql-acf/issues/159 by @peteluffman seems to solve the issues I'm having as well.

**Comment by jasonbahl** [comment]
@tobiasandersen I opened a PR which I believe might address this. Can you check https://github.com/wp-graphql/wp-graphql-acf/pull/205 and let me know?

**Comment by tobiasandersen** [comment]
Thanks @jasonbahl! Short answer: it didn't fix my issue, but also commented in the PR.

**Comment by TylerBarnes** [comment]
@tobiasandersen I think the problem here is the use of the preview field instead of using `asPreview`. Try this:

```
page(id: $id, idType: $idType, asPreview: true) {
      pageTemplate {
        template {
          ... on Page_Pagetemplate_Template_Hero {
            headline
          }
        }
      }
      title
      isPreview
      modified
}
```

**Comment by TylerBarnes** [comment]
@jasonbahl maybe the preview field should be deprecated?

**Comment by TylerBarnes** [comment]
Oh, nvm my bad, I see it's working for me on both:

<img width="1086" alt="Screen Shot 2021-01-15 at 4 48 20 PM" src="https://user-images.githubusercontent.com/14190743/104791968-8c22f200-5751-11eb-9b2a-c64aba12f261.png">
<img width="1097" alt="Screen Shot 2021-01-15 at 4 48 10 PM" src="https://user-images.githubusercontent.com/14190743/104791975-90e7a600-5751-11eb-9e61-b8c2ff755831.png">
