### ISSUE TITLE
Options values always empty

### ISSUE THREAD

**Issue by idflood** [wp-graphql/wp-graphql-acf#203]
I've created an ACF option page, registered it with `'show_in_graphql' => true` and it appear in the graphiql schema.

But when I try to query this field it always return `null`.

When trying to debug the issue I've found [that here](https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-config.php#L1649-L1653) the `acf_get_field_groups` function return the field definition but not the values.

If I try to add a `print_r(get_fields('options'))` I see that the values are present but not loaded with this function.

Another thing (maybe related), the query needed looks like it and is not really similar to the different documentations about this feature:

```
generalSettings {
    siteSettings {
      test
    }
  }
```

Wordpress 5.6
Advanced Custom Fields PRO 5.9.3
WP GraphQL 1.1.2
WPGraphQL for Advanced Custom Fields 0.3.5

**Comment by jasonbahl** [comment]
@idflood can you provide the code you used to register the ACF options page as well as the Field Group config? 

the `generalSettings` is a core field for querying settings under WordPress Settings > General page. 

ACF Options have their own root entry in the Graph under their own name.

**Comment by jasonbahl** [comment]
I'm not able to reproduce this, and with v0.5.0 (#250( there are [tests](https://github.com/wp-graphql/wp-graphql-acf/pull/250/files#diff-6d03e0950b6efd5d3ce4d3014252facca56305c1cbca8bf9f3a0b38d4bdba17fR591-R672) for Options Pages. 

If there are steps to consistently reproduce this, please open another issue.
