### ISSUE TITLE
Revisions not updating some data in acf flexible content

### ISSUE THREAD

**Issue by CalebBarnes** [wp-graphql/wp-graphql-acf#204]
To reproduce this you will need to import my wplocal export 
(I'll DM Jason this over slack, if anyone else wants to try you can ask for it)

This WP install is using a custom plugin I built to preview WPGraphQL revisions in Gatsby. https://github.com/CalebBarnes/WPGraphQL-Gatsby-Preview

For this plugin you need to add to your wp-config.php the link to the Gatsby site.
`define('GATSBY_PREVIEW_FRONTEND_URL', 'https://my-gatsby-site.netlify.app/');`

You will also need to set up the gatsby site using this repo: https://github.com/CalebAtBare/wp-gatsby-demo-with-preview
and then set the env `GATSBY_WPGRAPHQL_URL` to your WPGraphQL endpoint.
Example: `GATSBY_WPGRAPHQL_URL=https://wpgatsbydemo1.wpengine.com/graphql`

WPGraphQL version: 0.10.3 (Also tested revisions with 0.12.1 but 0.10.3 is the latest supported by the source plugin)
Platform: WPEngine (with revisions enabled)
Other Plugins: 
[WPGraphQL-Gatsby-Preview](https://github.com/CalebBarnes/WPGraphQL-Gatsby-Preview) 0.1
WP Gatsby 0.4.16
WPGraphQL for Advanced Custom Fields 0.3.5
WPGraphQL JWT Authentication 0.4.1

**Expected behavior:** When I click preview and then the gatsby site queries the newest revision it should have all of the updated data for that revision.

**Actual behavior:** The first item in the flexible content array is not updated to use the revision data, but everything else in the array is updated correctly.

**Comment by jasonbahl** [comment]
@CalebBarnes long time coming, but I believe this resolves the issue. Can you confirm? https://github.com/wp-graphql/wp-graphql-acf/pull/205

**Comment by jasonbahl** [comment]
I believe this is resolved per #205. Closing, but can re-open if that's not the case.
