### ISSUE TITLE
Custom fields don't show in schema when using 'Page Type' in location.

### ISSUE THREAD

**Issue by holliepearson** [wp-graphql/wp-graphql-acf#210]
When defining the location for the advanced custom field, choosing the criteria as being a 'page type' (i.e Page type is equal to Front Page), the field will no longer show in the schema.

Choosing a different option such as 'page is equal to page name' then causes the field to appear in the schema.

Possibly related to #206

**Comment by jasonbahl** [comment]
👋🏻  Hello! 

v0.5.0 (#250) resolves this. 

The ACF Location Rules are mapped much more accurately to the WPGraphQL Schema, but there are still some rules that are difficult to translate, so there's also a UI that allows you to explicitly set which GraphQL Types the ACF Field Group should show on. 

This video walks through the new feature: https://www.youtube.com/watch?v=VvrZGrcwv0Y

Below is also a screenshot of this rule in action, showing that this rule will show the Field Group on the `Page` Type in the Schema: 

![Screen Shot 2021-04-20 at 3 50 59 PM](https://user-images.githubusercontent.com/1260765/115468417-4cf0bb00-a1f0-11eb-9f70-526ba587ad71.png)
