### ISSUE TITLE
ACF image field returning null

### ISSUE THREAD

**Issue by jenishshrestha** [wp-graphql/wp-graphql-acf#211]
Acf image field is returning null in GraphiQl provided by WP Gatsby (i.e http://localhost:8000/___graphql) where as GraphiQl in wp backend provided by WP GraphQL is returning correct value.

I am using WP GraphQL(1.1.3), WP Gatsby(0.9.2), WPGraphQL for Advanced Custom Fields (0.4.1), Gatsby Source Wordpress@v4 BETA

**Comment by arnespremberg** [comment]
Hi @jenishshrestha I'm having the same issue - how did you solve it? Thanks

**Comment by blydewright** [comment]
@jenishshrestha @arnespremberg did either of you solve this issue? I'm getting the same problem now and pulling my hair out trying to find the issue 😒
