### ISSUE TITLE
Fetch a Range field with decimals - Fail

### ISSUE THREAD

**Issue by valikwork** [wp-graphql/wp-graphql-acf#215]
Hi!
I have a custom field type _"Range"_, and when i set its value to a whole number (1,2,3 etc), fetching it works fine, but when i use value with decimals (i.e. 1,5) - the query brakes, gives 'Internal server error' with the 'location' on Schema being mine rangeField. I belive input returns float number, not int. Is this what breaks the query, and is there any workaround for this?

Thanks in advance!

All plugin versions are up-to-date

**Comment by jasonbahl** [comment]
Hello @valikwork! 

Thanks for reporting this issue and including details to reproduce. 

I believe this has been resolved, but not yet released. See: #172 

The next release should include this fix.
