### ISSUE TITLE
mutation createPost don't support acf input field?

### ISSUE THREAD

**Issue by shipcake** [wp-graphql/wp-graphql-acf#216]
Hi. I use Wpgraphql and i have problem. how to defind custom acf type in  input field?

**Comment by Yuribtr** [comment]
I have a same question too. Can't find any info. 
@jasonbahl  seems that creation and update is not supported by this plugin, isn't it?

**Comment by saleebm** [comment]
Hey I have an example repository here [wp-acf-mutations](https://github.com/saleebm/wp-acf-mutations). Basically you need to run the filters to add the input fields to the schema based on your acf fields.

**Comment by Yuribtr** [comment]
Hi @saleebm, many thanks for pointing me out. If ACF and CPT UI is present the problem solves in few lines of code in functions.php. It is amazing!


```
use WPGraphQL\AppContext;
use WPGraphQL\Model\User;

add_action( 'graphql_input_fields', function ( $fields, $type_name, $config ) {	
	if ( $type_name === 'UpdateArticlesInput') {
		$fields = array_merge( $fields, [		
			'name' => [ 'type' => 'String' ],
		] );
	}

	return $fields;
}, 20, 3 );

add_action( 'graphql_post_object_mutation_update_additional_data', function ( $post_id, $input, $mutation_name, $context, $info ) {
	if ( isset( $input['name'] ) ) {
		update_field('field_6036d0504e27d', $input['name'], $post_id);
	}
}, 10, 5 ); 
```

**Comment by jasonbahl** [comment]
Hello! Mutations are not currently on the near-term roadmap for this plugin. We do hope to add support in the future, but I don't know when. I've labeled this "Future Feature" and moved it to the "ACF Mutations" milestone for future consideration.

**Comment by nagman** [comment]
> Hi @saleebm, many thanks for pointing me out. If ACF and CPT UI is present the problem solves in few lines of code in functions.php. It is amazing!
> 
> ```
> use WPGraphQL\AppContext;
> use WPGraphQL\Model\User;
> 
> add_action( 'graphql_input_fields', function ( $fields, $type_name, $config ) {	
> 	if ( $type_name === 'UpdateArticlesInput') {
> 		$fields = array_merge( $fields, [		
> 			'name' => [ 'type' => 'String' ],
> 		] );
> 	}
> 
> 	return $fields;
> }, 20, 3 );
> 
> add_action( 'graphql_post_object_mutation_update_additional_data', function ( $post_id, $input, $mutation_name, $context, $info ) {
> 	if ( isset( $input['name'] ) ) {
> 		update_field('field_6036d0504e27d', $input['name'], $post_id);
> 	}
> }, 10, 5 ); 
> ```

Where do you find the `field_6036d0504e27d` in the database?

**Comment by nagman** [comment]
Ok I found it => in the `wp_postmeta` table, search for `_your_acf_field_slug` (add the `_` at the beginning) in the `meta_key` column, and take the corresponding `meta_value`.

Thanks a lot @Yuribtr! You solved my dead end!

**Comment by jasonbahl** [comment]
👋🏻 We are re-building WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. 

I've created a new issue to track mutation support (and explain some current blockers). see: https://github.com/wp-graphql/wpgraphql-acf/issues/109

I'm going to close this in favor of tracking it in the new repo.
