### ISSUE TITLE
Query with meta in where parameter

### ISSUE THREAD

**Issue by shenburak** [wp-graphql/wp-graphql-acf#219]
```graphql
query MyQuery {
  schoolUsers(where: { userMeta: { school: { id: 999 } } }) {
    edges {
      node {
        userMeta {
          fieldGroupName
          school {
            ... on School {
              id
              title
              slug
            }
          }
        }
      }
    }
  }
}
```
What should I do so that I can run a query like the one above, I couldn't find any information about it. I want to search for input with meta information (for example, in this example I want to list the school IDs of 999 in userMeta with their schools, but that's not possible)

**Comment by ax-hack** [comment]
Maybe this help you https://www.wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument/

**Comment by shenburak** [comment]
I found a solution by creating taxonomies specific to the information to be searched.
Thanks.
