### ISSUE TITLE
Syntax Error: Expected Name, found ":"

### ISSUE THREAD

**Issue by stubbies** [wp-graphql/wp-graphql-acf#221]
When trying to generate graphql types with **graphql-codegen** I get this error:

````
Syntax Error: Expected Name, found ":"
````

This only happens when **wp-graphql-acf** extension plugin is activated.

**Comment by jasonbahl** [comment]
Hello @stubbies can you provide more information on this? 

What are the steps to reproduce? What version of WPGraphQL for ACF? What version of `graphql-codegen`? Did you have any ACF field groups created in your WordPress install?

The more information you can provide to reproduce, the more we can help. 

Thanks!

**Comment by jasonbahl** [comment]
Closing due to lack of information and unable to reproduce.
