### ISSUE TITLE
Document how to add support for ACF Extensions

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#225]
WPGraphQL for ACF supports mapping core ACF fields to the WPGraphQL Schema.

ACF has a robust extension ecosystem with custom fields. This plugin can't support the entire ACF extension ecosystem out of the box, but instead, we can provide documentation so ACF plugin authors can provide WPGraphQL support themselves, or developers working on specific implementations can add support for their projects.

## Action:

There are hooks and filters in the plugin that allow ACF extensions to be hooked in and supported. We need to add documentation to the README (or where applicable) to show how this can be done.

**Comment by manspaniel** [comment]
Hi! Any hints as to which hooks/filters are relevant to this?

**Comment by jasonbahl** [comment]
Closing this as it's being tracked in the new repo over here now: https://github.com/wp-graphql/wpgraphql-acf/issues/48
