### ISSUE TITLE
Request: Generic 'Content' type

### ISSUE THREAD

**Issue by YCMitch** [wp-graphql/wp-graphql-acf#228]
So, we're currently stuck at `WPGraphQL` 1.0, as we've relied on (what we now know is) an extremely helpful bug which has now been removed. 

Now, say you've written a huge `fragment` (some of ours are 500+ lines) of ACF fields which is using a specific post type (e.g `Page`). 

If, in WordPress, you apply the same fields to another post type - what do you do? You can't copy + paste the fragment once for each post type as that's _gross_. We discovered in `WPGraphQL` you can just query any post type as `page(id: X, idType: DATABASE_ID)`, and results will be returned accordingly (i.e, pretend everything is a page). 

Absolute life-saver, as `Pages`, `Posts`, `Products`, `People` etc etc can all use the same `flexibleContent` fields as each other. Admins can make pages however they like, for any post type. It was real distressing when this was taken away, as we don't have a viable alternative. In NextJS (unlike Gatsby) we can dynamically create GraphQL tags, so we can do something hideous like this (`slug` is just the post type, e.g `Page`, `Product`):

<img width="460" alt="Screen Shot 2021-03-11 at 5 23 47 pm" src="https://user-images.githubusercontent.com/34614502/110744976-adeeb000-828e-11eb-9597-956cd6f6ed79.png">

But in Gatsby we can't do that, so we're either using v1.0, or nothing at all. 

I sincerely vote we bring this back in some capacity. If everyone's uncomfortable letting us query anything as a `Page`, perhaps add a `Content` post type which can be any post object, queried by ID. It's not dissimilar from how WP itself works (as everything is _really_ just a `post`). 

Does that make sense? It would just, be so much more flexible - and I'm aware the functionality already exists (in 1.0 and below), so why not?

**Comment by jasonbahl** [comment]
👋🏻 it's been a LOOONG time coming, but we're getting close to a stable release of the new WPGraphQL for ACF (https://github.com/wp-graphql/wpgraphql-acf/releases) which is a complete re-architecture and supports re-usable fragments across different types that have the same ACF Field Groups. 

You can read more about this here: https://github.com/wp-graphql/wp-graphql-acf/issues/53#issuecomment-1789110210

I'm going to close this issue as the new plugin has MUCH BETTER support for sharing fragments across types. 

I'd encourage you to make the switch when you can as it's the version of the plugin we'll be supporting going forward and this repo will be archived in the not-too-distant future.
