### ISSUE TITLE
Support for multiple values on User Field Type

### ISSUE THREAD

**Issue by robanquieri** [wp-graphql/wp-graphql-acf#23]
It does not work when the multiple values feature is enabled.

**Comment by jasonbahl** [comment]
@robanquieri can you provide a detailed example so I can replicate and confirm? Possibly provide an example of a Field Group (json export would work) and the field(s) that don't seem to be working properly. 

Thanks!

**Comment by robanquieri** [comment]
Hi Jason,

The ACF custom fields settings:

![Screenshot_2019-08-01 Edit Field Group ‹ TPUSA — WordPress](https://user-images.githubusercontent.com/4391611/62339158-63e9f980-b4b1-11e9-8088-c5fc8578b0d5.png)

Post with multiple users selected:

<img width="1243" alt="Screen Shot 2019-08-01 at 22 54 02" src="https://user-images.githubusercontent.com/4391611/62339188-80863180-b4b1-11e9-9dba-ded1e68018fe.png">

GraphiQL response:

<img width="1140" alt="Screen Shot 2019-08-01 at 23 03 12" src="https://user-images.githubusercontent.com/4391611/62339216-9a277900-b4b1-11e9-8d88-e875fbaa7995.png">

Json file:

[https://drive.google.com/file/d/1eG0TScPUG59wJuubsQyZjkOBix_sMyxH/view?usp=sharing](url)

**Comment by jasonbahl** [comment]
@robanquieri thanks for the added info! I’ll get a fix here shortly
