### ISSUE TITLE
Archive URLs not shown when using with Page Links

### ISSUE THREAD

**Issue by janmei** [wp-graphql/wp-graphql-acf#230]
Hey, 

i have a problem with archive URLs to which i want to link to. 
I created a field with ACF which lists all the archive URLs. 

In GraphiQL i also got to choose the correct Custom Post Type, but the result is always `null`: 

![Bildschirmfoto 2021-03-17 um 13 52 54](https://user-images.githubusercontent.com/2657641/111470386-170b7300-8728-11eb-8c66-778dd4c76df1.png)

 ![Bildschirmfoto 2021-03-17 um 13 54 56](https://user-images.githubusercontent.com/2657641/111470738-79fd0a00-8728-11eb-8059-8d4ec82dc3c2.png)

![Bildschirmfoto 2021-03-17 um 13 55 01](https://user-images.githubusercontent.com/2657641/111470655-605bc280-8728-11eb-9546-ca60379a7230.png)

All the Post Type have the `has_archive` flag set to `true`

Do I miss something or is it just not supported?

**Comment by jasonbahl** [comment]
I'm not sure I understand. 

What is the ACF Field type, what does the data look like in the WP-Admin that you expect to be showing in WPGraphQL? 

Can you share more information about the steps you took to create a field group / fields in ACF, then how you stored the data in WordPress, and what you are expecting from the query above?
