### ISSUE TITLE
Certain location rules cause the field group to not show up in GraphQL

### ISSUE THREAD

**Issue by michaelpanik** [wp-graphql/wp-graphql-acf#233]
I have a field group that when I set the location rule to "Post Type is Post" it shows in GraphQL without issue.

If I set the location rule to "Post Format is Video" it does not show.

Is this by design? Is there something else I need to do in order to make this field show when setting post format rules?

**Comment by arnespremberg** [comment]
This seems to be the expected behaviour - most page rules are not supported yet. See this tag for more related issues:
https://github.com/wp-graphql/wp-graphql-acf/issues?q=is%3Aissue+is%3Aopen+label%3A%22Location+Rules%22

**Comment by michaelpanik** [comment]
@arnespremberg thanks! I saw @stupearce's fix in another thread, I may give that a go. Thanks for pointing me in the right direction!

**Comment by arnespremberg** [comment]
I managed to get your described behaviour to work today by using the code from this PR:
https://github.com/rsm0128/wp-graphql-acf/commit/6cb6193363dcce54c3fb830dfc10e69297b27edd

**Comment by michaelpanik** [comment]
> I managed to get your described behaviour to work today by using the code from this PR:
> [rsm0128@6cb6193](https://github.com/rsm0128/wp-graphql-acf/commit/6cb6193363dcce54c3fb830dfc10e69297b27edd)

This is awesome. Maybe they can verify and roll that in for the next version?

**Comment by arnespremberg** [comment]
I think they're currently reviewing :) the appropriate issue is this one: https://github.com/wp-graphql/wp-graphql-acf/issues/135

**Comment by jasonbahl** [comment]
👋🏻  Hey! 

Location Rules have been completely revamped in v0.5.0 (#250)! 

There's a video walking through things here: https://www.youtube.com/watch?v=VvrZGrcwv0Y

For this specific issue: 

> If I set the location rule to "Post Format is Video" it does not show.

This has been addressed. The location rules automatically map this better than before. You can see below that if I set this rule, the Field Group will show in the GraphQL Schema on the `Post` Type. And you have the option to manually associate the Field Group with other Types in the Schema if the auto-mapping logic doesn't quite do what you need it to.

![Screen Shot 2021-04-20 at 4 16 24 PM](https://user-images.githubusercontent.com/1260765/115470570-c4741980-a1f3-11eb-9fcd-ed1f38a20d29.png)
