### ISSUE TITLE
How Can I use ACF Font Awesome field in WP GraphQl

### ISSUE THREAD

**Issue by mshshuvooo** [wp-graphql/wp-graphql-acf#234]
Hi. I have used **Advanced Custom Fields: Font Awesome Field** plugin (https://wordpress.org/plugins/advanced-custom-fields-font-awesome/) to getting the icon filed. But there is no option for icon filed In the WP GraphQl Explorer section.  How can get an icon filed in my WP GraphQl query? Please help me.

**Comment by icecyber** [comment]
i also have the same problem

**Comment by jasonbahl** [comment]
👋🏻 We're working on a new version of WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. 

The new version has an API for adding support for third party ACF Field Types. 

In fact, the plugin comes with support for [ACF Extended](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/AcfExtended.php) Field Types and you can use them as a model for adding support for additional ACF Field Types. 

For example: 

- [ACFE Advanced Link](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeAdvancedLink.php)
- [ACFE Countries](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeCountries.php)

Here's also a GIST showing how @CesarBenavides777 mapped the ACF Table field type to the GraphQL Schema: https://gist.github.com/CesarBenavides777/79b158db8355ddbc349fbf9b3272ae47

While we won't be supporting all ACF Field Type extensions out of the box, but we will be supporting the APIs for developers to add their own custom ACF Field Types more easily. 

We'd recommend checking out the new version of WPGraphQL for ACF as it's what we'll be supporting going forward. It wil have a stable release on WordPress.org in the near future and this version will be archived.
