### ISSUE TITLE
nofollow support

### ISSUE THREAD

**Issue by simplenotezy** [wp-graphql/wp-graphql-acf#247]
Currently the GraphQL exposes:
- target
- title
- url

It would be nice if it would also expose `rel="nofollow"` as well (and perhaps `rel="sponsored"`).

![image](https://user-images.githubusercontent.com/3786627/114546780-db4bc680-9c5d-11eb-9fd2-5cecf99c0b75.png)

**Comment by jasonbahl** [comment]
@simplenotezy What field type are you referring to?

**Comment by simplenotezy** [comment]
@jasonbahl The ACF_Link type. Inside WorPress you can choose to tick of `Add rel="nofollow"`. But I cannot get this boolean out using GraphQL currently.

![image](https://user-images.githubusercontent.com/3786627/114884453-12f57280-9e06-11eb-8659-c1bc0d6318e3.png)

**Comment by jasonbahl** [comment]
@simplenotezy when using ACF Pro v5.9.4 I don't see the `nofollow` and `sponsor` links in the Link field. 

![Screen Shot 2021-05-13 at 12 19 08 PM](https://user-images.githubusercontent.com/1260765/118168748-6c40c980-b3e5-11eb-93a2-4abe16e3c142.png)

Are you using any ACF Extensions that might be adding this?

**Comment by jasonbahl** [comment]
@simplenotezy in my quick research, I couldn't find code in ACF or ACF Pro that exposes nofollow or sponsor on the link field.

It sounds like these properties of the Link field might be added via custom code or an extension to ACF? 

In the upcoming v0.6.0 the link field is exposed as the `AcfLink` type in the Schema, and you can add fields to the GraphQL Schema for that Type like so: 

```php
add_action( 'graphql_register_types', function() {

	register_graphql_fields( 'AcfLink', [
		'noFollow' => [
			'type' => 'Boolean',
			'description' => __( 'Whether the link has the noFollow attribute', 'your-textdomain' ),
			'resolve' => function( $link_data_from_acf ) {
				return isset( $link_data_from_acf['no_follow'] ) ? (bool) $link_data_from_acf['no_follow'] : false;
			}
		],
		'sponsor' => [
			'type' => 'Boolean',
			'description' => __( 'Whether the link has the sponsor attribute', 'your-textdomain' ),
			'resolve' => function( $link_data_from_acf ) {
				return isset( $link_data_from_acf['sponsor'] ) ? (bool) $link_data_from_acf['sponsor'] : false;
			}
		]
	] );

});
```

Then, with the fields added to the `AcfLink` type in the GraphQL Schema, you can query like so: 

![Screen Shot 2021-05-13 at 12 38 33 PM](https://user-images.githubusercontent.com/1260765/118171078-23d6db00-b3e8-11eb-9e81-e864aa261e0d.png)

**Comment by jasonbahl** [comment]
@simplenotezy if I'm mistaken, and ACF / ACF Pro do support these fields natively, can you point me to where I can see this in the codebase, and if ACF / ACF Pro support these fields, we can add support to WPGraphQL for ACF as well, but if it's indeed coming from extensions, then the Schema would also need to be extended.
