### ISSUE TITLE
Fatal error when trying to activate plugin

### ISSUE THREAD

**Issue by LaikaTheSpaceDog** [wp-graphql/wp-graphql-acf#248]
I have installed wp-graphql-acf (version 0.5.0), however when I try and activate the plugin I get the following error message:

`Warning: require(/Applications/XAMPP/xamppfiles/htdocs/meraki_wp/wp-content/plugins/wp-graphql-acf-develop/vendor/composer/platform_check.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/meraki_wp/wp-content/plugins/wp-graphql-acf-develop/vendor/composer/autoload_real.php on line 25`

Has anyone encountered this before?

**Comment by jasonbahl** [comment]
@LaikaTheSpaceDog I would recommend downloading from `master` not `develop` as the `develop` branch often contains in-progress work, where `master` is considered the currently stable release.

**Comment by LaikaTheSpaceDog** [comment]
Ah my bad I hadn't noticed I had downloaded from `develop` - thanks, that seems to have solved the issue!

**Comment by jasonbahl** [comment]
👋🏻  the latest develop should now be working to install with composer, as well as the latest master and latest release. 

Closing this as I have confirmation in the WPGraphQL Slack from @henrikwirth, who also experienced this.
