### ISSUE TITLE
Only core ACF fields are returned

### ISSUE THREAD

**Issue by warudin** [wp-graphql/wp-graphql-acf#249]
There's loads of extensions available for Advanced Custom Fields. I am not exactly sure how they extend ACF, but I can imagine that there's an API that's being used. this website (https://www.awesomeacf.com) offers up to 170 extensions, also there's the plugin ACF: Extended that implements various new field types. In several projects we use the plugin 'Advanced Custom Fields: Font Awesome Field' to offer users a way to select an icon for various purposes.

At this moment the current implementation of GraphQL for Advanced Custom Fields seems to return the data from core fields but not the data from fields that are added by extensions for ACF. I'm not sure if support for GraphQL is something that plugin developers need to implement themselves, or if ACF offers a way to extend the current output with data from third party fields.

**Comment by indie-ridge-dev** [comment]
Hi @jasonbahl, any news on this? Thanks!

**Comment by ShahriarKh** [comment]
Any updates?

**Comment by MichLan90** [comment]
Updates? We are having the same problem with 3rd party FontAwesome acf in graphQL

**Comment by ririshi** [comment]
I'm interested in this as well because I'd like to use [this Gravity Forms ACF field type](https://github.com/dannyvanholten/acf-gravityforms-add-on) with WPGraphQL.

**Comment by jasonbahl** [comment]
👋🏻 we're working on a new version of WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf.

The new version has an API for adding support for third party ACF Field Types.

In fact, the plugin comes with support for [ACF Extended](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/AcfExtended.php) Field Types and you can use them as a model for adding support for additional ACF Field Types such as the Open Streetmap field type.

For example:

- [ACFE Advanced Link](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeAdvancedLink.php)
- [ACFE Countries](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeCountries.php)

While we won't be supporting all ACF Field Type extensions out of the box, we will be supporting the APIs for developers to add their own custom ACF Field Types more easily.

We'd recommend checking out the new version of WPGraphQL for ACF as it's what we'll be supporting going forward. It will have a stable release on WordPress.org in the near future and this version will be archived.
