### ISSUE TITLE
Each field group requires updating after installing plugin, in alphabetical order

### ISSUE THREAD

**Issue by lindvall** [wp-graphql/wp-graphql-acf#251]
When installing the plugin I thought I simply needed to "Show in GraphQL" for the field groups I wanted to include in the GrapghQL, however the fields never showed up.

After a few hours of troubleshooting I found that creating a field group with "ACFDemoGroup" worked, however "XDemoGroup" did not. To verify the issue I then activated "Show in GraphQL" in the top field group of the list (sorted alphabetically). As the top group is now populated with the GraphQL parameters all field groups further down the list is displayed properly in the GraphQL.

I've not yet looked into the code if to find the issue. Can it be that the Schema stops being updated from the field groups if the parameters are missing? How are the groups looped through?

I'm using the acf-json way of versioning my field groups.

**Comment by rburgst** [comment]
Having a similar issue. Not sure whether its exactly the same but my fieldGroup is not shown (and yes, the field group starts with `s` so there are a bunch of others (which at least partially show up in the schema) which are alphabetically before.
I have also tried manually forcing the fieldGroup to all Pages but still this does not help, the field group does not show up in the schema: 
![image](https://user-images.githubusercontent.com/22971/115835222-58253000-a416-11eb-90a5-0792ab7e2ccb.png)
![image](https://user-images.githubusercontent.com/22971/115835412-860a7480-a416-11eb-9db2-da53f4a5ab79.png)

**Comment by rburgst** [comment]
Note that it seems that the processing of ACFs stops at field groups that are not enabled for GraphQL. 
After enabling this (previously disabled) group for GraphQL it seems that the processing gets a bit further, this means that the next enabled GraphQL fieldGroup now shows up in the schema.

**Comment by rburgst** [comment]
After enabling all graphql disabled field groups, now my `selectMenu` ACF finally shows up in the schema. This sounds like that there is some problem with enabled ACF field groups that are not enabled for GraphQL (i.e. where "Show in GraphQL" is "No").

**Comment by jasonbahl** [comment]
@rburgst ah, thanks for pointing this out. I think I know what the issue is and will get a fix out shortly!

**Comment by jasonbahl** [comment]
@lindvall  @rburgst can you see if #253 resolves this?

**Comment by jasonbahl** [comment]
Fwiw, I pushed up a test that registers 2 field groups. The first one alphabetically is set to not show in GraphQL, the 2nd one is. 

The test tries to query the 2nd group and fails.

https://github.com/wp-graphql/wp-graphql-acf/runs/2420830197?check_suite_focus=true#step:8:167

With the `continue;` instead of `return;` in place, the test now succeeds and the field group set to not show in GraphQL still is not in the Schema, but the one that is, is in the Schema: 

https://github.com/wp-graphql/wp-graphql-acf/runs/2420841392?check_suite_focus=true#step:8:119

**Comment by rburgst** [comment]
Checked the latest version and it seems to work. Thanks for the prompt resolution.
