### ISSUE TITLE
Plugin should not execute if ACF and WPGraphQL are both not active

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#26]
Currently we check to see if ACF and WPGraphQL are both active, and if not we show an admin notice. . .but we still attempt to make use of ACF functions, even if it's not active. 

In addition to the notice, we should also prevent further execution to avoid fatal errors.

https://github.com/wp-graphql/wp-graphql-acf/blob/master/wp-graphql-acf.php#L52

**Comment by jacobarriola** [comment]
@jasonbahl do you mind if I take a stab at this one?

**Comment by jasonbahl** [comment]
@jacobarriola that would be awesome. Thanks!

**Comment by kalebheitzman** [comment]
```Fatal error: Uncaught Error: Call to undefined function WPGraphQL\ACF\acf_get_field_groups() in /app/public/wp-content/plugins/wp-graphql-acf/src/class-config.php:142 Stack trace: #0 /app/public/wp-content/plugins/wp-graphql-acf/src/class-config.php(32): WPGraphQL\ACF\Config->add_acf_fields_to_post_object_types() #1 /app/public/wp-includes/class-wp-hook.php(286): WPGraphQL\ACF\Config->init('') #2 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /app/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /app/public/wp-content/plugins/wp-graphql/src/TypeRegistry.php(240): do_action('graphql_registe...') #5 /app/public/wp-content/plugins/wp-graphql/wp-graphql.php(517): WPGraphQL\TypeRegistry::init() #6 /app/public/wp-content/plugins/wp-graphql/src/Request.php(85): WPGraphQL::get_schema() #7 /app/public/wp-content/plugins/wp-graphql/src/Router.php(336): WPGraphQL\Request->__construct() #8 /app/public/wp-content/plugins/wp-graphql/src/Router.php(153): WPGraphQL\Router::process_htt in /app/public/wp-content/plugins/wp-graphql-acf/src/class-config.php on line 142```

Relevant line of code that errors out.

**Comment by jacobarriola** [comment]
Thanks @kalebheitzman . Out of curiosity, what page are you loading when that fatal message occurs? I can't seem to reproduce.

**Comment by kalebheitzman** [comment]
> what page are you loading

@jacobarriola I believe it was actually the graphql endpoint on the Wordpress end of things. If I remember correctly, I was seeing query errors in the terminal running gatsby, and then checked /graphql and that's what I saw as an error. It was on Flywheel if that matters and I'm sure php error reporting was turned on.

**Comment by jacobarriola** [comment]
Boom. Got it. Thanks.

**Comment by jasonbahl** [comment]
closed by #27
