### ISSUE TITLE
Uncuaght type error: t is null

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-acf#260]
When using WP-GQL-ACF `0.5.2` and ACF Pro `5.9.5`, and then try to add a image field to a Site Options field group, I get the following error:

<img width="1119" alt="Screen Shot 2021-05-04 at 9 02 25 PM" src="https://user-images.githubusercontent.com/475015/117056031-24061500-ad1c-11eb-8bc9-0fbe96c06a89.png">

**Steps to reproduce:**
Import this field group: https://github.com/funkhaus/fuxt-backend/blob/master/acf/site-options.json

Then try to add an image field to that group, look in console.

I tested on default 2020 theme and with no plugins installed other than ACF Pro and WP-GQL-ACF.

**Comment by drewbaker** [comment]
Tried this with old version (5.9.0) of ACF and `0.50` of WP-GQL-ACF too. Same error.

If I disable WP-GQL-ACF then it works.

**Comment by drewbaker** [comment]
Weird thing is I have the same combo of plugins installed on lots of other sites and don't get these errors.

**Comment by jasonbahl** [comment]
@drewbaker I just imported this field group with:

- ACF Pro v5.9.4
- WPGraphQL v1.3.7
- WPGraphQL for ACF v0.5.2

And I do not get any console errors 🤔 

You say it seems to be only on one site. Do you have `define( 'SCRIPT_DEBUG', true );` defined on that site? Perhaps it's related to that?

**Comment by drewbaker** [comment]
No I don't have `define( 'SCRIPT_DEBUG', true );` set, not that I know of. Super confusing. I will keep trying.

**Comment by drewbaker** [comment]
So the problem is related to this. The `acf` JS global object isn't correct for the broken site. Maybe this helps shed some light?

I just deleted all plugins, reinstalled them one by one. If I have both the WP-GQL and WP-GQL-ACF activated I get the error. If I have just one of them, it works fine.

<img width="1126" alt="Screen Shot 2021-05-05 at 12 56 09 AM" src="https://user-images.githubusercontent.com/475015/117079766-b8806f80-ad3c-11eb-8f0e-dbb088cb4d4b.png">
<img width="1134" alt="Screen Shot 2021-05-05 at 12 56 14 AM" src="https://user-images.githubusercontent.com/475015/117079770-bb7b6000-ad3c-11eb-9045-e3dabbf19e7d.png">

**Comment by drewbaker** [comment]
I re-installed WordPress, deleted all plugins and then reinstalled everything and this was fixed.
