### ISSUE TITLE
blocksJSON returns the wrong data structure

### ISSUE THREAD

**Issue by manuliak** [wp-graphql/wp-graphql-acf#263]
**I created an ACF block with a repeater field - "books", and this field includes a text field - "Title"**
[ACF blocks](https://www.advancedcustomfields.com/resources/blocks/)

![Screenshot from 2021-05-31 14-30-17](https://user-images.githubusercontent.com/8714097/120186658-73a50700-c21c-11eb-8929-c4411e95e70a.png)

![Screenshot from 2021-05-31 14-25-23](https://user-images.githubusercontent.com/8714097/120186267-f37ea180-c21b-11eb-9142-917740b60482.png)

**In the page editor, my block looks like this**

![Screenshot from 2021-05-31 14-32-59](https://user-images.githubusercontent.com/8714097/120186989-e910d780-c21c-11eb-9e0e-f34a5bf8826f.png)

**I want to get all the blocks that are on the page**

```
query MyQuery {
  page(id: 11, idType: DATABASE_ID) {
    blocksJSON
  }
}
```

 **and this query returns me this result**

![Screenshot from 2021-05-31 14-38-05](https://user-images.githubusercontent.com/8714097/120187619-b4e9e680-c21d-11eb-88e7-831c20ff8973.png)

**I expected to get the data in a format like:**

`"books": [ 'title1', 'title2' ....]`

**is it possible?**

**Comment by bhardie** [comment]
WpGraphQL for ACF doesn't support Gutenberg yet.  You might consider opening an issue on the [wp-graphql-gutenberg](https://github.com/pristas-peter/wp-graphql-gutenberg) repo.
