### ISSUE TITLE
acf_get_options_page requires ACF Pro

### ISSUE THREAD

**Issue by james-wfaa** [wp-graphql/wp-graphql-acf#264]
Running wp-graphql-acf 0.5.2 with advanced-custom-fields 5.9.6, I got this error when trying to load the GraphiQL browser: 

PHP Fatal error: Uncaught Error: Call to undefined function WPGraphQL\\ACF\\acf_get_options_page() in /nas/content/live/uwadvancement/wp-content/plugins/wp-graphql-acf-develop/src/location-rules.php:948

I think we had ported over some /acf-json/ files from a different project, and one of them contained a field group definition that was on an options page. 

But this code in location-rules.php should probably check for the existence of the function before calling it.

**Comment by benbender** [comment]
+1

**Comment by mkreidler** [comment]
I also have this error

**Comment by jasonbahl** [comment]
This bug has been resolved in the new version of WPGraphQL for ACF, being worked on over here: https://github.com/wp-graphql/wpgraphql-acf. 

It's a major re-architecture of the plugin and resolves a LOT of issues this plugin suffered from. It's the version we'll be releasing to the WordPress.org plugin repo (in the review queue now) and it's what we'll be supporting long-term. This repo will be archived in the not-too-distant future.
