### ISSUE TITLE
ACF Image returns null unless title is set on image

### ISSUE THREAD

**Issue by lggarrison** [wp-graphql/wp-graphql-acf#265]
I'm using `wp-graphical-acf` to display an ACF repeater of images.

There seems to be an issue with the images and their titles. The images are being returned as `null` unless I update the images with a new title, the title can even be an empty string.

I can recreate the issue each time I add an image to the repeater: `Cannot read property 'sourceUrl' of null`.

Resaving the image with a new title on the WP Edit Image UI resolves the problem.

I'm not exactly sure what is happening here because I am new to using ACF with GraphQL. It might be because I uploaded the images to WordPress before installing WP-Graphql-ACF, but I wanted to report this issue here in case other people run into a similar problem.

**Comment by jasonbahl** [comment]
I wasn't able to reproduce this. 

This plugin is being re-built over here: https://github.com/wp-graphql/wpgraphql-acf

I tested this functionality on the new version and I'm able to query images on repeater fields without issue: 

![CleanShot 2023-11-07 at 14 52 38](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/331d2c51-4fb6-400c-abb5-ccae1750629b)

This repo will be archived in the near-future so we encourage you to update to the new version when you have a chance. 

If you have problems with the new version, open up an issue on that repo 🙏🏻

**Comment by KeelanJon** [comment]
Just encountered this issue too in the same scenario when attempting to return image data that is nested in a repeater field, although in my case adjusting the title didn't resolve the issue.

I'm currently using the WPGraphQL for ACF plugin available directly in the Plugin Directory on wordpress which has otherwise been working great, but attempting to install and activate the new version provided by @jasonbahl above causes a critical error.

Still tinkering at this time but I am yet to find a work around.

Edit: Resolved.
Setting the Image data return format to **Image Array** in the field settings looks to have fixed this issue for me. Previously I used to set this to return as Image URL but this seems to be returning NULL since an update.

**Comment by jasonbahl** [comment]
> attempting to install and activate the new version provided by @jasonbahl above causes a critical error.

@KeelanJon what was the error? Did you install from the WordPress.org repo or did you install from GitHub? I'd recommend installing from WordPress.org directly as it contains all the built assets (composer dependencies, etc)

If you clone from GitHub, you would need to manually install the composer dependencies. 

----

> Setting the Image data return format to Image Array in the field settings looks to have fixed this issue for me. Previously I used to set this to return as Image URL but this seems to be returning NULL since an update.

@KeelanJon you had to make this change on the new WPGraphQL for ACF v2.0.0 or on the old v0.6.1 (this current repo?)

If it's a bug in the v2.0.0, could you open an issue on that repo so we can properly track and address the bug? 🙏🏻

**Comment by Bowriverstudio** [comment]
FYI I was able to reproduce this issue:

If you use  'return_format' => 'array', in the repeater array with the 


 * Plugin Name: WPGraphQL for ACF
 * Description: WPGraphQL for ACF seamlessly integrates Advanced Custom Fields with WPGraphQL.
 * Author: WPGraphQL, Jason Bahl
 * Author URI: https://www.wpgraphql.com
 * Version: 2.3.0
 * Text Domain: wpgraphql-acf
 * Requires PHP: 7.3
 * Requires at least: 5.
 
 It will return null
 
 
 
## This works
```php 
<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(
        array(
            'key' => 'group_safety_standards_section',
            'title' => 'Safety Standards Section',
            'fields' => array(

                array(
                    'key' => 'brudco_field_safety_main_heading',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                ),
                array(
                    'key' => 'brudco_field_safety_main_subheading',
                    'label' => 'Subheading',
                    'name' => 'subheading',
                    'type' => 'textarea',
                ),
                array(
                    'key' => 'field_safety_standards',
                    'label' => 'Safety Standards',
                    'name' => 'safety_standards',
                    'type' => 'repeater',
                    'layout' => 'table',
                    'sub_fields' => array(
                        array(
                            'key' => 'brudco_field_safety_icon',
                            'label' => 'Safety Icon',
                            'name' => 'safety_icon',
                            'type' => 'image',
                            'return_format' => 'array',
                        ),
                    ),
                ),
                array(
                    'key' => 'brudco_field_safety_background_image',
                    'label' => 'Background Image',
                    'name' => 'background_image',
                    'type' => 'image',
                    'return_format' => 'url',
                ),

            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'brudco/safety-section',
                    ),
                ),
            ),
        )
    );

endif;
?>

```

THis fails
```php
<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(
        array(
            'key' => 'group_safety_standards_section',
            'title' => 'Safety Standards Section',
            'fields' => array(

                array(
                    'key' => 'brudco_field_safety_main_heading',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                ),
                array(
                    'key' => 'brudco_field_safety_main_subheading',
                    'label' => 'Subheading',
                    'name' => 'subheading',
                    'type' => 'textarea',
                ),
                array(
                    'key' => 'field_safety_standards',
                    'label' => 'Safety Standards',
                    'name' => 'safety_standards',
                    'type' => 'repeater',
                    'layout' => 'table',
                    'sub_fields' => array(
                        array(
                            'key' => 'brudco_field_safety_icon',
                            'label' => 'Safety Icon',
                            'name' => 'safety_icon',
                            'type' => 'image',
                            'return_format' => 'url',
                        ),
                    ),
                ),
                array(
                    'key' => 'brudco_field_safety_background_image',
                    'label' => 'Background Image',
                    'name' => 'background_image',
                    'type' => 'image',
                    'return_format' => 'url',
                ),

            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                        'value' => 'brudco/safety-section',
                    ),
                ),
            ),
        )
    );

endif;
?>
