### ISSUE TITLE
Select does not support 'array' return type.

### ISSUE THREAD

**Issue by noudadrichem** [wp-graphql/wp-graphql-acf#267]
I haven't found this in the docs nor other issues (yet). Please correct me if I'm wrong.
I'd like the 'select' field in ACF to return both the value and label. This can be selected as 'output type' under the ACF menu but gives errors when fetching them in GraphIQL

```json
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "foo",
        "bar",
        0,
        "foo",
        "bar",
        0
      ]
    },
```

This could look something like this:
```js
[
  {
    label: 'Foo Label',
    value: 'foo_label'
  },
]
```

**Comment by vladfil** [comment]
For now not possible return anything but a "String", so for returned value possible add separator and split it on frontend side.
Here is code, depending on "Return Value" in ACF settings:

```
add_filter('graphql_acf_field_value', function ($value, $acf_field, $root, $id) {
    $separator = '|';

    if ($acf_field['type'] === 'select') {
        $label = $acf_field['choices'][$value];

        if ($acf_field['return_format'] === 'array') {
            return $value . $separator . $label;
        } else if ($acf_field['return_format'] === 'label') {
            return $label;
        }
    }

    return $value;
}, 10, 4);
```

But in the future will be good add filter that allow change return type.

**Comment by jasonbahl** [comment]
👋🏻 Hey, we're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf. 

It's a full re-architecture of the plugin and it resolves a LOT of issues this plugin suffered from. 

Unfortunately at the moment, this particular issue hasn't yet been resolved in the new plugin, but we do have the following issue on the new repo to track it: https://github.com/wp-graphql/wpgraphql-acf/issues/105

I'm going to close this issue in favor of the issue on the new repo. 

That's the version we'll be going stable with and releasing to the WordPress.org repo, then will archive this repo in the not-too-distant future. 

Thanks! 🙏🏻
