### ISSUE TITLE
ACF Options Page Field Values Return Null

### ISSUE THREAD

**Issue by bbuilds** [wp-graphql/wp-graphql-acf#268]
Tried copying the example directly from the docs into 2021 theme after not working in my custom theme. 

Both the field and group are enabled to display in Graphql.

These only seems to happen on parent settings while the other custom settings with parent slugs seem to work like `'parent_slug'   => 'edit.php?post_type=cpt_name,`

- wp-graphql 1.4.3
- acf-pro 5.9.6
- wp-graphql-acf 0.5.0
- WP 5.7.2

![Screen Shot 2021-06-17 at 10 09 41 AM](https://user-images.githubusercontent.com/29581184/122413736-9a6d7800-cf54-11eb-9f01-35dcc6643b68.png)

![Screen Shot 2021-06-17 at 10 09 58 AM](https://user-images.githubusercontent.com/29581184/122413698-92add380-cf54-11eb-8df5-f615ec52e8ee.png)

**Comment by logandeancall** [comment]
@bbuilds How did you resolve this issue? I'm running into the same problem now.

**Comment by lewebsimple** [comment]
Same here
