### ISSUE TITLE
v0.6.0 - Repeater groups show as Type: String in Schema

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#270]
When using the v0.6.0 branch of the plugin, repeater fields are showing type `String` in the Schema. 

This was reported by @craigwilcox

See: ![image (1)](https://user-images.githubusercontent.com/1260765/122774612-926c4b80-d266-11eb-8692-68092da7809b.png)

**Comment by rodrigo-arias** [comment]
@jasonbahl I can confirm this issues while testing the 0.6.0 branch which contains some important fixes. It would be great to be able to resolve this one if the 0.6.0 release is still delayed. Thanks a lot for your work

**Comment by jasonbahl** [comment]
closed as this has been resolved in the re-architected version of the plugin over here: https://github.com/wp-graphql/wpgraphql-acf
