### ISSUE TITLE
Internal Server Error thrown when using in PHP 8.0

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#274]
@wjohnsto reported that `Internal Server Error` is being thrown when using WPGraphQL with PHP 8.0. 

I've not attempted to replicate this, but wanted to open an issue to track this.

**Comment by jonsherrard** [comment]
I'm getting this same error using PHP 7.4, no issue with PHP 7.3

**Comment by jonsherrard** [comment]
Another note, I ran this plugin and all the dependencies through PHP Code Sniffer to look for any upgrade issues between 7.3 and 7.4 and came up with nothing:

`./bin/phpcs -p . --standard=PHPCompatibilityWP --extensions=php --runtime-set testVersion 7.3-`

**Comment by ol1s** [comment]
Am getting the same error

```
{
  posts(first: 1) {
    nodes {
      uri
      featuredImage {
        node {
          sourceUrl(size: LARGE)
        }
      }
    }
  }
}
```

```
{
  "errors": [
    {
      "debugMessage": "in_array(): Argument #2 ($haystack) must be of type array, string given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "posts",
        "nodes",
        0,
        "featuredImage"
      ]
    }
  ],
  "data": {
    "posts": {
      "nodes": [
        {
          "uri": "/news/2023/03/test-slug",
          "featuredImage": null
        }
      ]
    }
  },
  "extensions": {
    "debug": [],
    "queryAnalyzer": {
      "keys": "76151bf98e20d879c27da29d22a7bac294b8e9fbdf1326a7e40afa0db60e01aa graphql:Query list:post cG9zdDoyOTA0",
      "keysLength": 101,
      "keysCount": 4,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  }
}
```

Server info:

PHP version 8.0.28
WP Version 6.1.1
WPGraphQL Version 1.14.0
WPGraphQL for Advanced Custom Fields Version 0.5.3

**Comment by marco910** [comment]
I get a similar issue using version 0.6.1 of the plugin with PHP 8.2.

When registering a custom field and field type using `register_graphql_object_type`, `add_filter('wpgraphql_acf_register_graphql_field')`, and `add_filter('wpgraphql_acf_supported_fields')` I get a similar error:

```
Uncaught TypeError: asort(): Argument #1 ($array) must be of type array, null given in /var/www/html/wp-content/plugins/wp-graphql-acf-0.6.1/src/class-config.php:1337
```

When testing the same code with PHP 8.2 and version 0.3.4 of the WPGraphQL ACF plugin, everything works fine.

**Comment by jasonbahl** [comment]
@marco910 I would recommend checking out the new WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. It was re-architected and re-built from the ground up and solves a lot of issues that v0.6.1 suffered from. 

The specific filter you mentioned has been re-named to `wpgraphql/acf/supported_field_types`. You can read more about that in the [upgrade guide](https://acf.wpgraphql.com/upgrade-guide/#action-and-filter-changes) and in [GitHub here](https://github.com/wp-graphql/wpgraphql-acf/pull/67#issue-1818715865).

note: In WordPress, when filtering, make sure you return a value as well, in this case an array. 

If you try this out with the new version of WPGraphQL for ACF and still run into an issue, please open a new issue on the new repo: https://github.com/wp-graphql/wpgraphql-acf 🙏🏻 

I'm going to close this issue as the new version of WPGraphQL for ACF has tests that run on [PHP 8.0, 8.1 and 8.2](https://github.com/wp-graphql/wpgraphql-acf/blob/main/.github/workflows/testing-integration.yml#L27-L29) and things are working as expected.
