### ISSUE TITLE
Select field with array as return type, inside flexible content, return empty in graphql

### ISSUE THREAD

**Issue by polletto** [wp-graphql/wp-graphql-acf#296]
The "Select" filed of acf inside a flexible content with return both (value and label) return always an empty array. If want only return label in graphql shows always the value.

**Comment by jasonbahl** [comment]
Closing this as it's been resolved in the new version of WPGraphQL for ACF, being re-built over here: https://github.com/wp-graphql/wpgraphql-acf

read more: https://github.com/wp-graphql/wp-graphql-acf/issues/318#issuecomment-1626227889
