### ISSUE TITLE
WYSIWYG & Textareas not getting auto p and br tags

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-acf#3]
If you use the WYSIWYG or Textarea fields, normally the output would get the WordPress auto `<p>` and `<br>` tags applied to them. The `textarea` field actually has a dropdown to opt into no formatting, or just `br`, or both `p` or `br`.

It seems WYSIWYG should always be set to auto-p (basically behave the same as regular `post_content` fields, and the `textarea` should respect the dropdown settings.

WYSIWYG output should run through this filter: `apply_filters('the_content', $output);`

And `textarea` should run through the different options of this function it seems: 
https://codex.wordpress.org/Function_Reference/wpautop

**Comment by jasonbahl** [comment]
Ah! Good call. I'll get this patched up.

**Comment by jasonbahl** [comment]
Got this fixed in v0.1.3 (releasing as we speak)

**Comment by BartoszLobejko** [comment]
Hey @jasonbahl 
I'm experiencing the same issue but on WYSIWYG that is inside Flexible Content or Repeater. 
I got wp-graphql-acf 1.4

**Comment by jasonbahl** [comment]
@BartoszLobejko thanks for reporting. I'll have another look. 

Can you provide a .json export of the fields and an example of the query you're executing so I can replicate the issue?

**Comment by BartoszLobejko** [comment]
Yeah sure,
Attached is JSON export and here my query fragments.
It goes from the smallest parts to big query order.

`
export const ImageFragment = gql`
  fragment Image on MediaItem {
    sourceUrl
    id
    slug
    title
    srcSet
    description
    modifiedGmt
    caption
    altText
    mediaDetails {
      sizes {
        name
        sourceUrl
      }
    }
  }
`;

const ColumnFragment = gql`
  fragment Column on Page_Sections_Sections_Content_columns {
    image {
      ...Image
    }
    content
    button {
      label
      url
      style
    }
  }
`;

export const ContentFragment = gql`
  fragment Content on Page_Sections_Sections_Content {
    style
    toprow {
      content
      image {
        ...Image
      }
    }
    columns {
      __typename
      ...Column
    }
  }
  ${ColumnFragment}
  ${ImageFragment}
`;

const PAGE_QUERY = gql`
  query PageQuery($uri: String!) {
    pageBy(uri: $uri) {
      link
      title
      modified
      sections {
        __typename
        sections {
          __typename
          ...Content
        }
      }
    }
  }
  ${ContentFragment}
`;
`

[acf-export-2019-06-06.json.zip](https://github.com/wp-graphql/wp-graphql-acf/files/3259569/acf-export-2019-06-06.json.zip)

**Comment by BartoszLobejko** [comment]
Hey @jasonbahl, Any ETA for this bug? This is the last detail that holds me of from Production deployment.

**Comment by jasonbahl** [comment]
Looking at this now.

**Comment by jasonbahl** [comment]
@BartoszLobejko this looks like it _might_ be a core ACF issue. 

See: https://support.advancedcustomfields.com/forums/topic/inline-tags-are-removed-from-s-when-wysiwyg-in-flex-contentrepeater/

I'm still digging though.

**Comment by jasonbahl** [comment]
@BartoszLobejko I found the issue. PR coming and will be included in the next release.

**Comment by BartoszLobejko** [comment]
@jasonbahl Great news, thank you! That would be second last bug for me before our project being released. 
Last one is quite major: [https://github.com/wp-graphql/wp-graphql/issues/891](https://github.com/wp-graphql/wp-graphql/issues/891)
