### ISSUE TITLE
Required parameter deprecation notice PHP8

### ISSUE THREAD

**Issue by KevinBatdorf** [wp-graphql/wp-graphql-acf#303]
PHP will [show a deprecated notice](https://php.watch/versions/8.0/deprecate-required-param-after-optional) for when an optional parameter is defined before a required one.

https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/location-rules.php#L209

I have debug mode on with notices printed to the screen while developing, so it breaking the request.

Thanks

**Comment by jasonbahl** [comment]
closed by #313 

p.s. this repo will be archived in the not-too-distant future in favor of the re-architected plugin over here: https://github.com/wp-graphql/wpgraphql-acf and the new version will be released on the WordPress.org repo and is the version we'll be supporting long term. 🙏🏻
