### ISSUE TITLE
Location rule Taxonomy equals is not exposed to graphql

### ISSUE THREAD

**Issue by mooksz** [wp-graphql/wp-graphql-acf#306]
I have a custom taxonomy with some terms that I'm trying to attach some data to. But the fields I created are not exposed to the graphql api

**Comment by jasonbahl** [comment]
Closing this as this has been addressed for quite some time. 

In WPGraphQL v0.6.1 field groups will map to the Schema based on the Field Group's location rules. If the Location Rules cannot be matched, then you can custom select which GraphQL Type(s) the Field Group should be attached to in the Schema. 

For the example below I'm using this Field Group exported as JSON: [acf-export-2023-07-12.json.zip](https://github.com/wp-graphql/wp-graphql-acf/files/12029055/acf-export-2023-07-12.json.zip)

And using WPGraphQL v1.14.6 and WPGraphQL for ACF v0.6.1

This field group is set with the location rules: "Taxonomy is equal to Tag" and you can see this will map to the "Tag" type in the GraphQL Schema. 


![CleanShot 2023-07-12 at 08 30 26](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/05b4c0be-e342-465a-bb0c-255db492000e)

I can then query this field group (named DELETE ME) like so: 

![CleanShot 2023-07-12 at 08 36 15](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/cbc87538-26df-452e-b725-b9f6ce901951)


----

WPGraphQL for ACF is being re-written over here: https://github.com/wp-graphql/wpgraphql-acf and this also works in the new version (v2.0.0-beta.3.1.0 as of writing this comment)

Here's how the same field group could be queried in the new version of WPGraphQL for ACF:

![CleanShot 2023-07-12 at 08 40 08](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/d8a72e85-c5bd-4f6c-a99b-7cf974435dbc)

For anyone reading this, I'd recommend making the switch to the new version as it's what we'll be supporting going forward and what will be released on the WordPress.org plugin repo in the not-too-distant future!
