### ISSUE TITLE
Error from The Events Calendar with v 0.5.3

### ISSUE THREAD

**Issue by craigwilcox** [wp-graphql/wp-graphql-acf#310]
When trying to move an attendee from one event to another, we are encountering a critical error on the our sites when using v. 0.5.3. 

This is the stack trace and error description:

```
Error Details
=============
An error of type E_ERROR was caused in line 217 of the file /nas/content/staging/rmsewing/wp-content/plugins/wp-graphql-acf-0.5.3/src/class-acfsettings.php. Error message: Uncaught TypeError: Argument 1 passed to WPGraphQL\ACF\ACF_Settings::enqueue_graphql_acf_scripts() must be of the type string, null given, called in /nas/content/staging/rmsewing/wp-includes/class-wp-hook.php on line 303 and defined in /nas/content/staging/rmsewing/wp-content/plugins/wp-graphql-acf-0.5.3/src/class-acfsettings.php:217
Stack trace:
#0 /nas/content/staging/rmsewing/wp-includes/class-wp-hook.php(303): WPGraphQL\ACF\ACF_Settings->enqueue_graphql_acf_scripts(NULL)
#1 /nas/content/staging/rmsewing/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /nas/content/staging/rmsewing/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /nas/content/staging/rmsewing/wp-admin/includes/template.php(2046): do_action('admin_enqueue_s...', NULL)
#4 /nas/content/staging/rmsewing/wp-content/plugins/event-tickets/src/Tribe/Admin/Move_Tickets.php(88): iframe_header('Move Attendees')
#5 /nas/content/staging/rmsewing/wp-includes/class-wp-hook.php(303): Tribe__Tickets__Admin__Move_Tickets->
```

This "move attendees" feature works with version 0.3.3. 

All Events Calendar plugins are updated to the latest version. 

Happy to help debug...

Thanks,
Craig

**Comment by jasonbahl** [comment]
@craigwilcox does changing this line: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-acfsettings.php#L233

to: 

`public function enqueue_graphql_acf_scripts( ?string $screen ) {`

help?

It looks like the callback for `admin_enqueue_scripts` expects a string, but for some reason when used with that plugin a string is not being passed to the callback?

According to the hook's inline docblock here, a string should be expected: https://github.com/WordPress/WordPress/blob/4e70f57a0b3ed76682e778df0b8240d12f00cc5a/wp-admin/admin-header.php#L118

but it seems like the Events Calendar might be overriding some things? 

Anyway, based on how long ago this was, and how long it took me to reply, I assume this might not even be an issue anymore? 🤷🏻‍♂️

**Comment by jasonbahl** [comment]
I closed this as I'm not sure it's valid at this point, but if it is we can re-open. 

I'd love to see you try the new version of the plugin over at https://github.com/wp-graphql/wpgraphql-acf and let us know if it works with the Events Calendar or not 🙏🏻
