### ISSUE TITLE
New WP-GraphQL Update ACF Flexible Content Field Layouts Not Displaying in Query Composer

### ISSUE THREAD

**Issue by jhochgrevetsd** [wp-graphql/wp-graphql-acf#312]
As an example, we have a layout called Page_Contentmodules_Content_StandardContent. If I manually add:

... on Page_Contentmodules_Content_SideBySideContentColumns (and all of its content fields)

to the query, it still pulls the content but the layout itself no longer displays in the composer.

**Comment by ArmandPhilippot** [comment]
It's seems to be related to the new GraphiQL version and not this plugin. See: https://github.com/wp-graphql/wp-graphql/issues/2287

**Comment by jasonbahl** [comment]
I believe this was addressed by https://github.com/wp-graphql/wp-graphql/pull/2572
