### ISSUE TITLE
How to expose custom acf field to wp-graphql?

### ISSUE THREAD

**Issue by ShahriarKh** [wp-graphql/wp-graphql-acf#314]
I installed this extension (https://github.com/ildrm/acf-jalalidatepicker) to add a custom datepicker to ACF.
This is working fine, but I don't know how to enable the "Show in GraphQl" thing like other fields.
Any help is appreciated! 😸

![image](https://user-images.githubusercontent.com/31452340/157670509-4fca7b41-4e77-4624-b1ba-b960fe2cac1d.png)

**Comment by raulclaudino** [comment]
@ShahriarKh Did you manage to resolve this? Got any tips?

**Comment by ShahriarKh** [comment]
@raulclaudino Unfortunately, not yet.

**Comment by macojaune** [comment]
I would love to get some help on this matter. I can't find documentation on what to add to my custom field for it to be found in Graphql  Schema

**Comment by robmarshall** [comment]
I also need to add a custom field. Been struggling to find a solution.

**Comment by jasonbahl** [comment]
👋🏻 We're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf and in the new version we have a new API for mapping ACF Field Types to the GraphQL Schema.

The new version of the plugin has built-in support for ACF Extended (free and PRO), which uses the new API for mapping custom ACF Field Types to the GraphQL Schema.

It's not fully documented yet, but you can see plenty of examples of using the new register_graphql_acf_field_type() API in this directory: https://github.com/wp-graphql/wpgraphql-acf/tree/main/src/ThirdParty/AcfExtended

Here's also a GIST showing how @CesarBenavides777 mapped the ACF Table field type to the GraphQL Schema: https://gist.github.com/CesarBenavides777/79b158db8355ddbc349fbf9b3272ae47
