### ISSUE TITLE
How to query ACF field group independently?

### ISSUE THREAD

**Issue by ShahriarKh** [wp-graphql/wp-graphql-acf#315]
I have a field group called `productfilters` and it consists of some fields like `colors`.
I want to get the `productfilters` independently, **without querying posts**.

Ideally a query like this:
```graphql
query myQuery {
    productfilters {
       colors
    }
}
```
that should return something like this:
```js
filters {
    colors:  ["blue", "green", "red"]
}
```

![image](https://user-images.githubusercontent.com/31452340/157987963-8a4461b4-b00e-4fb8-ad3d-ae1cbab3b79c.png)

**Comment by jasonbahl** [comment]
@ShahriarKh hello, this is not possible. 

The way ACF works is by creating field groups and associating those field groups with a Type of content (Posts, Terms, etc). 

You can query those types of content (called "Nodes" in GraphQL), then access the associated ACF Fields from the node the field group is associated with. But you cannot access a field directly as the fields are properties of Nodes.

If you want a custom set of data that you can query independently, perhaps you would want a Custom Post Type or Custom Taxonomy, which [you can register with ACF as of v6.1](https://www.advancedcustomfields.com/resources/post-types-and-taxonomies/)
