### ISSUE TITLE
Internal Server Error with ACF Blocks

### ISSUE THREAD

**Issue by ttstauss** [wp-graphql/wp-graphql-acf#316]
Hello, hoping someone can point me in the right direction.

I've been using **WPGraphQL** without issue and it's been awesome. I recently set up **ACF** and **WPGraphQL for ACF** along with an **ACF block** (a simple **relationship field** mapped to an **Atlas Content Model**).

When I attempt to run a query on blocks, I get the following:

`debugMessage`: `DOMDocument::loadHTML(): Argument #1 ($source) must not be empty`.

The error only happens when I actually add the ACF block to a page. Any ideas?

Additional context
------

### ACF Block setup:
```
<?php

add_action('acf/init', 'my_acf_init_block_types');
function my_acf_init_block_types() {

    // Check function exists.
    if( function_exists('acf_register_block_type') ) {

        // register department block.
        acf_register_block_type(array(
            'name' => 'departments',
            'title' => __('Departments'),
            'description' => __('Custom departments block.'),
            'category' => 'widgets',
            'icon' => 'admin-multisite',
            'keywords' => array( 'departments' ),
	    'mode' => 'edit',
	    'supports' => array( 'align' => false, 'mode' => false ),
        ));
    }
}
```

### Custom Field setup:

![screencapture-bereafaust-wpengine-wp-admin-post-php-2022-03-18-14_30_58](https://user-images.githubusercontent.com/15224340/159079240-80738356-a698-449f-95bc-b1598071fe8c.png)

### Page usage:

![Screenshot 2022-03-18 140132](https://user-images.githubusercontent.com/15224340/159079387-90e1a75a-ed60-4d08-bee1-3e0178d073e6.png)

#### NOTE: _I made sure the `WP GraphQL Gutenberg` block registry is updated_.
(maybe the problem is with the `WP GraphQL Gutenberg` plugin?)

### GraphiQL query:
NOTE: The error happens regardless of what block I attempt to query (if `blocks` is in the query, it throws the error).
```
query getPage($id: ID!) {
  page(id: $id, idType: DATABASE_ID) {
    title
    blocks {
      name
      innerBlocks {
        name
      }
      ... on AcfDepartmentsBlock {
        attributes {
          ... on AcfDepartmentsBlockAttributes {
            data
          }
        }
      }
    }
  }
}
```

### Response:
```
{
  "errors": [
    {
      "debugMessage": "DOMDocument::loadHTML(): Argument #1 ($source) must not be empty",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "page",
        "blocks"
      ]
    }
  ],
  "data": {
    "page": {
      "title": "Home",
      "blocks": null
    }
  },
  "extensions": {
    "debug": []
  }
}
```

**Comment by ttstauss** [comment]
Looks like this issue was related to `WPGraphQL Gutenberg`. A fix has been submitted here [[Bugfix] #100 - Fix parsing empty attributes/HTML](https://github.com/pristas-peter/wp-graphql-gutenberg/pull/139) ([Plugin breaks with PHP 8 #100](https://github.com/pristas-peter/wp-graphql-gutenberg/issues/100#issuecomment-1072971200)).

**Comment by mrclay** [comment]
@ttstauss I think this is fixed in `develop` but author has not tagged a new release.

**Comment by jasonbahl** [comment]
I'm going to close this issue as I believe it's more related to WPGraphQL Gutenberg and WPGraphQL Gutenberg ACF then it is to this repo. 

This plugin is being actively re-written over here: https://github.com/wp-graphql/wpgraphql-acf and will be released on WordPress.org in the not-too-distant future. 

There's high probability that it will formally provide support for the WPGraphQL Content Blocks plugin being developed by WP Engine: https://github.com/wpengine/wp-graphql-content-blocks

I've experimented with supporting the bridge between ACF Blocks and WPGraphQL Content Blocks and it's promising and will likely be something we'll officially support in the coming months. I'd recommend tracking issues such as this one: https://github.com/wpengine/wp-graphql-content-blocks/issues/40

**Comment by mrclay** [comment]
@jasonbahl Thanks for that info 🙇‍♂️
