### ISSUE TITLE
ACF Select Field can't return Array format

### ISSUE THREAD

**Issue by ShahriarKh** [wp-graphql/wp-graphql-acf#318]
For some reason, I can't use the Array for return format and it throws an error.
I also saw #296 , #267 and #31, but none of them has a solution for a Headless WordPress. (My frontend is made with react, so theme functions doesn't help)

Plugin Versions:
```graphql
WP GraphQL: 1.7.2
WPGraphQL for Advanced Custom Fields: 0.5.3
ACF: 5.12
```

### This is my field:
[![enter image description here][1]][1]

____
I created a sample post and selected "green" and "blue". This is what happens:

### Works correctly when I choose "value" as Return Format:
[![enter image description here][2]][2]

### Works correctly when I choose "label" as Return Format:
[![enter image description here][3]][3]

### Throws error when I choose "Array (Both) as Return Format:
[![enter image description here][4]][4]

```graphql
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "path": [
        "posts",
        "nodes",
        0,
        "colors",
        "colors",
        0
      ]
    },
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "path": [
        "posts",
        "nodes",
        0,
        "colors",
        "colors",
        1
      ]
    }
  ],
  "data": {
    "posts": {
      "nodes": [
        {
          "title": "Test",
          "colors": {
            "colors": [
              null,
              null
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

And this is the error explanation when I turn on the Debug mode:

```graphql
{
  "errors": [
    {
      "debugMessage": "Expected a value of type \"String\" but received: {\"value\":\"g1\",\"label\":\"Green\"}",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "path": [
        "posts",
        "nodes",
        0,
        "colors",
        "colors",
        0
      ]
    },
    {
      "debugMessage": "Expected a value of type \"String\" but received: {\"value\":\"b1\",\"label\":\"Blue\"}",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "path": [
        "posts",
        "nodes",
        0,
        "colors",
        "colors",
        1
      ]
    }
  ],
  "data": {
    "posts": {
      "nodes": [
        {
          "title": "Test",
          "colors": {
            "colors": [
              null,
              null
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": []
  }
}
```

How can I fix this?
(also on [StackExchange](https://wordpress.stackexchange.com/questions/404473/acf-select-field-cant-return-array-when-multiple-items-are-selected))

  [1]: https://i.stack.imgur.com/v6dJw.png
  [2]: https://i.stack.imgur.com/Ms9UP.png
  [3]: https://i.stack.imgur.com/vS3xV.png
  [4]: https://i.stack.imgur.com/pxZvR.png

**Comment by metawise** [comment]
I'm facing a similar issue. Did you find any solutions yet?

**Comment by ShahriarKh** [comment]
> I'm facing a similar issue. Did you find any solutions yet?

Nope 😕. I'm handling it in frontend.

**Comment by marco910** [comment]
I'm also facing the same issue

**Comment by mkosak** [comment]
The same for me. Did anyone found any workaround?

**Comment by 2xSamurai** [comment]
+1 for this issue. I'm also facing it.

**Comment by jasonbahl** [comment]
This has been [resolved](https://github.com/wp-graphql/wpgraphql-acf/pull/62) in the new version of WPGraphQL for ACF being re-architected here: https://github.com/wp-graphql/wpgraphql-acf


That version of the plugin is what we'll be supporting going forward. 

It's a complete rewrite of the plugin and will be moving from beta to stable in the near future. 

We recommend making the switch sooner than later. A formal upgrade guide and docs will be out soon!

**Comment by jasonbahl** [comment]
Ah, perhaps I mis-spoke about this being resolved fully in the new version? 

We do have this open issue on the new repo as well, which seems to relate to this: https://github.com/wp-graphql/wpgraphql-acf/issues/105
