### ISSUE TITLE
Enable formatting for oembed field

### ISSUE THREAD

**Issue by palmjack** [wp-graphql/wp-graphql-acf#320]
https://github.com/wp-graphql/wp-graphql-acf/blob/365951c16c4f3a9ccc63cfbf462f005005bf2949/src/class-config.php#L436

I think adding the code below would make more sense than returning just the value. This way it can return the entire iframe instead of just the link. 
If you use `oembed_dataparse` filter in your theme you can return the modified code that suits your css framework
`if ( 'oembed' === $acf_field['type'] ) {
  $format = true;
}`

**Comment by TamirHen** [comment]
Major upvote on this one
@palmjack thanks for the easy solution!

**Comment by jeffceriello** [comment]
Does this work with subfields? It doesn't look like it does.  have a field that shows correctly the <iframe> but the subfield shows the url of the oembed.

**Comment by jasonbahl** [comment]
👋🏻 hello, we're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf

I've created an issue to track this in the new version of the plugin: https://github.com/wp-graphql/wpgraphql-acf/issues/106

This repo will be archived in the not-too-distant future in favor of the new version, which will be released on WordPress.org an marked stable shortly. 

Closing this issue in favor of the issue on the new repo (fwiw, I have a PR in progress for it as well)
