### ISSUE TITLE
Union type Page_AcfBottomCardBlock_SlidingCards must define one or more member types

### ISSUE THREAD

**Issue by binarystarr** [wp-graphql/wp-graphql-acf#322]
When i open the graphiql ide i get a number of error messages in the query output similar to the one above.

Googling hasnt helped so i wondered if there was something obvious i have missed?

Can anyone explain how I might solve this issue?

**Comment by jasonbahl** [comment]
@binarystarr obviously I'm waaaaay late replying here, but I think one of the best ways to get help on an issue like this would be to provide more information. Possibly a JSON export of the Field Group(s) you have configured and the query(s) you've tried. 

I would also recommend checking out the GraphiQL IDE and searching for the ACF Field Groups you have set to show in GraphQL to see what fields and GraphQL Types are generated. 

I'm assuming you've either resolved your issues or moved on, so I will close this issue now, but if you're still having issues, please open a new issue with a bit more details so someone looking to help can be more informed about your situation and what you're trying to accomplish. 

Thanks! 🙏🏻
