### ISSUE TITLE
Get field type in response

### ISSUE THREAD

**Issue by MercerMorning** [wp-graphql/wp-graphql-acf#330]
Hello! Does it has an opportunity to show field type of custom field in graphQL response. Maybe someone give me a hint about wp filter?

**Comment by TinoKlein-crsd** [comment]
> Hello! Does it has an opportunity to show field type of custom field in graphQL response. Maybe someone give me a hint about wp filter?

# +1

**Comment by jasonbahl** [comment]
If I understand the question correctly, you want to be able to know more about the ACF Field from within the resolver for the field? 

If that's correct, this might be the filter you're looking for: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-config.php#L469

This plugin is being actively re-written over here: https://github.com/wp-graphql/wpgraphql-acf and the new version will be released to WordPress.org and this version will be archived in the not-too-distant future. 

This filter in the new codebase is located here: https://github.com/wp-graphql/wpgraphql-acf/blob/6a9360506d51b13b7cc6c91b1ca9f547b96e0f0f/src/FieldConfig.php#L389

I'm going to close this, as I believe this is the filter you're looking for.
