### ISSUE TITLE
Possible to set graphql_field_name option in GUI?

### ISSUE THREAD

**Issue by jackgregory** [wp-graphql/wp-graphql-acf#332]
I have a few of fields which field names start with a number, but this throws an error `"The field '1280720' on Type 'Project_Afcprojectsettings_FeaturedGfxList_Src' is invalid. Field names cannot start with a number."`

When registering with php or json I can set graphql_field_name to avoid this error. But cant do this with the admin fields. Could it be added as an option?

**Comment by jasonbahl** [comment]
@jackgregory this has been added to the re-write of the plugin being worked on over here: https://github.com/wp-graphql/wpgraphql-acf. 

When using the new WPGraphQL for ACF + ACF 6.1+ each field now has a "GraphQL" tab where you can set things like this on a per-field basis:

![CleanShot 2023-07-11 at 21 51 10](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/038420d0-d1a3-4b99-9680-64d43a60f98f)

I'm closing this issue as it is now supported in the new version (which will be released on WordPress.org in the near future and this repo for the old version of the plugin will be archived)
