### ISSUE TITLE
Getting url of Image field, when Rules are set to "Show this filed group if [Block] is equal to [My Custom Block]"

### ISSUE THREAD

**Issue by jjung830** [wp-graphql/wp-graphql-acf#339]
I created a ACF custom block with image field (not for Post in Custom Fields Settings), 
and in GraphiQL I cannot find the image url...

ACF field group
![Screen Shot 2022-09-27 at 1 39 39 PM](https://user-images.githubusercontent.com/89928702/192598284-1b2563d3-0662-4373-98e4-d6ee043378e6.png)

GraphiQL result
<img width="1130" alt="Screen Shot 2022-09-27 at 1 51 59 PM" src="https://user-images.githubusercontent.com/89928702/192600480-442911c0-3014-4f94-bed8-fa5a87b99945.png">
I only get the image number, not the url... (in this case, 37)

Is there any way I can get the image url?

**Comment by sunilsingh2019** [comment]
Hi I am also the same situation, if you get any solution please let me know.
![image](https://user-images.githubusercontent.com/26164995/205461985-06732a0d-c515-4ab4-bf1a-f5c6a3ff2e7e.png)

**Comment by jasonbahl** [comment]
@jjung830 @sunilsingh2019 unfortunately this plugin doesn't support ACF Blocks as a location type. 

However, we are re-building WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf and that new version of the plugin DOES support Blocks as a location type. (you also need WP Engine's [WPGraphQL Content Blocks](https://github.com/wpengine/wp-graphql-content-blocks) plugin for it to work). 

You can read more about the block support here: https://github.com/wp-graphql/wpgraphql-acf/pull/81#issue-1874412897
