### ISSUE TITLE
Feature request: Checkboxes return value and label

### ISSUE THREAD

**Issue by aleeceburgess** [wp-graphql/wp-graphql-acf#341]
This is identical to #44 but checkboxes (or return multiple values).

<img width="1014" alt="checkboxes-return" src="https://user-images.githubusercontent.com/19706168/194987514-3a3cb5b2-19cd-420a-8a85-0c3ef28810fb.png">

Solutions I've tried:
- The snippet included in #44 
- Modifying above snippet
- Select field returning multiple selections
- A select within a repeater

I feel all options are expecting to return one selection `[value, label]` instead of multiple`{[value, label], [value, label]} `

Happy to privately share an endpoint if necessary 😄 

Thanks

**Comment by jasonbahl** [comment]
@aleeceburgess thanks for the issue! 

We're re-building the plugin over here: https://github.com/wp-graphql/wpgraphql-acf

We have an open issue to consider this change here: https://github.com/wp-graphql/wpgraphql-acf/issues/105

I'm going to close this issue as we'll be tracking it over on the new repo and will be archiving this repo in the not-too-distant future.
