### ISSUE TITLE
Inputs not showing in mutation on registerUser or createUser

### ISSUE THREAD

**Issue by michaelgrossklos** [wp-graphql/wp-graphql-acf#342]
Hello,
I am using a headless Wordpress with ACF (Version 6.0.3), ACF Extended (Version 0.8.8.10), WP-GraphQL (Version 1.12.0) and WPGraphQL for Advanced Custom Fields (Version 0.5.3) installed. 

In ACF I created a field group with some fields and set the condition to `User Role == All`. The Goal is to add some fields to the regular WP-User and register a user including those fields.

When I now want to use the GraphQL-IDE to click together a mutation to register a new user, the ACF fields I created aren't there as inputs. So I can't register a user using those fields. I wonder if I've done anything wrong.

Under `registerUser` or `createUser` I can find a node `user` and under that I can find the field group I have created. But not as inputs.

Here are some screenshots:
[ACF field group](https://i.stack.imgur.com/8BnZq.png)

[GraphQL Settings](https://i.stack.imgur.com/60H6F.png)

[GraphQL-IDE Query Composer](https://i.stack.imgur.com/RFSig.png)

**Comment by jasonbahl** [comment]
WPGraphQL for ACF doesn't support mutations at this time. 

We're waiting for the GraphQL Spec to make a decision on the `oneOf` directive before formally supporting ACF Field Group mutations. 

There are community extensions that do offer support, if you want to give it a try: https://github.com/zngly/wp-graphql-acf-mutations

I cannot vouch for the plugin as I've not tried it, but it seems like it supports mutations for several ACF Field Types.
