### ISSUE TITLE
No data resolved in page link fields when using internal link

### ISSUE THREAD

**Issue by maurocolella** [wp-graphql/wp-graphql-acf#343]
Hi.

With 
- ACF Pro Version 5.9.5
- WP GraphQL Version 1.10.0
- WP GraphQL for ACF Version 0.6.1, previously 0.5.2 

We're seeing an issue where the page link component when using internal links doesn't return anything through GraphQL.

The value exists in storage, and resolution appears to work _in part_, but fails halfway through.

It used to work. In fairness, we have a fairly complex setup, but I tried stripping it down to near-barebones WordPress, and was able to reproduce the issue.

We're using PHP 7.4.

**Comment by maurocolella** [comment]
Actually, [L746 here](https://github.com/wp-graphql/wp-graphql-acf/blob/develop/src/class-config.php#L746), this check verifies values of types `array` and `int` (post ID), but if the ACF field is a `page_link`, the value can also be null or a string when referencing an archive page.

Hence. This will resolve correctly for simple post types, but it won't return properly for strings.

```
$value = $this->get_acf_field_value( $root, $acf_field );

$return = [];
if ( ! empty( $value ) ) {
	if ( is_array( $value ) ) {
		foreach ( $value as $id ) {
			$post = get_post( $id );
			if ( ! empty( $post ) ) {
				$return[] = new Post( $post );
			}
		}
	} else {
		$post = get_post( absint( $value ) );
		if ( ! empty( $post ) ) {
			$return[] = new Post( $post );
		}
	}
}
```

**Comment by jasonbahl** [comment]
@maurocolella 👋🏻 thanks for this issue. 

Apologies for the delayed response. 

We're working on re-building WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf

I believe this issue has been resolved in the new version of the plugin, but if you believe this is still a bug in that version of the plugin, please open a new issue on that repo. 

I'm going to close this issue as we'll be archiving this repo in the not-too-distant future, and I _believe_ this issue has been resolved in the new version. 

🙏🏻
