### ISSUE TITLE
Feature request: Open Streetmap field data

### ISSUE THREAD

**Issue by erikhartin** [wp-graphql/wp-graphql-acf#349]
[This excellent plugin](https://github.com/mcguffin/acf-openstreetmap-field) adds an Open Streetmap field to ACF. However it's impossible to query it using wp-graphql-acf.

Any chance of implementing support for it here?

**Comment by jasonbahl** [comment]
@erikhartin we're working on a new version of WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. 

The new version has an API for adding support for third party ACF Field Types. 

In fact, the plugin comes with support for [ACF Extended](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/AcfExtended.php) Field Types and you can use them as a model for adding support for additional ACF Field Types such as the Open Streetmap field type. 

For example: 

- [ACFE Advanced Link](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeAdvancedLink.php)
- [ACFE Countries](https://github.com/wp-graphql/wpgraphql-acf/blob/main/src/ThirdParty/AcfExtended/FieldType/AcfeCountries.php)


While we won't be supporting all ACF Field Type extensions out of the box, but we will be supporting the APIs for developers to add their own custom ACF Field Types more easily. 

We'd recommend checking out the new version of WPGraphQL for ACF as it's what we'll be supporting going forward. It wil have a stable release on WordPress.org in the near future and this version will be archived.
