### ISSUE TITLE
GraphiQL IDE keeps loading when GraphQL ACF plugin is active

### ISSUE THREAD

**Issue by diceboi** [wp-graphql/wp-graphql-acf#350]
I have a problem, when Im activating the GraphQL ACF plugin in a wordpress site, and goes into the GraphiQL IDE, it keeps loading, and nothing happens. I dont know its a bug in the plugin or my wordpress, but the plugin causes it. Any ideas?

**Comment by px-wernerglinka** [comment]
I have the same issue, but in my case, a CPT causes it.

**Comment by jasonbahl** [comment]
@diceboi we'd need more information to be able to help here. 

Is there an issue with ONLY WPGraphQL and WPGraphQL for ACF active? 

I'd recommend checking out this page to see if you can find any tips on debugging and getting more information from the network tab, etc: https://www.wpgraphql.com/docs/debugging

If you're able to provide complete steps to reproduce, open a new issue with more details so we can investigate further. 

Also, we'd recommend checking out the new version of this plugin being worked on here: https://github.com/wp-graphql/wpgraphql-acf. It's the version we'll be supporting going forward.

**Comment by diceboi** [comment]
> @diceboi we'd need more information to be able to help here.
> 
> Is there an issue with ONLY WPGraphQL and WPGraphQL for ACF active?
> 
> I'd recommend checking out this page to see if you can find any tips on debugging and getting more information from the network tab, etc: https://www.wpgraphql.com/docs/debugging
> 
> If you're able to provide complete steps to reproduce, open a new issue with more details so we can investigate further.
> 
> Also, we'd recommend checking out the new version of this plugin being worked on here: https://github.com/wp-graphql/wpgraphql-acf. It's the version we'll be supporting going forward.

When I started with a fresh wordpress installation, the problem goes away, and I can't reproduce the issue again. If it happens again, I'll let you know. Thanks for the answer!
