### ISSUE TITLE
ACF Label Value

### ISSUE THREAD

**Issue by jT2a** [wp-graphql/wp-graphql-acf#354]
How do you get the Label and Value for the ACF Field via GraphQL query?

Something like this

```
query my_query {
	id
	title
	acfFields {
		someAcfField {
			label
			value
		}
		anotherAcfField {
			label
			value
		}
	}
}
```

**Comment by jasonbahl** [comment]
@jT2a what field type(s) do you envision this working for? 

We're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf and we have an open issue for "Choice Fields" to return the label and value. See: https://github.com/wp-graphql/wpgraphql-acf/issues/105

I'm going to close this issue as we'll be archiving this repo in the not-too-distant future in favor of the new version of the plugin. 

If that issue satisfies your needs, maybe leave a comment over there. If it doesn't consider making a new issue on that repo explaining more about what you want and your use cases, why it would be valuable, etc.
