### ISSUE TITLE
Multiple Post Object Products not pulling through

### ISSUE THREAD

**Issue by Steppio** [wp-graphql/wp-graphql-acf#356]
**Full error message**

_Abstract type Collection_Collectionsdata_SingleProduct must resolve to an Object type at runtime for field Collection_Collectionsdata.singleProduct with value \"instance of WPGraphQL\\Model\\Post\", received \"Product\". Either the Collection_Collectionsdata_SingleProduct type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function._

**Issue**

I am able to create a Post Object / Relationship field (‘Featured Product’ for example) and attach this to a custom taxonomy (‘Collections’ for example).

I can then go into the custom Collections taxonomy and save a Featured Product belonging to this collection.

This works well and pulls through on the Wordpress GraphQL IDE

![Screenshot 2023-05-01 at 17 24 02](https://user-images.githubusercontent.com/5756973/235686936-e302452e-90f1-40b9-ba17-450bfa60bacd.png)
![Screenshot 2023-05-01 at 17 27 07](https://user-images.githubusercontent.com/5756973/235687040-34b4ab95-c02c-4ab7-8d7e-da64f2b22d37.png)

However the issue occurs when I try to change this Post Object field to accept multiple values (using the ‘Select multiple values’ switch). 
I make this change, save the changes in ACF and then add an additional product to the Featured Product field, and run the same query again:

![Screenshot 2023-05-01 at 17 32 45](https://user-images.githubusercontent.com/5756973/235687201-2895128d-2b0c-45e9-8190-41710c6f4b8e.png)
![Screenshot 2023-05-01 at 17 31 50](https://user-images.githubusercontent.com/5756973/235687388-08c91289-04cb-4180-986b-e07d9d0e8cf1.png)

If I change the ‘Filter by Post Type’ to Post it works with multiple values, however I cannot seem to attach multiple Products to the post type. It always returns that same error 

_Abstract type Collection_Collectionsdata_SingleProduct must resolve to an Object type at runtime for field Collection_Collectionsdata.singleProduct with value \"instance of WPGraphQL\\Model\\Post\", received \"Product\". Either the Collection_Collectionsdata_SingleProduct type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function._

Absolutely any help would be appreciated as this has become quite a big issue now.

**Steps to replicate**

I’ve created a blank WP instance, installed WooCommerce (v7.6.1) and created two dummy products.

I install the following Gatsby-related / GraphQL plugins:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-3ca0345b-7fff-558e-9c42-6fc6b0d3a276"><div dir="ltr" style="margin-left:0pt;" align="left">

Name | Version
-- | --
WP Gatsby | 2.3.3
WPGraphQL | 1.14.3
WPGraphQL for ACF | 0.6.1
WooGraphQL | 0.12.0 (later versions create app.js errors)

</div></b>

I install Advanced Custom Fields (v6.1.4) and Custom Post Type UI (v1.13.5) 

I create a taxonomy called Collections, attach it to the Product Post type and enable it in GraphQL

![Screenshot 2023-05-01 at 17 55 55](https://user-images.githubusercontent.com/5756973/235687967-9ef9ab6e-d120-4ceb-bed4-dcd54399a4f0.png)
![Screenshot 2023-05-01 at 18 01 44](https://user-images.githubusercontent.com/5756973/235688077-18e5a6df-bcea-4577-861e-6b4ddd212c2c.png)

I then create a single ACF Post Object field group called ‘Featured Product’ and attach it to the taxonomy and filter by Post Type of ‘Product’:

![Screenshot 2023-05-01 at 18 03 17](https://user-images.githubusercontent.com/5756973/235688343-aef7a64d-366d-435d-83de-d4578100282a.png)
![Screenshot 2023-05-01 at 18 03 23](https://user-images.githubusercontent.com/5756973/235688432-e929daa3-6f46-484c-9167-6f8b67a66cba.png)
![Screenshot 2023-05-01 at 18 08 00](https://user-images.githubusercontent.com/5756973/235688524-7bdbabd2-0a57-4a4e-99b5-a741bc71b379.png)

I then go into my Taxonomy and create a new Collection and add a single Featured Product and save it.

![Screenshot 2023-05-01 at 18 11 50](https://user-images.githubusercontent.com/5756973/235688751-b03f7ec6-1fb7-428d-b7f2-4b56884615a2.png)
![Screenshot 2023-05-01 at 18 11 27](https://user-images.githubusercontent.com/5756973/235688781-4371223a-8166-4c30-86d7-d741713b54e1.png)

I now change this ACF Post Object to ‘Select multiple values’ and add an additional product to the taxonomy Featured Product:

![Screenshot 2023-05-01 at 18 13 06](https://user-images.githubusercontent.com/5756973/235688953-cff76997-0627-4acf-a6ae-78ab74ad5105.png)

And this produces the exact same error:

![Screenshot 2023-05-01 at 18 15 11](https://user-images.githubusercontent.com/5756973/235688992-186b05c9-a01d-447e-9ba4-3d10bd7d7475.png)

**Expected Result**

I hoped for WpGraphQL to pull through

**Things I’ve tried**

I’ve tried changing the PHP version from 8 to 7.4 (this has fixed something else regarding mediaItems query issues for me in the past)

I’ve tried using different versions of the WPGatsby / WpGraphQL / WooGraphQL plugins - it seems to be the same whatever I try

I’ve tried using a Relationship field instead - same issue

I’m at a bit of a loss here so any help would be greatly appreciated!

**Comment by Steppio** [comment]
Due to time constraints I've had to think of a workaround this using Algolia

Any help in the future in regard to this would be greatly appreciated as it costs alot of extra money to use the Algolia method

**Comment by jasonbahl** [comment]
Hello, this version of WPGraphQL for ACF has many known conflicts with WPGraphQL for WooCommerce. 

We believe many of those conflicts have been resolved in the new version of WPGraphQL for ACF being worked on over here: https://github.com/wp-graphql/wpgraphql-acf. 

The new version is what we'll be supporting going forward and this repo will be archived in the not-too-distant future. 

If you find the same issue exists in the new version, please open a new issue on that repo with steps to reproduce. 


From what I can tell, this IS supported in the new version. 

Following your steps to reproduce, I was able to query the data: 

![CleanShot 2023-07-07 at 16 17 33](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/b08990fb-4d15-4290-95c6-4f125f98e31e)


Attached is the Field Group export that I used: 

[acf-export-2023-07-07 (2).json.zip](https://github.com/wp-graphql/wp-graphql-acf/files/11986563/acf-export-2023-07-07.2.json.zip)

And the plugin versions I'm running:

- ACF PRO 6.1.7
- WooCommerce  7.8.2
- WPGraphQL 1.14.6
- WPGraphQL for ACF 2.0.0-beta.3.1.0 (https://github.com/wp-graphql/wpgraphql-acf)
