### ISSUE TITLE
ACF custom post type and custom taxonomy

### ISSUE THREAD

**Issue by MoeinMirkiani** [wp-graphql/wp-graphql-acf#361]
As might already know, ACF can create custom post types and taxonomies now.
I was wondering if you have any plans to add GraphQL support for these features any time soon.

**Comment by jasonbahl** [comment]
Hello, this is supported in the new version of WPGraphQL for ACF being worked on over here: https://github.com/wp-graphql/wpgraphql-acf

This repo we're on now will be archived in the not-too-distant future in favor of the new plugin which is a complete re-architecture. 

Docs and upgrade guide coming soon, but we recommend using the new version as it's solved a lot of problems in this version and is what we'll be supporting going forward 🙏🏻
