### ISSUE TITLE
Querying for a custom post type by one of it's ACF field values

### ISSUE THREAD

**Issue by ewaninfo** [wp-graphql/wp-graphql-acf#363]
I've been following this article https://www.wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument.

The new where arguments have been registered, but the query always returns an empty array.

```
   add_action('graphql_register_types', function (){
    register_graphql_field('RootQueryToAdvertisementConnectionWhereArgs', 'tagId', [
        'type' => 'Int',
        'description' => __('Filter Advertisements by tag ID.', 'your-textdomain'),
    ]);

    register_graphql_field('RootQueryToAdvertisementConnectionWhereArgs', 'postId', [
        'type' => 'Int',
        'description' => __('Filter Advertisements by post ID.', 'your-textdomain'),
    ]);
    });
```

```
    add_filter('graphql_post_object_connection_query_args', function ($query_args, $source, $args, $context, $info) {
    // Filter by tag ID
    if (isset($args['where']['tagId'])) {
        $query_args['meta_query'][] = [
            'key' => 'tags',
            'value' => (int) $args['where']['tagId'],
            'compare' => 'IN'
        ];
    }

    // Filter by post ID
    if (isset($args['where']['postId'])) {
        $query_args['meta_query'][] = [
            'key' => 'posts',
            'value' => (int) $args['where']['postId'],
            'compare' => 'IN'
        ];
    }

    return $query_args;
    }, 10, 5);
```

Here is the query I'm trying to use:

```
query getAds {
  advertisements(where: {postId: 9260}) {
    nodes {
      title
      content
      advertisementsSettings {
        advertisementsDisplayOptions {
          posts {
            ... on HealthPost {
              slug
              databaseId
            }
          }
          tags {
            name
            slug
            databaseId
          }
        }
        advertisementsLocationOptions
      }
    }
  }
}
```

The posts field is a 'post object' field and the tags field is a 'taxonomy' field. Both allow multiple values to be selected.

Any suggestions would be great thanks.

**Comment by jasonbahl** [comment]
@ewaninfo I would recommend starting with a WP_Query that does what you want, then work backward from there. 

If you're able to execute a WP_Query and get the data you're expecting, then you _should_ be able to better map the WPGraphQL inputs to that WP_Query. 

I have a feeling your filter that modifies the `$query_args['meta_query']` is possibly not translating to a functional WP_Query?

I'm going to close this as I don't believe this is an issue with the plugin but more a question on documentation and how to properly filter things. 

For discussions like this, I'd recommend joining the [WPGraphQL Slack](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA) or the [HeadlessWP Discord](https://developers.wpengine.com/discord). 

If you're able to confirm that there's an actual issue with WPGraphQL for ACF, feel free to open another issue with steps to reproduce. 

----

Also, FYI, we're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf and will be archiving this repo in the not-too-distant future.

**Comment by ewaninfo** [comment]
@jasonbahl thanks for your response. I ended up using a combination of your Tax Query and Meta Query plugins.
