### ISSUE TITLE
Fetching Data from User Relationship Field Returns Null

### ISSUE THREAD

**Issue by ccohan-eg** [wp-graphql/wp-graphql-acf#364]
Hi @jasonbahl ,

I have a custom post type I am working with a number of registered custom fields associated to it. Currently, I am trying to build out a feature which is to pretty much display a secondary author on the frontend. That said, I've added the user field to the custom post type, populated it with some test user. Upon trying to query the custom post type and fetching the set of fields associated with the user, no matter what I do the result is null.

Here's my query:
```
query GetNodeByUri($uri: String = "/custom_guides/testing-coauthor") {
    nodeByUri(uri: $uri) {
      __typename
      ... on Guide {
        id
        content
        date
        guideId
        title
        uri
        modified
        lastEditedBy {
          node {
            name
          }
        }
        categories {
          nodes {
            name
            slug
            uri
            parent {
              node {
                name
                slug
                uri
              }
            }
          }
        }
        tags {
          nodes {
            name
            slug
          }
        }
        featuredImage {
          node {
            mediaItemUrl
            altText
          }
        }
        author {
          node {
            description
            name
            avatar {
              url
            }
            authorCustomFields {
              authorDiscordLink
              authorTwitchLink
              authorTwitterLink
            }
          }
        }
        customGuideFields {
          guideLargeBackgroundImage {
            mediaItemUrl
          }
          listGuideIcons {
            guideIcon
          }
          guideCoauthor {
            name
            avatar {
              url
            }
            authorCustomFields {
              authorDiscordLink
              authorTwitchLink
              authorTwitterLink
            }
          }
          guideTagline
        }
      }
    }
  }
```

Here's the result w/ respect to what gets returned: 

```
{
  "data": {
    "nodeByUri": {
      "__typename": "Guide",
      "id": "cG9zdDoyMjIw",
      "content": "here is some test content here is some test content here is some test content",
      "date": "2023-07-26T13:25:43",
      "guideId": 2220,
      "title": "Here is some test content",
      "uri": "/custom_guides/here-is-some-test-content/",
      "modified": "2023-07-28T16:34:43",
      "lastEditedBy": {
        "node": {
          "name": "admin.developer"
        }
      },
      "categories": {
        "nodes": [
          {
            "name": "Barbarian",
            "slug": "barbarian",
            "uri": "/category/d4/barbarian/",
            "parent": {
              "node": {
                "name": "Diablo IV",
                "slug": "d4",
                "uri": "/category/d4/"
              }
            }
          },
          {
            "name": "Diablo IV",
            "slug": "d4",
            "uri": "/category/d4/",
            "parent": null
          }
        ]
      },
      "tags": {
        "nodes": []
      },
      "featuredImage": {
        "node": {
          "mediaItemUrl": "https://wp-staging.icy-veins.com/wp-content/uploads/2023/05/Necromancer-LP-BG.jpg",
          "altText": "Necromancer LP BG"
        }
      },
      "author": {
        "node": {
          "description": null,
          "name": "Author Test",
          "avatar": {
            "url": "https://secure.gravatar.com/avatar/95648369d1b6389bcb7be20db4cc383c?s=96&d=mm&r=g"
          },
          "authorCustomFields": {
            "authorDiscordLink": null,
            "authorTwitchLink": null,
            "authorTwitterLink": null
          }
        }
      },
      "customGuideFields": {
        "guideLargeBackgroundImage": {
          "mediaItemUrl": "https://wp-staging.icy-veins.com/wp-content/uploads/2023/05/1920x1080_Kehjistan_png_jpgcopy.jpg"
        },
        "listGuideIcons": null,
        "guidecoauthor": null,
        "guideTagline": "Testing tagline here"
      }
    }
  }
}
```
The **guideCoauthor ** within the customGuideFields is null, no matter what object is queried. Other custom fields like the **guideLargeBackgroundImage** (which is an image field), returns the associated URL needed. 

Any advice would be great, am I doing something wrong with how I'm querying this field, or is this just a bug as per some updates done on ACF's side?

**Comment by jasonbahl** [comment]
@ccohan-eg 👋🏻 my guess is that this is related to the WPGraphQL Model Layer. 

Users are not public entities in WordPress by default. Only users with published content of a public post type are considered public. 

My guess is that the users you are adding as connections are not public and therefore returning null. 

You could filter the WPGraphQL Model Layer to make all users public, like so: https://www.wpgraphql.com/recipes/make-all-users-public

Or possibly instead of using Users you could use another Custom Post Type to represent authors?

I believe this is working as intended, but since you want to show non-public users publicly, you'd need to modify that behavior for your site.

**Comment by jasonbahl** [comment]
FYI, we're re-building this plugin over here: https://github.com/wp-graphql/wpgraphql-acf and we'll be archiving this repo in the not-too-distant future

**Comment by ccohan-eg** [comment]
Thanks for the follow-up @jasonbahl - appreciate you and your hard work on this plugin. For what it's worth a workaround was discovered by using JWT authentication to have a generic admin user be authenticated in prior to submitting the query. Your mention of public versus private data as far as the user schema goes makes sense. Thanks again, and take care!
