### ISSUE TITLE
Get all the ACF fields object

### ISSUE THREAD

**Issue by ravisinghnath** [wp-graphql/wp-graphql-acf#365]
I am using **WPGraphQL** and **WPGraphQL for Advanced Custom Fields**

I want to create a post from the front end using a UI form. I need all the ACF field/input objects attached to a custom post type.

Does anyone have any idea? Thanks

**Comment by jasonbahl** [comment]
@ravisinghnath I like this idea, but it's not something we plan to support in this plugin. 

You could potentially use existing WPGraphQL APIs such as [register_graphql_object_type](https://www.wpgraphql.com/functions/register_graphql_object_type), [register_graphql_interface_type](https://www.wpgraphql.com/functions/register_graphql_interface_type), [register_graphql_field](https://www.wpgraphql.com/functions/register_graphql_field) to build a plugin that could provide the schema with this kind of data.
