### ISSUE TITLE
Empty response when content includes non-allowed HTML tag

### ISSUE THREAD

**Issue by abstractvector** [wp-graphql/wp-graphql-acf#367]
### Description

I am using Advanced Custom Fields and have an HTML field. The field contains HTML imported from another platform, and in some cases includes `<u>` tags, not allowed in Wordpress.

Using the REST API, I can query a post with such a field and the `<u>` tag is stripped from the response. When using the GraphQL API, I get a completely empty response back (no JSON whatsoever, body length of zero) but an `HTTP 200 OK` response status code.

### Steps to reproduce

Add some content including a `<u>` tag to an HTML-supporting ACF field in WordPress. Attempt to query it via the GraphQL API and see that an empty response is returned.

### Additional context

I believe the correct behavior should emulate the REST API - i.e. return a sanitized response with non-allowed tags stripped out.

While obviously I can sanitize the data on the import (and will be doing as a workaround), this doesn't stop an editor manually adding the tag back in.

### WPGraphQL Version

1.14.10

### WordPress Version

6.3

### PHP Version

7.4.33

### Additional enviornment details

Hosted on Wordpress.com

WPGraphQL for Advanced Custom Fields v0.6.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
I'm unable to reproduce this. 

I've tried with:

- WPGraphQL v1.18.0 
- WPGraphQL for ACF v0.6.1 and WPGraphQL for ACF v2.0.0-beta.5.1.0


I have an ACF Field Group that has all the ACF fields available. 

I've entered HTML into the Text field, Textarea field and WYSIWYG fields.

![CleanShot 2023-11-07 at 13 42 59](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/e01b3e8e-f9e7-4e3b-8d8a-c91c3970aa74)

I can successfully query for the fields and see the `<u>` tag returned without being stripped: 

### v0.6.1

I get a response with the expected data, including the "invalid" `<u>` tag

![CleanShot 2023-11-07 at 13 37 53](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/c1efbbc6-71c2-4ee5-bb77-09081d024802)

### v2.0.0-beta.5.1.0

I get a response with the expected data, including the "invalid" `<u>` tag

![CleanShot 2023-11-07 at 13 39 16](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/9939ea6c-ac91-4bae-9ce2-164ba1c80615)

----

I'm inclined to believe that something else is causing the issue. Another plugin perhaps? 

If you're able to reproduce this consistently with _just_ WPGraphQL and WPGraphQL for ACF (preferably the new version being worked on over here: https://github.com/wp-graphql/wpgraphql-acf) then open a new issue on that repo with added details and we can look again.

**Comment by jasonbahl** [comment]
@abstractvector I also tested the WP REST API, and I see the `<u>` tags in the response for the ACF Field Group as well: 

![CleanShot 2023-11-07 at 13 47 26](https://github.com/wp-graphql/wp-graphql-acf/assets/1260765/5c618e3f-ea95-4d2b-8293-aaef461e0260)

I believe there's some other code somewhere else (custom plugin, theme, mu-plugin) that's causing a problem.
