### ISSUE TITLE
ACF fields is not showing in graphiql IDE

### ISSUE THREAD

**Issue by ferdausalom** [wp-graphql/wp-graphql-acf#372]
ACF fields is not showing in graphiql IDE, even "Show in Graphql" setting selected.

**Comment by josephfusco** [comment]
Hey @ferdausalom, can you please provide more details with your situation?

- wpgraphql version
- wp-graphql-acf version
- acf version

If you could please provide instructions on how to reproduce the issue, such as if this is a custom post type, that would be helpful!

**Comment by ferdausalom** [comment]
WPGraphQL V: 1.19.0, 
WPGraphQL for Advanced Custom Fields V: 0.6.1, 
WordPress V: 6.4.2  
ACF V: 6.2.4

Location rules for the ACF, added in Create and Edit User

**Comment by josephfusco** [comment]
Thanks!

Check out https://github.com/wp-graphql/wp-graphql-acf?tab=readme-ov-file#location-rules-
You might have to manually map your ACF field group to the GraphQL schema.

I would recommend checking out the [re-architected ACF for WPGraphQL plugin](https://github.com/wp-graphql/wpgraphql-acf).

**Comment by jasonbahl** [comment]
@ferdausalom As @josephfusco mentioned, I would recommend checking out the new version of the plugin and if you experience any issues with it, please open an issue on the new repo: https://github.com/wp-graphql/wpgraphql-acf

Thanks!
