### ISSUE TITLE
GraphQL not working when defining sub options page

### ISSUE THREAD

**Issue by omriluz** [wp-graphql/wp-graphql-acf#373]
When using the function from ACF `acf_add_options_sub_page`, the type that is related to that ACF options sub page is not being exposed to WPGraphQL, When using regular ACF options page everything works fine

im using  `php 8.1`, ` WPGraphQL 2.0.0-beta.6.0.0` (im using this since it kinda works for other issues, tried other versions as well),  `wordpress 6.3.2`

```php
acf_add_options_sub_page(array(
                'page_title' => __('Settings page', 'domain'),
                'menu_title' => __('Settings page', 'domain'),
                'menu_slug' => 'customer-service-settings',
                'icon_url' => 'dashicons-text',
));
```

Any help would be appriciated,

**Comment by josephfusco** [comment]
Try adding `show_in_graphql => true`

In the meantime, we are recommending folks start using the new [re-architected ACF for WPGraphQL](https://github.com/wp-graphql/wpgraphql-acf).

**Comment by omriluz** [comment]
@josephfusco Thanks Joseph! I will try your suggestions and come back tomorrow to this thread to report what happened

**Comment by jasonbahl** [comment]
👋🏻 I'm going to close this due to inactivity. 

As @josephfusco mentioned, the plugin has been re-built over here (https://github.com/wp-graphql/wpgraphql-acf). If this is an issue on the new version of the plugin, please open an issue on that repo with clear steps to reproduce. 

Thanks!
