### ISSUE TITLE
Query on Taxonomy gives error on graphql response

### ISSUE THREAD

**Issue by mude-albij** [wp-graphql/wp-graphql-acf#378]
So i using the below query for fetching category by taxonomy field from ACF inside a clone field within Flexible component
```
fragment LatestNews on LatestNewsLayout {
  latestNews{
    category{
      nodes{
        slug
      }
    }
  }
}
```
And then am prompted to be below shown error.
```
"errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "page",
        "template",
        "pageComponents",
        "pageComponents",
        5,
        "latestNews",
        "category"
      ]
    }
  ],
```

Steps to replicate
1. Create a `Page Components` Field with Flexible Layout
2. Create a `NewsLayout` Field and add `Category` field as taxonomy field 
3. Clone `NewsLayout` inside page Component Flexible Field
4. Use the following query

**Comment by josephfusco** [comment]
Hey @mude-albij, there is a new version of WPGraphQL for ACF out now that provides better support for clone fields. https://wordpress.org/plugins/wpgraphql-acf/

It's a complete re-architecture and solves a lot of issues. This repo will be archived in the not-too-distant future.

**Comment by jasonbahl** [comment]
@mude-albij I'm going to close this as I believe it's been resolved in the new version: https://wordpress.org/plugins/wpgraphql-acf/

**Comment by mude-albij** [comment]
yeah thanks it was resolved
