### ISSUE TITLE
Deprecated function "WPGraphQL\Data\DataSource::resolve_post_object"

### ISSUE THREAD

**Issue by sdegetaus** [wp-graphql/wp-graphql-acf#382]
Hello!

We started getting a thousand warnings once we went live. We believe this is the culprit:

![image](https://github.com/wp-graphql/wp-graphql-acf/assets/30123984/776f1332-589f-46c0-b3c7-a47d9cb66360)

Our website is in Spanish, so sorry about the "spanglish" 😁
```
User Deprecated: ¡La función WPGraphQL\Data\DataSource::resolve_post_object ha quedado obsoleta desde la versión 0.8.4! Usa Use $context->get_loader( 'post' )->load_deferred( $id ) instead. en su lugar.
```

Any chance of fixing this on the production version? 

Thanks for you help.

**Comment by jasonbahl** [comment]
@sdegetaus what version of WPGraphQL for ACF are you using? I would highly recommend updating to WPGraphQL for ACF v2.*+ when you can. This repo will be archived in the not-too-distant future. 

I will consider doing a minor release for this, but it has already been [publicly stated](https://github.com/wp-graphql/wp-graphql-acf?tab=readme-ov-file#wpgraphql-for-advanced-custom-fields) many times that this repo will no longer be supported long-term in favor of the re-built WPGraphQL for ACF v2.0+ which is available on GitHub (https://github.com/wp-graphql/wpgraphql-acf) and the WordPress.org repository: https://wordpress.org/plugins/wp-graphql/

**Comment by jasonbahl** [comment]
This was fixed and released in https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.6.2
