### ISSUE TITLE
User field returns empty UNLESS that user has authored a post

### ISSUE THREAD

**Issue by theleewise** [wp-graphql/wp-graphql-acf#385]
I noticed that whenever I selected some users, the data would show in the graphql query but whenever other users were selected then it wouldn't show the data. After check all different settings, roles, etc. between the users it appears the only difference is users that have authored posts.

I took a user that didn't have any authored posts and was not showing in my graphql query and change 1 article to be authored by them and then the query started working.

<img width="1013" alt="Screenshot 2024-05-17 at 2 31 49 PM" src="https://github.com/wp-graphql/wp-graphql-acf/assets/623632/18886524-ea54-431c-a75d-1e25adc7f0cd">

<img width="1036" alt="Screenshot 2024-05-17 at 2 32 41 PM" src="https://github.com/wp-graphql/wp-graphql-acf/assets/623632/50ac9b89-698d-42b7-bf15-5b5399714a25">

## ACF Setup
- A field group `articles` to display on all post type `Post`.
- Within is a Group field `reviewed`
- Within that is a User field `reviewer`

**Comment by jasonbahl** [comment]
@theleewise this is working as expected. 

Users in WordPress are not public unless they have authored something that is public. 

You can read more about this here: 

- https://www.wpgraphql.com/docs/users#sensitive-data 
- https://www.wpgraphql.com/docs/security#access-control-rights

If you want to expose users as public entities we have some examples of how to do this: 

- https://www.wpgraphql.com/recipes/make-all-users-public
- https://www.wpgraphql.com/2020/12/11/allowing-wpgraphql-to-show-unpublished-authors-in-user-queries
