### ISSUE TITLE
Cannot mutate relationship ACF field on userUpdate

### ISSUE THREAD

**Issue by roccopung** [wp-graphql/wp-graphql-acf#386]
Hi,

This is not really an issue for wp-graphql, but rather a general question if someone would like to help me figuring out :)

I am working on an app made with Sveltekit + Wordpress + wp-graphql-acf. Currently, each user with role "administrator", has a relationship field that looks like this:

```

    {
        "key": "group_6654931ec00c4",
        "title": "UserGroup",
        "fields": [
            {
                "key": "field_6654931f16eca",
                "label": "Luoghi Visitati",
                "name": "luoghi_visitati",
                "type": "relationship",
                "post_type": [
                    "luogo"
                ],               
                "filters": [
                    "search",
                    "post_type"
                ],
                "return_format": "object",
                "bidirectional": 0,
                "show_in_graphql": 1,
                "graphql_description": "",
                "graphql_field_name": "luoghiVisitati",
                "graphql_connection_type": "one_to_many",
                "bidirectional_target": []
            }
        ],
        "location": [
            [
                {
                    "param": "user_role",
                    "operator": "==",
                    "value": "administrator"
                }
            ]
        ],
        "show_in_graphql": 1,
        "graphql_field_name": "usergroup",
        "map_graphql_types_from_location_rules": 0,
        "graphql_types": ""
    }
]

```

The user can pick among the post type "luogo", and add as many as they want to the "luoghiVisitati" field. In the updateUser input options, there is nothing related to the luoghiVisitati field, therefore I tried to add it as an input in php. Currently my mutation looks like this:

```
mutation UpdateUserGroup {
  updateUser(input: {id: "idUser", luoghiVisitati: "titleLuogo"}) {
    user {
      usergroup {
        luoghiVisitati {
          nodes {
            ... on Luogo {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

It's not working, supposedly because I need to somehow bind my luoghiVisitati input with the custom post type "luogo"?

**Comment by josephfusco** [comment]
Hey @roccopung, this plugin as been rearchitected here https://github.com/wp-graphql/wpgraphql-acf and would recommend checking that out! It doesn't support mutations out of the box, but if you were to add support yourself, I'd recommend working against the new plugin as this one will eventually be archived.

**Comment by roccopung** [comment]
Hi @josephfusco , thank you so much for your quick reply! I am indeed using that ,will look into the new documentation then
