### ISSUE TITLE
Image field within repeater returning null when its return format is 'Image URL'

### ISSUE THREAD

**Issue by zzkevinlim** [wp-graphql/wp-graphql-acf#387]
Not sure if this is a bug or intentional, could be a ACF bug.

Same problem with Page Link.

**Comment by josephfusco** [comment]
Hey @zzkevinlim, this plugin as been rearchitected here https://github.com/wp-graphql/wpgraphql-acf and would recommend checking that out!

What version of the plugin are you using? If you're using 2.* or newer, this issue would belong in that repo. If you're using 0.6.* or older, this is the correct repo, but we will be archiving it and recommend upgrading to the [newer version](https://github.com/wp-graphql/wpgraphql-acf).

These issues look like they might be related
- https://github.com/wp-graphql/wpgraphql-acf/issues/213
- https://github.com/wp-graphql/wpgraphql-acf/issues/208

**Comment by josephfusco** [comment]
Closing this and recommending the new version of the plugin as indicated above.
