### ISSUE TITLE
Add support for Github Updater

### ISSUE THREAD

**Issue by mvaneijgen** [wp-graphql/wp-graphql-acf#41]
A while back I wanted to do this for my own plugin, because I saw it happen with a plugin also hosted on Github and I asked the maker of the plugin. [The conversation can be found here](https://github.com/mcguffin/acf-quick-edit-fields/issues/51), it goes way over my head and I myself didn't take the time to look in in myself (because my plugin rarely gets updated and it only used by me), but maybe someone here has a better understanding on how WP plugins work.

**Comment by andrewminion-luminfire** [comment]
I’ve used this before and it works pretty well: https://github.com/afragen/github-updater

@jasonbahl Do you plan to put the wp-graphql plugins on the WP.org repo eventually?

**Comment by jasonbahl** [comment]
@mvaneijgen @andrewminion-luminfire At the moment I don't have immediate plans of adding this plugin to the WordPress.org repo. Possibly in the future, but in my experience plugins like this that are intended to be used by developers get a lot of unnecessary noise in the .org forums, etc. 

I will update it to support Github Updater, and the plugin is also on packagist (https://packagist.org/packages/wp-graphql/wp-graphql-acf), so if you're using Composer you can pull in updates from composer.
