### ISSUE TITLE
Feature Request: Expose ACF fields defined on attachments

### ISSUE THREAD

**Issue by gu-stav** [wp-graphql/wp-graphql-acf#42]
It is possible to extend attachment with custom fields. These are currently not exposed through `wp-graphql-acf`, although it would be great to have!

**Comment by jasonbahl** [comment]
👋🏻  Hello! 

With v0.5.0 (#250) you can assign an ACF Field Group to MediaItems in the WPGraphQL Schema. 

Below is a screenshot of the new GraphQL Settings, and you can see that when I assign the field group to media items, it is assigned to the `MediaItem` Type in the GraphQL Schema. 

![Screen Shot 2021-04-20 at 3 55 39 PM](https://user-images.githubusercontent.com/1260765/115468826-dd2f0000-a1f0-11eb-818e-d257bf6f97cd.png)
