### ISSUE TITLE
Feature Request: Expose Field Choices

### ISSUE THREAD

**Issue by heyfletch** [wp-graphql/wp-graphql-acf#43]
Allow to get choices from an ACF field that has them, for example, Checkbox, Radio, Select, and Button Group. Screenshot shows an example of what should be returned. 

![choices](https://user-images.githubusercontent.com/658245/62982422-0ed7ad00-bdfa-11e9-9ec4-89d2a9d8cc44.jpg)

**Comment by Locheed** [comment]
Just came looking for how to populate dropdown values from the Select field's choices. Looks like I have to hard code these in the DOM right now. :/

**Comment by jasonbahl** [comment]
👋🏻 this is being tracked in the repo for the re-build of this plugin over here: https://github.com/wp-graphql/wpgraphql-acf/issues/105

Closing this as it will be discussed further in the new repo.
