### ISSUE TITLE
Multiple values Post Object ACF field not working

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#45]
Originally posted here: https://github.com/wp-graphql/wp-graphql/issues/939

----

When using a multiple values Post Object ACF field, WPGraphQL return an empty object instead of the list of post objects.

**Steps to reproduce:**

- Make a multiple values Post Object ACF field
- Try to query it

**Comment by cordial** [comment]
Is anyone looking at this? I'm also having this issue.

**Comment by cordial** [comment]
I've actually done a (pretty obvious) workaround in case anyone sees this. Just put a single post object into a repeater. Works fine.

**Comment by weareimpulse** [comment]
I have been having the same issue, I have a group of fields exposed to GraphQL, each field in the group is a Post Object field type allowing multiple id's to be stored, when accessing this user meta via GraphQL the query always returns null, at this point I can't change the fields as per @cordial suggested above as we are to far into the dev process to change this, has anybody got round this issue or looking into it as it is blocking further development on this area of the project.

Thanks for your time. Charlie

**Comment by ProwlElement** [comment]
im having the same issue i have a repeater field that I want to be able to add multiple "Project" custom post types using Post Object and all I can see is 
`{
pages {
    nodes {
      featuredProjects {
        projectCards {
          fieldGroupName
        } 
      }
    }
  }
}`

expected
`
{
  pages {
    nodes {
      featuredProjects {
        projectCards {
          project {
             title
             image
             location
            }
        } 
      }
    }
  }
}
`

This should give me access to the post object and i should be able to use it this way or am I missing something?

Any help appreciated.
Thanks,
S

**Comment by ProwlElement** [comment]
https://www.wpgraphql.com/extenstion-plugins/wpgraphql-for-custom-post-type-ui/

I just found this

**Comment by cordial** [comment]
Does using a repeater not work for you or fit your needs? My workaround, described above fixed my issue which looks the same as yours (i couldnt find a way of fixing it the original way that worked).

**Comment by ProwlElement** [comment]
I got it working using the above plugin
S

**Comment by cordial** [comment]
Ah ok, cool!

**Comment by jasonbahl** [comment]
This has been resolved for quite some time. 

To reproduce: 

## Add ACF Field

I created an ACF Field of the "Post Object" field type, and set it to allow multiple selections

![Screen Shot 2021-05-14 at 3 31 17 PM](https://user-images.githubusercontent.com/1260765/118333717-6e7c5400-b4c9-11eb-932d-d496b608952b.png)

## Edit Post with Field

Then I edited a post with this field on it, selecting multiple post objects

![Screen Shot 2021-05-14 at 3 31 51 PM](https://user-images.githubusercontent.com/1260765/118333754-82c05100-b4c9-11eb-82ec-33300c259844.png)

## Query the field

Then I queried the field: 

### v0.5.2

In WPGraphQL for ACF v0.5.2, I queried like so:

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    databaseId
    postTest {
      multiSelectPostObjectField {
        __typename
        ... on Post {
          id
          title
        }
      }
    }
  }
}
```

![Screen Shot 2021-05-14 at 3 29 52 PM](https://user-images.githubusercontent.com/1260765/118333604-3c6af200-b4c9-11eb-9afa-567fca54cafb.png)

### v0.6.0

The upcoming v0.6.0 (#262) is making some changes to the behavior with the `Post Object` field type, so it can be queried like so: 

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    databaseId
    postTest {
      multiSelectPostObjectField {
        nodes {
          __typename
          id
          databaseId
        }
      }
    }
  }
}
```

![Screen Shot 2021-05-14 at 3 34 04 PM](https://user-images.githubusercontent.com/1260765/118333919-d29f1800-b4c9-11eb-9446-b2cf387bc65e.png)
