### ISSUE TITLE
Multiple users ACF field not working

### ISSUE THREAD

**Issue by caco-jr** [wp-graphql/wp-graphql-acf#48]
https://github.com/wp-graphql/wp-graphql-acf/blob/85ec7dda331c9409f80219b7d34bebb563538b13/src/class-config.php#L576

I did a test with this code and it worked fine.

` 
 case 'user':
    $field_config = [
        'type'    => [ 'list_of' => 'User' ],
        'resolve' => function( $root, $args, $context, $info ) use ( $acf_field ) {
                $value = $this->get_acf_field_value( $root, $acf_field );
                $users = [];

                if ( ! empty( $value ) && is_array( $value ) ) {
                    foreach ( $value as $user ) {
                        $users[] = DataSource::resolve_user( (int) $user, $context );
                    }
                }

                return $users;
        },
];
break;
`

**Comment by jasonbahl** [comment]
Closed by #49
