### ISSUE TITLE
Composer and MU-plugin

### ISSUE THREAD

**Issue by DevOpsRadar** [wp-graphql/wp-graphql-acf#5]
Hey, 
When you are guys planning to push this plugin to the Composer?
Currently, this plugin requires wp-graphql v3.2 to be installed but this version doesn't exist in Composer either. 

Another problem is that when I keep ACF, GraphQL and GraphQL ACF as MU plugin it shows error in admin panel that I need to Install and activate them, even if it's already done. 

And the last issue is with activating GraphQL ACF. Even if I have all plugins correct version as described in your documentation and installed in usual "plugin" directory it gives me an error: "version cannot be empty."

Please help.

**Comment by jasonbahl** [comment]
Hey!

This plugin won’t be on Composer as it’s a premium plugin that requires to be downloaded after purchasing a license. You can update from within your dashboard much like a plugin from the .org repo. 

As far as the main WPGraphQL repo, it should be publishing to packagist every time we do a release, but I do see it hasn’t made it up there since v.0.3.01. 🤔

Some connection between GitHub and Packagist must have stopped working. I’ll look into this.

**Comment by jasonbahl** [comment]
Hey!

I got the webhook for WPGraphQL working again so it’s now updated on packagist at v0.3.3

I’ll see what I can find out from Freemius about options to let folks with a license install via composer as well, but in the meantime the ACF plugin will need to be downloaded/installed without composer, as the source code isn’t available on packagist

**Comment by DevOpsRadar** [comment]
Hey, 

I just pulled WPGraphQL to my Composer. Thank you for that. 

ACF PRO is also paid Plugin and you can download it from Public repo. The licence needs to be activated by providing key to the URL. Below is an example. Maybe you could make it work a similar way?

```
"repositories": [
		{
			"type": "composer",
			"url": "https://wpackagist.org"
		},
		{
			"type": "package",
			"package": {
				"name": "advanced-custom-fields/advanced-custom-fields-pro",
				"version": "5.7.12",
				"type": "wordpress-muplugin",
				"dist": {
					"type": "zip",
					"url": "https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k={%ACF_PRO_KEY}&t={%version}"
				},
				"require": {
					"ffraenz/private-composer-installer": "^2.0",
					"composer/installers": "^1.0"
				}
			}
		}
	],
```

**Comment by jasonbahl** [comment]
I've reached out to Freemius to see what options there are for pulling in licensed plugins via Composer. Stay tuned.

**Comment by jasonbahl** [comment]
I reached out to Freemius again yesterday and it looks like they don't support installing via Composer (yet), but are interested in supporting it. 

I'll keep following that and follow-up here if they make any progress.

**Comment by BartoszLobejko** [comment]
Sounds good @jasonbahl. It would be great to do the same for all Graphql plugins as some of them even if they are not premium still doesn't exist in Composer directory.

**Comment by jasonbahl** [comment]
The plugin is now available on packagist here: https://packagist.org/packages/wp-graphql/wp-graphql-acf

---

Also, ICYMI: This plugin is now FREE, and no longer being updated through Freemius. 

The plugin is available on Github here: https://github.com/wp-graphql/wp-graphql-acf

**Comment by rubas** [comment]
@jasonbahl
Sadly the latest version pushed to packagist is 0.2. Would you mind updating it and integrating packagist in your release workflow.
