### ISSUE TITLE
Error activating plugin

### ISSUE THREAD

**Issue by anthonycmain** [wp-graphql/wp-graphql-acf#51]
I am getting the following error trying to activate the plugin added via git cloning into a WP 5.22

Parse error: syntax error, unexpected ':', expecting '{' in /Users/XXX/repos/bsr/website backup/wp-content/plugins/wp-graphql-acf/wp-graphql-acf.php on line 89

**Comment by deciosales** [comment]
I am getting the same error trying to activate the plugin. Anyone find a solution let me know, thanks :)

**Comment by horacioh** [comment]
@jasonbahl is this bug fixable by removing the `:bool` from [this line](https://github.com/wp-graphql/wp-graphql-acf/blob/master/wp-graphql-acf.php#L89) ?

**Comment by jasonbahl** [comment]
@anthonycmain @deciosales what version of PHP are you on? 

The plugin intends to be used on PHP 7+ (https://github.com/wp-graphql/wp-graphql-acf/blob/master/wp-graphql-acf.php#L11)

@horacioh that could cause issues for PHP versions below 7.

**Comment by anthonycmain** [comment]
This appears to solve my problem @jasonbahl thank you, I updated to 7.2 from 5.6

**Comment by jasonbahl** [comment]
@anthonycmain what version of PHP are you on? Maybe I just ditch that one line 🤔

**Comment by jasonbahl** [comment]
Fixed by #66
