### ISSUE TITLE
Sometimes Fields don't show until a Field Group is trashed :thinking:

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#6]
2 people have reported that the fields are not showing in their Schema. Trashing the field group and restoring the group brings the fields back to the Schema.

**Comment by jasonbahl** [comment]
@josephcarrington reported that the presence of the `acf-json` folder in the theme causes this conflict. 

I plan to look into this further today.

**Comment by BartoszLobejko** [comment]
I can confirm that I experience the same issue and removing acf-json folder did help.

**Comment by jasonbahl** [comment]
resolved
