### ISSUE TITLE
Taxnomy returns empty [] unless 'Appearance' is set to Multi Select

### ISSUE THREAD

**Issue by cleshams** [wp-graphql/wp-graphql-acf#68]
Queries for Taxonomy fields return an empty array if not set to `Multi Select` appearance in the ACF Field Settings.

```
{ 
    taxonomyName {
        ... on TaxonomyName {
            id
            name
        }
}
```
will return 
```
{
"taxonomyName": []
}
``` 
Changing `Return Value` doesn't seem to have any bearing on the success of the query.

A quick fix I've just tried is to extend `class-config.php` at line` 586` to the following 
```
if ( ! empty( $value ) && is_array( $value ) ) {
    foreach ( $value as $term ) {
		 $terms[] = DataSource::resolve_term_object( (int) $term, $context );
	}
}
else
{
    $terms[] = DataSource::resolve_term_object( (int) $value, $context );
}
```
I haven't done any real testing here though, so welcome any other input if anyone else has experience with a similar problem.

**Comment by intelligence** [comment]
Just tested the quick fix on my end and it works great for my taxonomy field set to "select" as appearance!

**Comment by cleshams** [comment]
Great. If I get a chance I'll do a bit more testing on it later and see if there's a more robust solution, then submit a PR

**Comment by Fleuv** [comment]
What is the status on this, seems like the else statement is a proper fix.

**Comment by MateuszPaulski** [comment]
I think that proper fix should look like this since we need to return object, not an array when field type is 'select' or 'radio'

		
				$type = 'TermObjectUnion';

				if ( isset( $acf_field['taxonomy'] ) ) {
					$tax_object = get_taxonomy( $acf_field['taxonomy'] );
					if ( isset( $tax_object->graphql_single_name ) ) {
						$type = $tax_object->graphql_single_name;
					}
				}
				$is_multiple = isset($acf_field['field_type']) && in_array( $acf_field['field_type'], array('checkbox', 'multi_select'));
				if ($is_multiple) {
					$type = [ 'list_of' => $type ];
				}

				$field_config = [
					'type'    => $type,
					'resolve' => function( $root, $args, $context, $info ) use ( $acf_field, $is_multiple ) {
						$value = $this->get_acf_field_value( $root, $acf_field );
						$terms = [];
						if ( ! empty( $value ) && is_array( $value ) ) {
							foreach ( $value as $term ) {
								 $terms[] = DataSource::resolve_term_object( (int) $term, $context );
							}
						}else{
							$terms[] = DataSource::resolve_term_object( (int) $value, $context );
						}

						if ($is_multiple) {
							$terms = ! empty( $terms ) ? $terms : null;
						} else {
							$terms = ! empty( $terms[0] ) ? $terms[0] : null;
						}

						return $terms;
					},
				];
				break;
