### ISSUE TITLE
Relationships field error

### ISSUE THREAD

**Issue by homerjam** [wp-graphql/wp-graphql-acf#7]
Hi

Sorry in a rush so I will try to add more detail and a reproduction tomorrow.

I just came across an issue whereby a query for a post with a relationship field broke (returned internal server error). This went away after updating the post - I'm assuming the relationship broke somehow maybe because a project was updated. This may be an ACF issue rather than being to do with this plugin, but thought it worth mentioning.

**Comment by jasonbahl** [comment]
Ah ya, some more detail would be great here. 

It sounds though as this is behaving as expected. If you have data stored for a related object and said object no longer exists, and you query for it, you will get an error, and that's appropriate behavior.

You should _also_ still get your response though. The data should still be returned to you as fully as it can be. The relationship field might be null, but other fields that could resolve should still be resolving fine.

**Comment by jasonbahl** [comment]
Related to #12

**Comment by jasonbahl** [comment]
Fixed in the next release.
