### ISSUE TITLE
Feature request: mutation

### ISSUE THREAD

**Issue by iMohamedSamir** [wp-graphql/wp-graphql-acf#72]
Sup, wouldn't it be awesome if wp-graphql-acf supported mutation? since acf doesn't support post/get value in api _as far as I know, I tried, very hard_ even with ACF to REST API plugin

**Comment by neopanther** [comment]
much needed

**Comment by Mambi** [comment]
yes, it would be useful

**Comment by ivanjeremic** [comment]
For now, I need to use strapi or hasura because of this missing feature in wpgraphql-acf, any new status on when it will be implemented?

**Comment by imarindam** [comment]
Yes please! Much required!!

**Comment by lance-anderson** [comment]
Perhaps it's worth noting that wp-graphql exposes the [register_graphql_mutation](https://www.wpgraphql.com/functions/register_graphql_mutation/) function which be used to leverage ACF's [update_field](https://www.advancedcustomfields.com/resources/update_field/) function and other APIs for updating WP data.

**Comment by vstrelianyi** [comment]
would be great to have mutations build in the plugin. or at least there should be some kind of step-by-step instruction how to implement that...
I have tried what you have advised.. but without any success.

> Perhaps it's worth noting that wp-graphql exposes the [register_graphql_mutation](https://www.wpgraphql.com/functions/register_graphql_mutation/) function which be used to leverage ACF's [update_field](https://www.advancedcustomfields.com/resources/update_field/) function and other APIs for updating WP data.

**Comment by vstrelianyi** [comment]
would be great to have mutations build in the plugin. or at least there should be some kind of step-by-step instruction how to implement that...
I have tried what you have advised.. but without any success.

**Comment by colmobildev** [comment]
It would be very useful!

**Comment by jasonbahl** [comment]
👋🏻 We are re-building WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf. 

I've created a new issue to track mutation support (and explain some current blockers). see: https://github.com/wp-graphql/wpgraphql-acf/issues/109

I'm going to close this in favor of tracking it in the new repo.
