### ISSUE TITLE
Make Connections for Repeaters / Flex Fields

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-acf#8]
Some fields in ACF return lists. Sometimes those lists would be nice to paginate instead of get the entire list back. 

Flex Fields, Repeaters and other fields that return lists could/should return connections and support pagination, and at some point filters, etc

**Comment by cristobalbahe** [comment]
Hello there!

Did this finally got implemented? I would like to paginate relationship fields (which are also a list) and would love to know if it has been done or I should hack it :)

Thank you very much
