### ISSUE TITLE
Add data from Gatsby to WP

### ISSUE THREAD

**Issue by ivanjeremic** [wp-graphql/wp-graphql-acf#80]
I'm really sorry to put this here but I really love and test in last days Graphql WP and I'm also able to display data in my Gatsby Site, but what I'm really interested in is to create an Auth system where users can login in my Gatsby frontend and add data to WP same way I as admin go to my Custom Post Type and click on 'add new'. This data added here should then be visible on the frontend for the users but only data added by them. Any good resourses and sugguestion what I should look at?

Thanks

**Comment by jasonbahl** [comment]
@ivanjeremic I would check out WPGraphQL JWT Auth for how to do authentication with WPGraphQL. 

Also, it's not a super robust repo, but this repo shows how to authenticate and do mutations using WPGraphQL: https://github.com/wp-graphql/wpgraphql-gatsby-kanban
