### ISSUE TITLE
Layouts inside ACF Flexible Content field groups not showing up in latest version

### ISSUE THREAD

**Issue by lukemiller93** [wp-graphql/wp-graphql-acf#84]
Hi! I have a wordpress install that I've been using WPGraphQL with WPGraphQL for ACF for some time. After upgrading to WPGraphQL v0.4.0 and WPGraphQL for ACF v0.3.0 the layouts in my flexible content field groups stopped working. I was able to reproduce the issue on a fresh wp install with only WPGraphQL, WPGraphQL for ACF, and ACF Pro installed. I've also attached screenshots with the different errors I received. Any assistance would be greatly appreciated! Thanks!

![wpgraphql-flexible-content-error-1](https://user-images.githubusercontent.com/26014351/67877108-f7f64c00-fb06-11e9-8115-45f4afd63f5c.png)

![wpgraphql-flexible-content-error](https://user-images.githubusercontent.com/26014351/67877109-f88ee280-fb06-11e9-822c-97aff90b13c9.png)

**Comment by jasonbahl** [comment]
@lukemiller93 can you provide a JSON export of the field group(s) in question? I'm looking into this but could be good to reproduce your same setup.

**Comment by lukemiller93** [comment]
@jasonbahl  Here is the json export with the test fields I used.

[acf-export-2019-10-30.zip](https://github.com/wp-graphql/wp-graphql-acf/files/3790819/acf-export-2019-10-30.zip)

**Comment by jasonbahl** [comment]
@lukemiller93 thanks! Checking this out now!

**Comment by jasonbahl** [comment]
@lukemiller93 any chance you're using WPGraphQL for WooCommerce? I think this _might_ be an issue with how it uses the filter `graphql_union_resolve_type` 🤔 

@kidunot89 looks like maybe the callback function is missing here? https://github.com/wp-graphql/wp-graphql-woocommerce/blob/6eaaaa14ece0266043557444078ef194d4bee902/includes/class-core-schema-filters.php#L39

**Comment by jasonbahl** [comment]
@lukemiller93 can you also confirm that you're on WPGraphQL for ACF v0.3.0 and WPGraphQL v0.4.0?

**Comment by jasonbahl** [comment]
with WPGraphQL v0.4.0 and WPGraphQL for ACF v0.3.0, I wasn't able to replicate the issue you mentioned, but did find another issue with resolvers for unions not working. I've opened an issue on the WPGraphQL for WooCommerce repo to track: https://github.com/wp-graphql/wp-graphql-woocommerce/issues/162

**Comment by lukemiller93** [comment]
@jasonbahl I am not using the WPGraphQL for Woocommerce. See screenshot of active plugins below. If you weren't able to replicate the issue, I'll keep looking on my end and see what I can figure out.

![Screenshot_2019-10-30 Plugins ‹ testsite — WordPress](https://user-images.githubusercontent.com/26014351/67899931-533d3400-fb31-11e9-9291-c563bff3ed4b.png)

**Comment by jasonbahl** [comment]
@lukemiller93 I see that you closed this. Is this fixed by upgrading to the latest version of WPGraphQL for ACF v0.3.1? Or is there something else you had to do?

**Comment by lukemiller93** [comment]
@jasonbahl I figured out the problem. I downloaded the v0.3.0 zip file from the releases page, but the included files were from v0.2.1. Once I realized that I downloaded from the master branch, and it's working great again!

**Comment by jasonbahl** [comment]
@lukemiller93 thanks! Ya, I think somehow the v0.3.0 tag got on the wrong hash. I believe I got that fixed yesterday as well. Glad it's working for you now.
