### ISSUE TITLE
New update to wp-graphql (v0.4.0) breaks repeaters

### ISSUE THREAD

**Issue by ytwguru** [wp-graphql/wp-graphql-acf#86]
Repeaters don't work with version v0.4.0

**Comment by orjanb-ne** [comment]
I have a problem with field name being replaced by field key. This only happens in repeater fields.

**Comment by jasonbahl** [comment]
🤔 @orjanb-ne @ytwguru can ya'll provide more info so I can replicate? Such as version numbers of plugins installed (WPGraphQL, ACF and WPGraphQL for ACF)

**Comment by orjanb-ne** [comment]
I've had the same problem with:
WPGraphQL 0.4.0
ACF 5.8.7
WPGraphQL-ACF 0.3.1 

WPGraphQL 0.3.5
ACF 5.8.6
WPGraphQL-ACF 0.2.1

**Comment by jasonbahl** [comment]
Ok, great. this is helpful info. I'll see what I can find out.

**Comment by orjanb-ne** [comment]
I should probably mention that I use Gutenberg editor and WP version 5.2.4.
To make GraphQL work with Gutenberg blocks I use WP GraphQL Gutenberg 0.1.1.
https://github.com/pristas-peter/wp-graphql-gutenberg

**Comment by jasonbahl** [comment]
@orjanb-ne can you try de-activating `wp-graphql-gutenberg` for a moment and see if that makes any difference?

**Comment by orjanb-ne** [comment]
Yeah, then my syntax does not work.

**Comment by jasonbahl** [comment]
With the following plugins, I get the following results:

- ACF Pro v5.8.7
- WPGraphQL v0.4.0
- WPGraphQL for ACF v0.3.1

I can save repeater data like so:

![Screen Shot 2019-11-13 at 11 00 58 AM](https://user-images.githubusercontent.com/1260765/68791112-e1231f80-0605-11ea-8566-43d986be5b0d.png)


And query the following: 
![Screen Shot 2019-11-13 at 11 01 22 AM](https://user-images.githubusercontent.com/1260765/68791114-e1231f80-0605-11ea-9bf6-a2f69642dd59.png)

**Comment by jasonbahl** [comment]
FWIW, here's the exported PHP for the Field Group I tested:

```php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5dcc43cda6256',
	'title' => 'Repeater Test',
	'fields' => array(
		array(
			'key' => 'field_5dcc43d223db2',
			'label' => 'Repeater',
			'name' => 'repeater',
			'type' => 'repeater',
			'instructions' => 'Test',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5dcc43dd23db3',
					'label' => 'Text Field',
					'name' => 'text_field',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_in_graphql' => 1,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_graphql' => 1,
	'graphql_field_name' => 'repeaterTest',
));

endif;
```

**Comment by orjanb-ne** [comment]
Yeah, but I use blocks. Is this likely to be a blocks problem then?

**Comment by jasonbahl** [comment]
Oooh! Are you talking about ACF Gutenberg Blocks? If so, then ya, that's handled by @pristas-peter plugin, not this plugin.

**Comment by jasonbahl** [comment]
@ytwguru are you also experiencing issues with repeaters in the context of ACF Blocks? Or just regular ACF fields? If so, see the previous comment.

**Comment by jasonbahl** [comment]
Looks like this issue has moved over here: https://github.com/pristas-peter/wp-graphql-gutenberg/issues/16

If it turns out there are issues with repeaters _not_ associated with Blocks, we can re-open in this repo and look into it further.

**Comment by ytwguru** [comment]
@jasonbahl My problem was with regular repeaters.  

Had to branch off the original (v.0.3.8) of wp-graphql to support elasticsearch, but I can retest & get more information.

**Comment by jasonbahl** [comment]
@ytwguru ok, ya, if you can get me as much info as you can so I can replicate that would be great. 

Thanks!

**Comment by ytwguru** [comment]
@jasonbahl It Works!

**Comment by jasonbahl** [comment]
Oh great! Thanks for the follow-up. We'll leave this closed then. 😄
