### ISSUE TITLE
ACF Options Page GraphQL support

### ISSUE THREAD

**Issue by BartoszLobejko** [wp-graphql/wp-graphql-acf#9]
Hi,
I set up new options page and associate custom fields with it by using acf_add_options_page()
Now it looks like GraphQL schema doesn't cover this type of page. 

Am I right or I'm doing something wrong?

Are you planing to introduce support for this page type?

Regards

**Comment by jasonbahl** [comment]
Not supported quite yet. But coming soon. 

Single pages as a location is next up, then options. 😀

**Comment by devmithunnath** [comment]
Hi Jason, sorry I know that you've been quite busy these days, any updates on this?

**Comment by sergixnet** [comment]
This feature will be nice! 👍
Thanks Jason for this awesome plugin

**Comment by kwoterG** [comment]
Would be great to have this feature. 
Keep up the good work!

**Comment by jasonbahl** [comment]
Closed by #66
