### ISSUE TITLE
Error: Current PHP version does not meet minimum requirements

### ISSUE THREAD

**Issue by ericjasonthomas** [wp-graphql/wp-graphql-acf#90]
When I try to activate the plugin I receive Error: Current PHP version does not meet minimum requirements for WPGraphQL for Advanced Custom Fields.
The site is on php7.3

**Comment by jasonbahl** [comment]
@ericjasonthomas WPGraphQL for ACF specifies that PHP 7.0 is required, so you should be good on 7.3

see: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/wp-graphql-acf.php#L11

Do you know if this error is something WordPress core is doing, or is it at a lower level like at the actual PHP level? Maybe a screenshot of what you're seeing?

**Comment by ericjasonthomas** [comment]
> @ericjasonthomas WPGraphQL for ACF specifies that PHP 7.0 is required, so you should be good on 7.3
> 
> see: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/wp-graphql-acf.php#L11
> 
> Do you know if this error is something WordPress core is doing, or is it at a lower level like at the actual PHP level? Maybe a screenshot of what you're seeing?

😂Figured it out was htacess apache addhandler was set php5
Got it working now but, Thanks for following up. really appreciate it
Thanks again
