### ISSUE TITLE
Textarea not not getting auto p in repeater

### ISSUE THREAD

**Issue by intelligence** [wp-graphql/wp-graphql-acf#93]
Stumbled upon #3 as I was having issues with `<p>` not getting output when using Textarea in a repeater field.

Seems like the fix was applied to WYSIWYG but not Textarea, as when I switch from Textarea to WYSIWYG it started working.

**Comment by jasonbahl** [comment]
@intelligence is it applied in normal ACF by default when calling `get_field()` on a text field?

I could be mistaken, but it seems like if you're using a Textarea you want to control the formatting on output, but if you are using a WYSIWYG field you want to control formatting on input?

**Comment by intelligence** [comment]
With Textarea you have the option to decide how it should behave:

<img width="1139" alt="Skärmavbild 2019-12-03 kl  17 50 42" src="https://user-images.githubusercontent.com/756582/70071460-b53bfe00-15f5-11ea-8e08-9f723abe125a.png">

In my case I had applied `Automatically add paragraphs`. I find this field useful when I want a more controlled input field where users can't apply styling on their own, but still be able to do line breaks.

**Comment by jasonbahl** [comment]
@intelligence makes sense. I'll check for that config and can apply accordingly
