### ISSUE TITLE
Issue activating plugin

### ISSUE THREAD

**Issue by ezra-ihi** [wp-graphql/wp-graphql-acf#98]
When we activate the plugin, we receive the following error:

Both WPGraphQL (v0.4.0+) and Advanced Custom Fields (v5.7+) must be active for "wp-graphql-acf" to work

Both plugins are active, however the current version of WPGraphQL is 0.3.1. Do we need to install 0.4.0 to get this to work? If so, where do we download that?

Thanks!

**Comment by jasonbahl** [comment]
@ezra-ihi you can get the latest version(s) of WPGraphQL here: https://github.com/wp-graphql/wp-graphql/releases

**Comment by jasonbahl** [comment]
@ezra-ihi if you're using Composer, you can also get it here: https://packagist.org/packages/wp-graphql/wp-graphql
